CompaniTech/compani-api

controllers/eventController.js

Reverts sophiemoustard/alenvi-api#251

Revert "Feature 309 Fix Credit notes creation events select"

---

helpers/export.js

Note pour plus tard : quand on teste un ticket à envoyer directement en prod, dumper la base de prod, ne pas lancer les scripts et tester dessus

COM-659 - change number to billNumber

---

src/helpers/draftFinalPay.js
src/helpers/draftPay.js
src/repositories/ContractRepository.js
src/repositories/EventRepository.js
tests/unit/helpers/draftFinalPay.test.js
tests/unit/helpers/draftPay.test.js

Cette PR est un préambule au ticket COM-726 pour améliorer les performances des pages Fin de contrats et Paie mensuelle.

Com 726 perf

---

src/helpers/customers.js
tests/unit/helpers/customers.test.js

Lorsque l'on change l'adresse d'un bénéficiaire on change les addresses des évènements futures (jour du changement inclus)

Com 713 multiple fixes

---

tests/integration/twilio.test.js

Fix d'un import avec l'ancien 'authentification'

Fix import

---

src/helpers/bills.js
src/helpers/draftBills.js
src/helpers/fundings.js
tests/unit/helpers/bills.test.js

J'ai remarqué des soucis au moment de la facturation et du telechargement des factures notamment s'il n'y a pas de TVA

COM-788 - fix billing validation

---

src/helpers/fundings.js
src/repositories/StatRepository.js
tests/unit/helpers/fundings.test.js

- petit fix sur l'aggregation
- si on voulait modifier une version d'un financement qui avait une endDate et qu'un autre financement demarrait apres la endDate, on ne pouvait plus modifier le financement precedent

COM-833 two fixes

---

src/controllers/userController.js
src/helpers/users.js
src/models/User.js
tests/integration/users.test.js
tests/unit/helpers/users.test.js

- recupere les roles auxiliaire et referente pour voir si ca correspond. si oui tu l'ajoutes et si non, non
- userPayload.procedure = taskIds;. ici tu change ton input donc ce n'est pas mon
- essayer de mock le uuid dans les test et de ne pas le passer en parametre

Com 802 fix

---

src/controllers/balanceController.js
src/controllers/paymentController.js
src/helpers/balances.js
src/helpers/payments.js
src/models/Payment.js
src/repositories/PaymentRepository.js
tests/integration/payments.test.js
tests/integration/seed/authenticationSeed.js
tests/integration/seed/paymentsSeed.js
tests/unit/helpers/payments.test.js
tests/unit/helpers/stat.test.js

Com 860 find

---

src/models/ThirdPartyPayer.js
src/routes/payments.js
src/routes/preHandlers/payments.js
tests/integration/payments.test.js
tests/integration/seed/paymentsSeed.js

prehandler pour la creation de paiement (pour éviter que l'on puisse créer un paiement pour un utilisateur qui ne fait pas partie de notre company). 
prehandler sur la modification des paiments

Com 860 prehandlers

---

src/controllers/payDocumentController.js
src/helpers/payDocuments.js
src/models/PayDocument.js
src/routes/payDocuments.js
src/routes/preHandlers/payDocuments.js
tests/integration/payDocuments.test.js
tests/integration/seed/payDocumentsSeed.js
tests/unit/helpers/payDocuments.test.js

Seulement pour les payDocuments

COM-858 creation

---

src/models/Bill.js
src/models/CreditNote.js
src/models/Payment.js
src/models/preHooks/validate.js
src/repositories/BillRepository.js
src/repositories/CreditNoteRepository.js
src/repositories/PaymentRepository.js

Les modeles : 
- Bill
- pour BillDispatch: on n'a decide de ne pas prendre en compte la company dans l'aggregation
- page balance client
- CreditNote: page balance client
- Payment : page balance client

Com 908 bill cn payments

---

src/helpers/draftFinalPay.js
src/helpers/draftPay.js
src/models/Contract.js
src/repositories/ContractRepository.js
tests/unit/helpers/draftFinalPay.test.js
tests/unit/helpers/draftPay.test.js

Prehook pour contract.
getAuxiliaryToPay --> Page de la paie mensuelle et STC

COM-908 add prehook aggregation for contract

---

src/helpers/pay.js

COM-929 - fix wording

---

src/helpers/export.js
tests/unit/helpers/export.test.js

Le secteur ne s'affichait plus dans l'export auxiliaires

COM-931 fix sector in auxiliary export

---

src/models/Bill.js
tests/integration/seed/exportSeed.js

* COM-954 - update modal with unique constraints
* COM-954 - implement tests

COM-954 - update modal with unique constraints (#658)

---

src/models/Company.js
src/routes/companies.js
tests/integration/companies.test.js
tests/integration/seed/companiesSeed.js

Info manquante pour le pied de page du bordereau tiers-payeur

COM-934 Add siren to company model

---

src/repositories/StatRepository.js

Creer un index: startDate, endDate et type en decroissant

COM-882 ten

---

src/controllers/billSlipController.js
src/data/billSlip.html
src/helpers/billSlips.js
tests/unit/helpers/billSlips.test.js

PR sur l'ajout des infos du header/footer du template

COM-934 Add template header/footer info

---

src/repositories/StatRepository.js
tests/integration/seed/statsSeed.js
tests/integration/stat.test.js

Com 907 multiple fixes

---

src/data/taxCertificates.html
src/helpers/fundings.js
src/helpers/subscriptions.js
src/helpers/taxCertificates.js
src/repositories/EventRepository.js
tests/unit/helpers/taxCertificates.test.js

Ajout du tableau des évènements dans les attestations fiscales

Com 958 events

---

tests/integration/bills.test.js
tests/integration/seed/billsSeed.js

un test d'integration ne fait pas de mal apres le bug de ce matin

Com 977 tests

---

src/repositories/StatRepository.js
tests/integration/stat.test.js

Fix sur la durée moyenne des interventions
je n'ai pas mis le loader comme suggéré par Guillaume car je pense qu'il vaut mieux attendre d'avoir toutes les variables pour voir vraiment comment ca rend pour le chargement

COM-960 - avergae by customer

---

src/controllers/payController.js
src/helpers/pay.js
src/helpers/stats.js
src/repositories/SectorHistoryRepository.js
src/routes/events.js
src/routes/pay.js
src/routes/preHandlers/pay.js
src/routes/stats.js
tests/integration/pay.test.js
tests/integration/seed/paySeed.js
tests/integration/stat.test.js
tests/unit/helpers/pay.test.js
tests/unit/helpers/stat.test.js

COM-939 get hours balance details

---

src/data/taxCertificates.html
src/helpers/taxCertificates.js
src/models/Company.js
src/models/Establishment.js
src/models/TaxCertificate.js
src/models/User.js
src/repositories/EventRepository.js
src/routes/companies.js
tests/integration/events.test.js
tests/unit/helpers/taxCertificates.test.js

Suite a mon point avec Guillaume : 
- Creation d'une nouvelle page dans la config pour plus de cohérence,
- Ajout du representant legal dans la config (prenom / nom / fonction)
- Ajout du numero RCS d'alenvi dans l'entete de l'attestation
- La date de l'attestation correspond la date de génération
- Le numero de matricule d'un auxiliaire correspond a ses initiales + date d'arrivée

Com 958 config

---

src/helpers/balances.js
src/repositories/BillRepository.js
src/repositories/CreditNoteRepository.js
src/repositories/PaymentRepository.js
src/routes/thirdPartyPayers.js
tests/unit/helpers/balances.test.js

Périmetre interface : Admin / Coach
Périmetre pages : balance client
Cas d'usage : liste des balance client
- pas de financement APA : 
-- ligne beneficiaire : 100
-- ligne tiers payeurs (si existe) : 0
- financement APA : 
-- ligne beneficiaire : `customerParticipationRate`
-- ligne tiers payeurs (si existe) : 100 - `customerParticipationRate`

COM-760 - Add participation rate

---

src/helpers/billSlips.js
src/helpers/creditNotes.js
src/repositories/CreditNoteRepository.js
tests/integration/billSlips.test.js
tests/integration/seed/billSlipsSeed.js
tests/unit/helpers/billSlips.test.js
tests/unit/helpers/creditNotes.test.js

- Périmetre interface : admin
- Périmetre pages : bordereaux tiers payeurs
- Cas d'usage : verifier que les avoirs du tiers payeurs de lyon sont bien pris en compte dans le total affiché sur la page (pas le pdf)

COM-995 fix getBillSlips method

---

src/data/billSlip.html
src/helpers/billSlips.js
src/repositories/CreditNoteRepository.js
tests/unit/helpers/billSlips.test.js

[] J'ai verifié la fonctionnalite sur mobile - no pertinent
[] Mon code est testé unitairement - je n'ai pas eu le temps d'ajouter les tests avec les avoirs... possible de faire la MEP sans ?
[] Mon code est testé avec des tests d'intégration - non pertinent
Périmetre interface : Admin
Périmetre pages : page bordereaux des tpp
Cas d'usage : telechargement des PDF

COM-995 - add credit note in bil slips

---

src/helpers/billSlips.js
tests/unit/helpers/billSlips.test.js

- Périmetre interface : non pertinent
- Périmetre pages : non pertinent
- Cas d'usage : Non pertinent
- Autre info: Ajout d'un test unitaire + changement d'un -= en += car cela me paraissait etrange d'avoir des heures negative.

COM-995 add unit tests

---

src/helpers/constants.js
src/routes/preHandlers/users.js
tests/integration/companies.test.js
tests/integration/seed/authenticationSeed.js
tests/integration/users.test.js

- Périmetre interface : interface admin
- Périmetre pages : toutes les pages de l'interface admin
- Cas d'usage : non pertinent

COM-997 change superAdmin to adminVendeur

---

src/helpers/billSlips.js
src/helpers/bills.js
src/helpers/export.js
src/models/Bill.js
src/repositories/BillRepository.js
tests/integration/exports.test.js
tests/integration/seed/balanceSeed.js
tests/integration/seed/billSlipsSeed.js
tests/integration/seed/billsSeed.js
tests/integration/seed/exportSeed.js
tests/unit/helpers/billSlips.test.js
tests/unit/helpers/bills.test.js
tests/unit/helpers/export.test.js

[] Mon code est testé unitairement - non pertinent
[] Mon code est testé avec des tests d'intégration - non pertinent
- Périmetre interface : Coach / aidant
- Périmetre pages :
A facturer
Onglet facturation du beneficiaire 
Page facturation de l'aidant
Bordereau TPP
- Cas d'usage : creation de facture / liste des factures / generation des bordereaux

COM-663 - Rename client to thirdpartypayer for bill

---

src/helpers/historyExport.js
src/helpers/nodemailer.js
src/repositories/EventRepository.js
src/repositories/UserRepository.js
tests/integration/email.test.js
tests/unit/helpers/historyExport.test.js

- Périmetre interface : Coach / admin
- Périmetre pages : Export historique
- Cas d'usage : Exports des interventions sur un an

COM-1005 - fix timeout on interventions export

---

src/helpers/balances.js
tests/integration/balances.test.js
tests/integration/seed/balanceSeed.js
tests/unit/helpers/balances.test.js

- Périmetre interface : Admin
- Périmetre pages : balance client
- Cas d'usage : creation de prelevements en masse

COM-1024 - fix balance

---

src/helpers/balances.js
tests/integration/balances.test.js
tests/integration/seed/balanceSeed.js
tests/unit/helpers/balances.test.js

COM-1024 - fix balance (#755)

---

src/helpers/email.js
src/helpers/nodemailer.js
tests/integration/email.test.js
tests/unit/helpers/email.test.js

Fix email tests

---

src/controllers/userController.js
src/helpers/authentication.js
src/helpers/users.js
src/routes/users.js
tests/integration/companies.test.js
tests/integration/seed/authenticationSeed.js
tests/integration/users.test.js
tests/unit/helpers/authentication.test.js
tests/unit/helpers/users.test.js

- Périmetre interface : Coach / auxiliaire
- Périmetre pages : Profile auxiliaire / mon compte
- Cas d'usage : mise a jour de l'utilisateur

Com 1008 fix

---

src/controllers/userController.js
src/helpers/email.js
src/helpers/users.js
src/routes/users.js
tests/integration/seed/usersSeed.js
tests/integration/users.test.js
tests/unit/helpers/users.test.js

- Cas d'usage : refacto process mot de passe oublié

Com 1008 fix forgot password

---

src/helpers/constants.js
src/models/Role.js
src/models/User.js
src/routes/preHandlers/users.js
tests/integration/companies.test.js
tests/integration/seed/authenticationSeed.js
tests/integration/users.test.js
tests/unit/helpers/authentication.test.js

- Périmetre interface : App vendeur
renommage seller > vendor

COM-1039 - rename seller to vendor

---

src/jobs/updateRole.js

- Périmetre interface : script
- Périmetre pages : 
- Cas d'usage : mise a jour du role pour les auxiliaires inactifs

COM-1047 - fix update role

---

src/routes/customers.js

- Périmetre interface : Auxiliaire / Coach
- Périmetre pages : planning beneficaire
- Cas d'usage : affichage d'une equipe

COM-1040 - fix customer planning

---

src/helpers/constants.js
src/helpers/users.js
src/models/User.js
src/routes/users.js
tests/integration/seed/authenticationSeed.js
tests/integration/users.test.js
tests/unit/helpers/users.test.js

- Périmetre interface : admin_vendeur
- Périmetre pages : repertoire formateur
- Cas d'usage : creer des formateurs en base et verifier l'affichage 
Pour l'instant pas de creation.

Com 1037 trainer

---

.github/pull_request_template.md
src/helpers/constants.js
src/helpers/users.js
src/models/User.js
src/models/preHooks/validate.js
tests/integration/seed/finalPaySeed.js
tests/integration/seed/paySeed.js
tests/integration/seed/usersSeed.js
tests/integration/users.test.js
tests/unit/helpers/users.test.js

- Périmetre interface : vendor / client
- Périmetre roles : coach, admin_vendor
**repertoire formateur**: creer un formateur
**info beneficiaire**: creer/editer un aidant
**repertoire auxiliaire**: creer un auxiliaire

Com 1037 creation

---

src/routes/preHandlers/users.js
src/routes/users.js
tests/integration/seed/usersSeed.js
tests/integration/users.test.js

- Périmetre role : admin_vendor 
- Cas d'usage : redirection vers la page du formateur

COM-1038 authorize user update or getbyid if user has role vendor

---

src/helpers/authentication.js
src/routes/companies.js
src/routes/preHandlers/companies.js
tests/integration/companies.test.js
tests/integration/seed/authenticationSeed.js

- Périmetre interface : Vendeur et client
Vendeur : affichage et édition de la fiche profile structure
Client : admin configuration

COM-1030 - add store on company profile

---

src/routes/preHandlers/users.js

- Périmetre pages : Liste formateur
- Cas d'usage : le responsable organisme formation peut creer des formateurs

COM-1037 - add creation rights to training-manager

---

src/controllers/userController.js
src/helpers/users.js
src/routes/preHandlers/users.js
src/routes/users.js
tests/unit/helpers/users.test.js

- Périmetre interface : interface vendeur
- Périmetre roles : vendor admin 
- Cas d'usage : possibilite d'editer un formateur

COM-1038 fix update user for trainer

---

src/helpers/eventsRepetition.js
src/jobs/billDispatch.js
src/jobs/eventRepetitions.js
src/plugins/index.js
src/repositories/BillRepository.js
src/routes/scripts.js
tests/unit/helpers/eventsRepetition.test.js
tests/unit/jobs/eventRepetitions.test.js

Com 1069 staging

---

src/models/Company.js
src/models/Customer.js
src/models/ESign.js
src/models/Establishment.js
src/models/Event.js
src/models/EventHistory.js
src/models/Repetition.js
src/models/ThirdPartyPayer.js
src/models/User.js

COM-1061 Remove id virtual from user sub schema objects

---

src/controllers/userController.js
src/helpers/users.js
src/routes/users.js
tests/integration/users.test.js
tests/unit/helpers/users.test.js

- Cas d'usage : creation mdp auxiliaire, maj mdp, mdp oublie.

COM-588 add route to update password

---

src/controllers/courseController.js
src/helpers/courses.js
src/helpers/users.js
src/models/Course.js
src/routes/courses.js
tests/integration/courses.test.js
tests/unit/helpers/courses.test.js

- Périmètre interface : Vendeur
- Périmètre rôles : fiche d'édition de la formation
- Cas d'usage : Mise a jour du nom et des formatteurs

COM-1051 - update course

---

src/repositories/CustomerRepository.js
tests/integration/customers.test.js
tests/integration/seed/customersSeed.js

- Cas d'usage : Verifier que l'auxiliaire referent s'affiche bien sur le planning beneficiaire lorsque l'on selectionne un beneficiaire

COM-1072 get referent info on get customers with subscription

---

src/controllers/courseSlotController.js
src/helpers/courseSlots.js
src/helpers/courses.js
src/helpers/translate.js
src/models/Course.js
src/models/CourseSlot.js
src/routes/courseSlots.js
src/routes/index.js
src/routes/preHandlers/courseSlot.js
tests/integration/courseSlots.test.js
tests/integration/seed/courseSlotsSeed.js
tests/unit/helpers/courseSlots.test.js
tests/unit/helpers/courses.test.js

- Périmetre roles : Admin / ROF
- Cas d'usage : Ajouter / editer / supprimer des creneaux horaires pour une formation

COM-1052 - Add course slots

---

tests/integration/companies.test.js
tests/integration/users.test.js

COM-1087 add integration tests

---

src/models/User.js
src/routes/users.js
tests/integration/users.test.js

Roll-back sur les contraintes de mot de passe

COM-1063 - remove passwrod contraints

---

src/routes/contracts.js
src/routes/preHandlers/contracts.js
tests/integration/contracts.test.js
tests/integration/seed/contractsSeed.js

- Périmetre roles : aidant
- Cas d'usage : acces aux contrats mandataires

COM-1060 fix customer contracts

---

src/helpers/constants.js
src/helpers/dataExport.js
src/helpers/users.js
tests/integration/exports.test.js
tests/integration/users.test.js
tests/unit/helpers/dataExport.test.js
tests/unit/helpers/users.test.js

Mise en staging de la résolution du bug : affichage des auxiliaires qui sont partis dans le planning

COM-1101 - get all auxiliary roles on planning

---

src/models/Customer.js
src/models/Establishment.js
src/models/User.js
src/models/utils.js
src/routes/customers.js
src/routes/establishments.js
src/routes/validations/utils.js
tests/integration/customers.test.js
tests/integration/seed/customersSeed.js

- Périmetre roles : auxiliaire/coach
- Cas d'usage : On ne peut rentrer que un numero de telephone dans le champs telephone + on peut entrer ce qu'on veut dans le champs complements

COM-1073 add regex file + add other field in customer

---

src/helpers/billSlips.js
src/models/Company.js
src/routes/companies.js
tests/integration/companies.test.js
tests/unit/helpers/billSlips.test.js

- Cas d'usage : possibilite de mettre un email de support facturation dans la configuration generale

A fusionner apres la mise en staging - COM-1109

---

src/helpers/referentHistories.js
tests/unit/helpers/referentHistories.test.js

COM-988 - add referent history tests

---

src/models/User.js
src/routes/users.js
tests/integration/users.test.js

- Périmetre roles :  ROF / admin vendeur
- Cas d'usage :  MAJ du user

COM-1106 Add biography field to user

---

src/models/ReferentHistory.js
tests/integration/customers.test.js
tests/integration/seed/customersSeed.js

- Périmetre roles : helper
- Cas d'usage : information sur l'auxiliaire referente si il y en a une

COM-1053 add contact to populate referent

---

src/data/attendanceSheet.html
src/helpers/courses.js
tests/integration/seed/coursesSeed.js
tests/unit/helpers/courses.test.js

- Périmetre roles : Admin / ROF
- Cas d'usage : Téléchargement des feuilles d'émargement

Com 1085 doc

---

src/controllers/exportController.js
src/helpers/constants.js
src/helpers/dataExport.js
src/routes/exports.js
tests/integration/exports.test.js
tests/integration/seed/exportSeed.js
tests/unit/helpers/dataExport.test.js

- Cas d'usage : export referent

COM-1092 export referent

---

src/data/attendanceSheet.html

- Cas d'usage : Dans le bloc orange, comme l'image de droite est en position absolute, il faut definir une largeur pour la div englobant le texte pour ne pas que le texte passe derriere

Com 1085 mini fix

---

src/helpers/courses.js
tests/unit/helpers/courses.test.js

- Périmetre roles : Admin / ROF
- Cas d'usage : Amelioration des performance pour le telechargement du ZIP des feuilles d'émargement

Com 1085 perf

---

src/helpers/courses.js
tests/unit/helpers/courses.test.js

- Périmetre roles : ROF, admin vendeur
- Cas d'usage : dl d'attestations de fin de formation

Com 1103 fix

---

src/helpers/courses.js
tests/unit/helpers/courses.test.js

- Périmetre interface :
- Périmetre roles : Stagiaire
- Cas d'usage : je vois le formateur sur la page d'info formation

COM-1095 - add populate on trainer

---

src/controllers/courseController.js
src/data/attendanceSheet.html
src/helpers/courses.js
src/helpers/utils.js
tests/unit/helpers/courses.test.js
tests/unit/helpers/utils.test.js

- Cas d'usage : Telechargement des feuilles d'emargement
Juste un PDF avec tout - pas de zip
Diminuer la police et les espacements
Changer le titre : Emargements - Prenom Nom
Corriger le calcul de la durée

Com 1085 fix

---

src/repositories/utils.js

- Périmetre roles : coach, admin_client, auxiliaire
- Cas d'usage :  affichage des bénéficiaires sans référents (planning bénéf et modal planning aux),

COM-1108 Fix customer without referent display

---

src/models/Sector.js
src/routes/preHandlers/sectors.js
src/routes/sectors.js
tests/integration/sectors.test.js
tests/integration/seed/sectorsSeed.js

- Cas d'usage : Je ne peux pas supprimer une equipe des qu'un auxiliaire en a fait partie

COM-1152 - fix sector deletion

---

src/helpers/stats.js
src/repositories/CustomerRepository.js
src/repositories/EventRepository.js
src/repositories/StatRepository.js
src/repositories/utils.js
tests/integration/customers.test.js

- Périmetre roles : Admin / coach / auxiliaire
- Cas d'usage : Ameliorations des perfs sur le tableau de bord et sur le suivi des plans d'aide

Com 1138 blabla

---

src/controllers/userController.js
src/helpers/authentication.js
src/helpers/users.js
src/routes/courses.js
src/routes/preHandlers/users.js
tests/integration/courses.test.js
tests/integration/seed/coursesSeed.js
tests/integration/users.test.js
tests/seed/roleSeed.js
tests/unit/helpers/users.test.js

- Périmetre roles : trainer
- Cas d'usage : les formateurs ont acces a leur page d'infos et peuvent modifier leurs infos. 
+ J'ai fait un petit changement pour que si quelqu'un qui n'a que un role vendeur il accede a l'interface vendeur si il arrive sur '/' et pas sur une 404. 
+ fix COM-1142

COM-1143 trainers can update their infos

---

src/helpers/users.js
tests/integration/users.test.js
tests/unit/helpers/users.test.js

- Cas d'usage : lorsque je cree un formateur interne, il est attaché à Alenvi

COM-1162 set company to internal trainer

---

src/data/attendanceSheet.html
src/helpers/courses.js
tests/unit/helpers/courses.test.js

- Cas d'usage : fix sur les fiches d'emargement et attestations.

COM-1121 changes in attestation and attendance sheets

---

tests/end2end/seed/authenticationSeed.js
tests/seed/customerSeed.js
tests/seed/eventSeed.js
tests/seed/serviceSeed.js

- Périmetre roles : helper
- Cas d'usage : test end2end de l'agenda

Com 1151 agenda

---

src/helpers/draftFinalPay.js
src/repositories/ContractRepository.js
tests/integration/finalPay.test.js
tests/integration/seed/finalPaySeed.js

- Périmetre interface : CLient
- Cas d'usage : Fix du solde tout compte

Com 1175 staging

---

src/models/Company.js
src/routes/companies.js
tests/integration/companies.test.js

- Cas d'usage : ajout des abonnements dans le modele des Structures

COM-1164 add subscriptions field to Company

---

src/routes/preHandlers/users.js
src/routes/users.js
tests/integration/users.test.js

- Cas d'usage : on ne peut plus supprimer de coach/admin

COM-1070 can only delete helper

---

tests/integration/bills.test.js
tests/integration/companies.test.js
tests/integration/contracts.test.js
tests/integration/creditNotes.test.js
tests/integration/customers.test.js
tests/integration/events.test.js
tests/integration/finalPay.test.js
tests/integration/pay.test.js
tests/integration/payDocuments.test.js
tests/integration/payments.test.js
tests/integration/seed/authenticationSeed.js
tests/integration/seed/companiesSeed.js
tests/integration/seed/eventsSeed.js
tests/integration/taxCertificates.test.js
tests/integration/users.test.js
tests/seed/companySeed.js
tests/seed/userSeed.js
tests/unit/helpers/authentication.test.js

Ajout des tests vérifier les droits des utilisateurs sans abonnement erp sur la creation des objets suivants :
-- Factures
-- Contrats
-- Avoirs
-- Bénéficiaires
-- Évènements
-- Paie finale
-- Paie
-- Documents de paie
-- Paiements
-- Attestations fiscales

Com 1165 test

---

src/data/attendanceSheet.html
src/helpers/courses.js
src/helpers/translate.js
src/routes/preHandlers/courses.js
tests/integration/courses.test.js
tests/unit/helpers/courses.test.js

- Cas d'usage : possibilite d'ajouter des stagiaires a des formation interb2b

COM-1188 add trainee in INTERB2B courses

---

src/controllers/emailController.js
src/helpers/email.js
src/helpers/emailOptions.js
src/routes/email.js
src/routes/preHandlers/email.js
tests/integration/email.test.js
tests/integration/seed/emailSeed.js
tests/unit/helpers/email.test.js

- Cas d'usage : Un email est envoye aux formateurs à sa creation (que ce soit un nouvel utilisateur ou non)

Com 1125 all

---

tests/integration/exports.test.js
tests/seed/customerSeed.js
tests/seed/serviceSeed.js
tests/seed/userSeed.js

- Périmetre roles : helper
- Cas d'usage : tests end2end de la partie abonnements/souscriptions + fix sur l'affichage du titre de l'aidant dans la validation de la souscription

COM-1193 change seeds for test end2end

---

src/models/Customer.js
src/repositories/CustomerRepository.js
tests/end2end/seed/authenticationSeed.js
tests/end2end/seed/billingSeed.js
tests/end2end/seed/planningSeed.js
tests/integration/exports.test.js
tests/integration/seed/authenticationSeed.js
tests/integration/seed/balanceSeed.js
tests/integration/seed/billsSeed.js
tests/integration/seed/contractsSeed.js
tests/integration/seed/creditNotesSeed.js
tests/integration/seed/customersSeed.js
tests/integration/seed/exportSeed.js
tests/integration/seed/paymentsSeed.js
tests/seed/companySeed.js
tests/seed/customerSeed.js
tests/seed/userSeed.js
tests/unit/helpers/xml.test.js

Com 1193 contact

---

src/helpers/constants.js
src/helpers/users.js
src/models/User.js
src/routes/preHandlers/email.js
src/routes/users.js
tests/integration/seed/authenticationSeed.js
tests/integration/seed/courseSlotsSeed.js
tests/integration/seed/coursesSeed.js
tests/integration/seed/emailSeed.js
tests/integration/users.test.js
tests/seed/userSeed.js
tests/unit/helpers/users.test.js

- Périmetre roles : trainer/ admin
- Cas d'usage : plus de status pour les formateurs

COM-1205 remove internal/external for trainer

---

src/helpers/constants.js
tests/integration/exports.test.js
tests/unit/helpers/historyExport.test.js

- Cas d'usage : coquille corrigé dans les raisons d'annulation d'un evenement

COM-1211-fix coquille

---

tests/end2end/seed/billingSeed.js
tests/seed/companySeed.js

- Cas d'usage : test de la partie mandat du beneficiaire.

COM-1208 add some seed for testend2end billing

---

src/helpers/events.js
src/helpers/eventsRepetition.js
tests/unit/helpers/events.test.js

- Périmetre roles : Auxiliaire coach
- Cas d'usage : mise a jour d'une repetition en a affecter

COM-1217 - fix updateRepetitions

---

src/helpers/taxCertificates.js

- Cas d'usage : telechargement de l'attestation fiscale de Mickeline Arnaud

COM-1240 - fix tax certificate download

---

src/controllers/userController.js
src/helpers/users.js
src/routes/users.js
tests/unit/helpers/users.test.js

- Périmetre roles : admin/coach
- Cas d'usage : on peut ajouter un aidant qui existe deja cote vendeur, le supprimer et le re-ajouter en tant qu'aidant

Com 1209 fix

---

server.js
src/helpers/courses.js
src/helpers/translate.js
src/routes/courses.js
src/routes/preHandlers/courses.js
tests/integration/courses.test.js
tests/integration/seed/coursesSeed.js
tests/unit/helpers/courses.test.js
tests/unit/helpers/users.test.js

- Périmetre interface : vendeur/client
- Cas d'usage : update de la route pour ajouter un stagiaire : 
- uniquement avec l'email si user existe et a une structure
- avec l'email et la structure si il manque sa structure
- avec email/structure/nom_de_famille sinon

COM-1204 update route course/{id}/trainee

---

src/plugins/hapiSentry.js

- Cas d'usage : Lorsqu'il y a une erreur, cela envoie bien les informations voulues a sentry

fix sentry

---

tests/end2end/seed/planningSeed.js

Ajout de donnees dans les Seed pour les test end to end du planning auxiliaire

COM-1231 - update planning seed

---

tests/end2end/seed/planningSeed.js

- Périmetre interface : -np
- Périmetre roles : -np
- Cas d'usage : fix pour les tests end2end

COM-1231 fix test end 2 end planning

---

src/helpers/courses.js
tests/unit/helpers/courses.test.js

- Cas d'usage : filtres sur le repertoire de formations

COM-1277 populate trainees company

---

src/routes/preHandlers/email.js

- Périmetre roles : ROF/admin
- Cas d'usage : possibilite d'ajouter un coach dans une autre entreprise avec l'envoi de mail.

COM-1267 fix send email to other company when vendor

---

src/helpers/eventsValidation.js
tests/unit/helpers/events.test.js
tests/unit/helpers/eventsValidation.test.js

COM-1266-fix remove conflict check if 'toBeAssigned'

---

src/helpers/courses.js
tests/unit/helpers/courses.test.js

- Périmetre roles : trainer
- Cas d'usage : je peux filtrer les formations sur les entreprises et les programmes

COM-1279 populate trainee company for courses getList

---

src/repositories/EventRepository.js
tests/integration/seed/billsSeed.js

COM-1216 - check auxiliary contract on billing

---

src/helpers/eventsRepetition.js
src/jobs/eventRepetitions.js
tests/unit/helpers/eventsRepetition.test.js
tests/unit/jobs/eventRepetitions.test.js

- Cas d'usage : Correction du script des repetitions : si un heure interne ou une indispo est en conflit on ne la cree pas

COM-1320 - fix repetition script

---

src/routes/preHandlers/users.js
tests/integration/users.test.js

- Cas d'usage : Je peux ajouter a une structure un stagiaire inscrit dans une formation pour cette structure.

COM-1321 fix error when trying to update a trainee with a company

---

src/controllers/scriptController.js
src/helpers/eventsRepetition.js
src/jobs/eventRepetitions.js
tests/unit/helpers/eventsRepetition.test.js
tests/unit/jobs/eventRepetitions.test.js

COM-1320 - organise repetitions

---

src/controllers/userController.js
src/models/Cloudinary.js

- Périmetre interface : tous
- Cas d'usage : suppressin des roles, envoi des pp vers le dossier users/profile_pictures dans cloudinary

COM-1296 store pp in new and single folder: /profile_picture

---

src/helpers/courses.js
src/models/CourseSmsHistory.js
tests/unit/helpers/courses.test.js

- Cas d'usage : dans la modal d'historique du sms, ajout du message indiquant les stagiaire dont le numero de telephone manquait lors de l'envoi
changement de design validé avec Romain

COM-1299 - add missing phones

---

src/controllers/moduleController.js
src/helpers/modules.js
src/routes/modules.js
tests/integration/modules.test.js
tests/unit/helpers/modules.test.js

- Cas d'usage : je peux editer un module et changer le titre

COM-1314 add tests

---

src/data/attendanceSheet.html
src/helpers/courses.js
src/models/Course.js
tests/unit/helpers/courses.test.js

- Périmetre interface : vendeur/client/core
- Cas d'usage : on affiche la bonne brochette en fct du contexte, voir commentaire sur la pr du front

Com 1322 misc

---

src/helpers/constants.js
src/models/Step.js
src/routes/programs.js
tests/integration/programs.test.js
tests/integration/seed/activitiesSeed.js
tests/integration/seed/programsSeed.js
tests/integration/seed/stepsSeed.js

- Périmetre roles : rof/admin
- Cas d'usage : je peux choisir un type pour les etapes

COM-1332 add type to step

---

src/controllers/courseController.js
src/helpers/courses.js
src/models/Course.js
src/models/CourseSlot.js
src/repositories/CourseRepository.js
tests/integration/courses.test.js
tests/integration/seed/coursesSeed.js
tests/unit/helpers/courses.test.js

- Périmetre interface : client/vendeur
- Périmetre roles : coach/admin/rof/trainer
- Cas d'usage : slotsToPlan est une virtuals

COM-1335 slotsToPlan is now a virtual

---

src/controllers/activityController.js
src/helpers/activities.js
src/helpers/cards.js
src/helpers/constants.js
src/helpers/steps.js
src/models/Activity.js
src/models/Card.js
src/routes/activities.js
tests/integration/activities.test.js
tests/integration/seed/activitiesSeed.js
tests/unit/helpers/activities.test.js
tests/unit/helpers/cards.test.js
tests/unit/helpers/steps.test.js

- Périmetre interface : vendeir
- Cas d'usage : ajout de la route pour créer des cartes

COM-1308 add 'addCard' route

---

src/helpers/activities.js
tests/integration/activities.test.js
tests/integration/seed/activitiesSeed.js
tests/unit/helpers/activities.test.js

- Périmetre roles : admin rof
- Cas d'usage : j'ai ajouté la population du template des cartes a la requete Activity.getById

COM-1308-modal populate cards.template

---

src/models/Activity.js
src/models/Step.js
src/routes/activities.js
src/routes/programs.js
src/routes/steps.js
tests/integration/activities.test.js
tests/integration/programs.test.js
tests/integration/seed/activitiesSeed.js
tests/integration/seed/programsSeed.js
tests/integration/seed/stepsSeed.js
tests/integration/steps.test.js
tests/unit/helpers/activities.test.js
tests/unit/helpers/cards.test.js
tests/unit/helpers/steps.test.js

- Cas d'usage : Création / édition d'étapes et activités

COM-1360 - rename title to name

---

src/helpers/programs.js
tests/unit/helpers/programs.test.js

- Périmetre roles : admin rof
- Cas d'usage : on renseigne le type (e-leaning/presentiel) pour toutes les étapes de chaque programme dans la liste.

COM-1354 populate steps.type

---

tests/integration/courses.test.js

COM-1348 add test

---

src/helpers/courses.js
src/repositories/CourseRepository.js
tests/integration/courses.test.js
tests/integration/seed/coursesSeed.js

- Périmetre interface : Mobile
- Périmetre roles : Apprenant
- Cas d'usage : Affichage de la liste des formations

COM-1347 - add image

---

src/helpers/constants.js
src/models/Card.js

- Cas d'usage : creation d'un carte titre/texte

COM-1372 -- prochain sprint

---

src/helpers/cloudinary.js
tests/unit/helpers/cloudinary.test.js

- Périmetre interface : Toute
- Périmetre roles : Tous
- Cas d'usage : chargement d'une image dans cloudinary - retirer les caractères interdits du public_id 
https://cloudinary.com/documentation/upload_images#using_the_public_id_to_organize_media_assets_in_folders

COM-1397 - add condition on cloudinary public-id

---

src/controllers/userController.js
src/helpers/users.js
src/models/User.js
src/routes/preHandlers/users.js
src/routes/users.js
tests/integration/seed/usersSeed.js
tests/integration/users.test.js
tests/unit/helpers/users.test.js

- Cas d'usage : j'ai comparé avec l'aggregation et avec le virtual pop, les deux sont similaire et prennent a peine le tmps d'une ptite vague ( des trois rectangles roses). Du coup j'ai gardé le plus simple, le virtual pop

Com 1367 populate

---

src/helpers/constants.js
src/models/Card.js

- Cas d'usage : creation carte texte-media

COM-1375 add text media creation

---

src/helpers/contracts.js
src/helpers/eventsValidation.js
src/jobs/eventConsistency.js
src/repositories/ContractRepository.js
tests/integration/contracts.test.js
tests/integration/seed/contractsSeed.js
tests/unit/helpers/contracts.test.js
tests/unit/helpers/events.test.js
tests/unit/helpers/eventsValidation.test.js
tests/unit/helpers/pay.test.js

Com 1276 rename

---

src/models/Company.js
src/routes/companies.js
tests/integration/companies.test.js
tests/unit/helpers/companies.test.js

Suppression des templates de contrats/avenants mandataires
Telechargement des contrats prestataires (renommage dess champs)

Com 1276 template

---

src/helpers/draftPay.js
src/helpers/events.js
src/repositories/ContractRepository.js
src/repositories/EventRepository.js
src/routes/contracts.js
tests/integration/contracts.test.js
tests/unit/helpers/dataExport.test.js
tests/unit/helpers/draftPay.test.js
tests/unit/helpers/events.test.js

- Périmetre roles : Admin / coach / auxiliaires
Fin de contrat
Signature en ligne du contrat
Upload des contrats signés a la main
Paie
STC
Refacto des tests export auxiliaires

Com 1276 document

---

src/helpers/activities.js
src/models/Card.js
src/routes/cards.js
tests/integration/activities.test.js
tests/integration/cards.test.js
tests/integration/seed/activitiesSeed.js
tests/integration/seed/cardsSeed.js
tests/unit/helpers/activities.test.js

- Périmetre roles : rof/admin
- Cas d'usage : Edition des cartes flashcard

COM-1377 edition for flashcard

---

src/helpers/users.js
tests/integration/users.test.js
tests/unit/helpers/users.test.js

fix-user-contract + add test

---

src/helpers/constants.js
src/models/Activity.js
src/routes/steps.js
tests/integration/seed/activitiesSeed.js
tests/integration/seed/programsSeed.js
tests/integration/steps.test.js
tests/unit/helpers/steps.test.js

- Cas d'usage : ajout du type d'une activité

COM-1413 add activity type

---

package-lock.json
package.json
src/helpers/users.js
tests/end2end/seed/billingSeed.js
tests/end2end/seed/planningSeed.js
tests/integration/seed/balanceSeed.js
tests/integration/seed/billsSeed.js
tests/integration/seed/companiesSeed.js
tests/integration/seed/contractsSeed.js
tests/integration/seed/courseSlotsSeed.js
tests/integration/seed/coursesSeed.js
tests/integration/seed/creditNotesSeed.js
tests/integration/seed/customersSeed.js
tests/integration/seed/driveSeed.js
tests/integration/seed/emailSeed.js
tests/integration/seed/establishmentsSeed.js
tests/integration/seed/eventHistoriesSeed.js
tests/integration/seed/eventsSeed.js
tests/integration/seed/exportSeed.js
tests/integration/seed/finalPaySeed.js
tests/integration/seed/internalHoursSeed.js
tests/integration/seed/payDocumentsSeed.js
tests/integration/seed/paySeed.js
tests/integration/seed/paymentsSeed.js
tests/integration/seed/statsSeed.js
tests/integration/seed/taxCertificatesSeed.js
tests/integration/seed/twilioSeed.js
tests/integration/seed/usersSeed.js
tests/seed/userSeed.js
tests/unit/helpers/users.test.js

Je n'ai pas mis a jour sinon car pour sinon-mongoose il nous faut une version de sinon entre 5 et 7
Pour uuid, tel qu'il est importé aujourd'hui (cf la doc), je n'ai pas trouvé de moyen de le mocker et donc de contrôler le retour => c'est pour ca que j'ai enlevé la ligne `withExactArgs` car je ne controle plus le format du token ><

Com 1402 package

---

src/controllers/programController.js
src/controllers/subProgramController.js
src/helpers/programs.js
src/helpers/steps.js
src/helpers/subPrograms.js
src/helpers/translate.js
src/models/Program.js
src/models/SubProgram.js
src/routes/activities.js
src/routes/index.js
src/routes/programs.js
src/routes/steps.js
src/routes/subPrograms.js
tests/integration/activities.test.js
tests/integration/programs.test.js
tests/integration/seed/programsSeed.js
tests/integration/seed/subProgramsSeed.js
tests/integration/steps.test.js
tests/integration/subProgram.test.js
tests/unit/helpers/programs.test.js
tests/unit/helpers/steps.test.js
tests/unit/helpers/subProgram.test.js

- Cas d'usage : creation de sous programme, edition du nom

COM-1404-sub-program add subProgram model, creation, edition

---

src/helpers/constants.js
src/models/Card.js
tests/integration/seed/cardsSeed.js

- Cas d'usage : Creation de card quiz : texte a trou / qcu / qcm / mettre dans l'ordre

COM-1408 - add quiz templates constants

---

.eslintrc.js
src/helpers/courses.js
tests/unit/helpers/courses.test.js

Ajoute simplement 'address' pour être utilisé dans l'app mobile

COM-1382 - Add address to slots in get course call for /course/id/user

---

src/helpers/courses.js
tests/unit/helpers/courses.test.js

- Périmetre interface : Mobile
- Périmetre roles : Apprenant
N'envoyer que ce qui est necessaire

COM-1423 - update listUserCourses

---

src/routes/preHandlers/cards.js
tests/integration/cards.test.js

- Cas d'usage : je ne peux pas avoir de balises de la forme `<trou> </trou>` ou `<trou> test </trou>`

COM-1409 add validation for spaces around answer

---

src/models/User.js

- Cas d'usage : Affichage des contrats pour les auxiliaires inactifs
je ne savais pas ou ajouter un test et si meme c'etait pertinent...

COM-1447 - fix contract display

---

src/helpers/constants.js
tests/integration/cards.test.js

Petit Fix - Erreur sur le nombre max de mauvaises réponses possibles

COM-1409 - fix max

---

src/data/bill.html
src/helpers/bills.js
tests/unit/helpers/bills.test.js

- Périmetre roles : aidant et admin
- Cas d'usage : sur la facture pour les forfaits nuit je vois le nombre d'evenement et non pas le nombre d'heure (cf capture d'ecran sur le ticket)

COM-1452 display nbr of events on bill if service is fixed

---

src/data/bill.html
src/helpers/bills.js
tests/unit/helpers/bills.test.js

Com 1452 staging

---

src/models/Program.js
tests/integration/programs.test.js
tests/integration/seed/programsSeed.js

Suppression du lien entre les programmes et les etapes

COM-1451 - remove steps from program

---

src/helpers/eventsValidation.js
src/helpers/utils.js
tests/integration/events.test.js
tests/integration/seed/eventsSeed.js
tests/unit/helpers/utils.test.js

Com 1449 staging

---

src/controllers/subProgramController.js
src/helpers/steps.js
src/routes/preHandlers/subPrograms.js
src/routes/subPrograms.js
tests/integration/subPrograms.test.js
tests/unit/helpers/steps.test.js

- Cas d'usage : Je peux detacher une etape d'un sous programme

COM-1426 can detach step from subprogram

---

src/helpers/constants.js
src/models/Card.js

- Cas d'usage : je peux creer des cartes questionnaires (question ouverte et sondage)

COM-1438 add questionnaire template constants

---

src/helpers/activities.js
src/helpers/cards.js
src/helpers/steps.js
src/helpers/subPrograms.js
src/routes/activities.js
src/routes/preHandlers/activities.js
src/routes/preHandlers/programs.js
src/routes/preHandlers/steps.js
src/routes/preHandlers/subPrograms.js
src/routes/programs.js
src/routes/steps.js
src/routes/subPrograms.js
tests/integration/activities.test.js
tests/integration/programs.test.js
tests/integration/seed/stepsSeed.js
tests/integration/steps.test.js
tests/integration/subPrograms.test.js
tests/unit/helpers/activities.test.js
tests/unit/helpers/cards.test.js
tests/unit/helpers/steps.test.js
tests/unit/helpers/subProgram.test.js

- Cas d'usage : je peux reutiliser/dupliquer une activité

Com 1429 reuse

---

src/routes/preHandlers/steps.js
src/routes/steps.js
tests/integration/seed/stepsSeed.js
tests/integration/steps.test.js

- Périmetre interface : venderu
- Cas d'usage : on bloque la réutilisation des activités d'une mm etapes

COM-1429-same-step

---

src/controllers/activityController.js
src/controllers/cardController.js
src/controllers/courseController.js
src/controllers/programController.js
src/controllers/stepController.js
src/helpers/activities.js
src/helpers/translate.js
src/routes/preHandlers/steps.js
src/routes/steps.js
tests/integration/steps.test.js
tests/unit/helpers/activities.test.js

- Périmetre roles : admin rof
- Cas d'usage : retrait d'une activité

COM-1437 detach activities

---

src/routes/preHandlers/cards.js
tests/integration/cards.test.js

- Cas d'usage : on accepte pas les saut de ligne entre les balise <trou></trou>

COM-1410-template-fix fix regexp

---

tests/integration/cards.test.js
tests/integration/seed/cardsSeed.js

- Cas d'usage : test d'integration pour edition question ouverte

COM-1439 add test for open question edition

---

src/helpers/activities.js
src/models/Activity.js
src/models/Step.js
tests/integration/activities.test.js
tests/integration/seed/activitiesSeed.js
tests/unit/helpers/activities.test.js

- Périmetre roles : admin rof
- Cas d'usage : populate le nom du programme dans la route GET /activities

COM-1430 populate program name in activities.getById

---

src/routes/activities.js
src/routes/preHandlers/activities.js
src/routes/programs.js
src/routes/steps.js
src/routes/subPrograms.js
tests/integration/activities.test.js
tests/integration/programs.test.js
tests/integration/steps.test.js
tests/integration/subPrograms.test.js

- Périmetre roles : ROF / Admin
- Cas d'usage : Drag and drop des cards dans les activités

COM-1459 - drag and drop cards

---

src/helpers/constants.js
src/helpers/subPrograms.js
src/models/Activity.js
src/models/Step.js
src/models/SubProgram.js
src/routes/preHandlers/subPrograms.js
src/routes/subPrograms.js
tests/integration/seed/subProgramsSeed.js
tests/integration/steps.test.js
tests/integration/subPrograms.test.js
tests/unit/helpers/subProgram.test.js

- Périmetre roles : rof/admin
- Cas d'usage : Possibilite de publier un sous programme. Les etapes et activites de ce sous programme sont alors publies + impossible de modifier le nom du sous programme

COM-1460 publish subprogram

---

src/helpers/users.js
tests/integration/users.test.js
tests/unit/helpers/users.test.js

- [n] Mon code est testé unitairement
Refacto : enlever expiresIn

COM-1496 - remove expiresIn

---

src/routes/preHandlers/cards.js
tests/integration/cards.test.js
tests/integration/seed/cardsSeed.js

- Cas d'usage : interdit de supprimer une carte d'une activité publiée

COM-1469 add pre for card deletion on published activities

---

src/controllers/activityHistoryController.js
src/helpers/activityHistories.js
src/helpers/translate.js
src/models/ActivityHistory.js
src/routes/activityHistories.js
src/routes/index.js
src/routes/preHandlers/activityHistories.js
tests/integration/activityHistories.test.js
tests/integration/seed/activityHistoriesSeed.js
tests/unit/helpers/activityHistories.test.js

Ajout d'une activityHistory - contenant un userId, une activityId et une date - lorsque qu'une activité est terminée

Com 1464 - ActivityHistory

---

src/controllers/courseController.js
src/helpers/courses.js
src/models/Activity.js
src/models/Course.js
tests/integration/courses.test.js
tests/integration/seed/coursesSeed.js
tests/unit/helpers/courses.test.js

- Cas d'usage : Lorsqu'une activité est complétée elle apparait en vert. 
premieir commit: a la main
deuxieme commit: avec virtuals

Com 1465 2

---

src/routes/preHandlers/activityHistories.js
tests/integration/activityHistories.test.js
tests/integration/seed/activityHistoriesSeed.js

- Cas d'usage : quand on quitte une activité avec des questions ouvertes nos réponses aux questions ouvertes sont enregistrées et affichées si l'on revient sur la question

COM-1507: units and integration test for open question

---

src/helpers/courses.js
src/models/Program.js
src/routes/programs.js
tests/integration/courses.test.js
tests/integration/programs.test.js
tests/integration/seed/coursesSeed.js
tests/unit/helpers/courses.test.js

- Cas d'usage : renommage de "objectif pédagogique" en "description"

COM-1498 rename learningGoals to description

---

package-lock.json
package.json

COM-1548 upgrade bcrypt

---

src/helpers/activities.js
src/models/Card.js
src/models/validations/cardValidation.js
tests/integration/cards.test.js
tests/integration/courses.test.js

La validation des cartes se fait désormais par le back et est renvoyé sous forme d'un virtual 'isValid'

COM-1555 - Add virtual isValid to card

---

src/helpers/programs.js
src/models/Activity.js
tests/integration/activities.test.js
tests/integration/courses.test.js
tests/integration/programs.test.js
tests/integration/seed/programsSeed.js
tests/unit/helpers/programs.test.js

Ajout d'un virtual areCardsValid uniquement si les cartes sont populées et qui est true si toutes les cartes ont isValid === true.

COM-1527 - Add areCardsValid virtual

---

src/models/Activity.js
src/models/Step.js
tests/integration/courses.test.js
tests/integration/programs.test.js
tests/unit/helpers/programs.test.js

Ajout champ virtuel areActivitiesValid à step, qui est à true si step est populé et que ses activités sont toutes valides

COM-1528 - Add areActivitiesValid virtual

---

src/routes/activities.js

- Cas d'usage : ajout modification du type d'une activité

COM-1574 added type to payload

---

src/helpers/historyExport.js
src/repositories/EventRepository.js
tests/unit/helpers/historyExport.test.js

- Périmetre roles : admin/coach
- Cas d'usage : Je peux faire un export des evenements. (j'ai teste sur dev, ca a l'air de fonctionner)

Com 1581 populate

---

src/helpers/subscriptions.js
src/routes/customers.js
tests/integration/customers.test.js
tests/unit/helpers/subscriptions.test.js

- Cas d'usage : quand je supprime une souscription, ca la supprime des souscriptionHistory

COM-1572 remove sub from subHistory

---

src/helpers/draftPay.js
tests/unit/helpers/draftPay.test.js

- Cas d'usage : Lorsque je met une facture telephonique ca met bien les frais telephonique sur la paie, si je l'enleve, ca enleve bien les frais telephonique sur la paie

COM-1549 fix phonefees if there was a phone invoice

---

src/helpers/courses.js
tests/unit/helpers/courses.test.js

- Cas d'usage : POur le suivi des réponses des stagiaires, on ne prend que la dernière réponse par utilisateur

Com 1516 user

---

src/helpers/emailOptions.js

- Périmetre interface : ALL
- Périmetre roles : ALL
- Cas d'usage : lorsque je reçois une invite pour créer mon espace Compani, on m'informe de la démarche a suivre si mon lien expire.

COM-1593 edited baseWelcomeContent

---

src/routes/preHandlers/courses.js
tests/integration/courses.test.js

- Cas d'usage : Je peux aller sur l'onglet formation d'un stagiaire sans entreprise sans qu'il y ait d'erreur

COM-1607 fix error on course page for trainee without company

---

src/controllers/cardController.js
src/helpers/cards.js
src/models/Card.js
src/models/validations/cardValidation.js
src/routes/cards.js
src/routes/preHandlers/cards.js
tests/integration/cards.test.js
tests/integration/seed/cardsSeed.js
tests/unit/helpers/cards.test.js

- Périmetre roles : ROF / admin
- Cas d'usage : edition des reponses possible des cartes QUESTION_REPONSES

Com 1596 edition

---

src/helpers/customers.js
src/repositories/CustomerRepository.js
tests/unit/helpers/authentication.test.js
tests/unit/helpers/customers.test.js

- Cas d'usage : Uniformiser la warning sur le répertoire et sur la fiche bénéficiaire

COM-1608 - from aggregation to populate

---

src/controllers/serviceController.js
src/helpers/services.js
src/helpers/subscriptions.js
src/routes/customers.js
src/routes/preHandlers/customers.js
src/routes/services.js
tests/integration/customers.test.js
tests/integration/seed/customersSeed.js
tests/integration/services.test.js
tests/unit/helpers/services.test.js
tests/unit/helpers/subscriptions.test.js

- Périmetre roles : admin/coach
- Cas d'usage : Je ne peux pas creer ou editer une souscription avec un service archivé (cf point 2 du ticket)
J'ai fait une mini refacto sur la suppressoin de souscription en passant une partie du helper dans le prehandler.

Com 1587 2

---

src/routes/preHandlers/events.js
tests/integration/events.test.js
tests/integration/seed/eventsSeed.js

- Périmetre roles : aux/coach/admin
- Cas d'usage : Si un service est archive, je ne peux pas ajouter/modifier un evenement avec une souscription liée a ce service.

COM-1587 cant add or edit event with service archived

---

src/controllers/cardController.js
src/helpers/cards.js
src/routes/cards.js
src/routes/preHandlers/cards.js

- Cas d'usage : je peux supprimer une reponse (les tests arrivent)

Com 1596 deleteAnswer

---

src/controllers/courseSlotController.js
src/helpers/constants.js
src/helpers/courseHistories.js
src/helpers/courseSlots.js
src/models/CourseHistory.js
tests/integration/courseSlots.test.js
tests/unit/helpers/courseHistories.test.js
tests/unit/helpers/courseSlots.test.js

- Périmetre roles : ROF / ADMIN / COACH
Lorsqu'un créneau est créé, un courseHistory est créé.

Com 1611 - CourseHistory

---

src/helpers/constants.js
src/routes/cards.js
src/routes/preHandlers/cards.js
tests/integration/cards.test.js

- Cas d'usage : je suis limité a 450 caracteres

COM-1552 FlashCard add back validation

---

src/controllers/programController.js
src/helpers/courses.js
src/helpers/programs.js
src/models/Activity.js
src/models/Course.js
src/routes/preHandlers/programs.js
src/routes/programs.js
tests/integration/programs.test.js
tests/integration/seed/programsSeed.js
tests/unit/helpers/programs.test.js

- Cas d'usage : lorsque j'appuie sur commencer/continuer j'arrive sur la prochaine activité à faire. Vu avec Romain: Si j'ai fini toutes les activites, j'arrive sur la page des etapes

Com 1615 refresh

---

src/helpers/courseHistories.js
src/routes/courseHistories.js
tests/integration/courseHistories.test.js
tests/integration/seed/courseHistoriesSeed.js
tests/unit/helpers/courseHistories.test.js

- Périmetre interface : vendor / client
- Périmetre roles : coach / rof / admin
- Cas d'usage : Ajout du infinite scroll. Ajout sur la PR : https://github.com/sophiemoustard/alenvi-api/pull/1097

Com 1611 infinite scroll

---

src/controllers/courseSlotController.js
src/helpers/constants.js
src/helpers/courseHistories.js
src/helpers/courseSlots.js
src/models/CourseHistory.js
tests/integration/courseSlots.test.js
tests/unit/helpers/courseHistories.test.js
tests/unit/helpers/courseSlots.test.js

- Périmetre roles : ROF / Admin / Coach
Lorsque je supprime un créneau, il apparait dans l'historique des modifications de créneau.

COM-1612 - Create coursehistory on slot deletion

---

src/controllers/courseSlotController.js
src/helpers/constants.js
src/helpers/courseHistories.js
src/helpers/courseSlots.js
src/models/CourseHistory.js
tests/integration/courseSlots.test.js
tests/unit/helpers/courseHistories.test.js
tests/unit/helpers/courseSlots.test.js

- Cas d'usage : je vois lhistorique dune modif de jour

COM-1618 creation of CourseHistory object at updateCourseSlot()

---

src/helpers/courses.js
src/helpers/steps.js
tests/integration/courses.test.js
tests/unit/helpers/courses.test.js
tests/unit/helpers/steps.test.js

- Cas d'usage : calcul de la progression dans le back et renvoi de cette dernière dans la formation

Com 1601 refacto

---

src/controllers/courseController.js
src/helpers/constants.js
src/helpers/courseHistories.js
src/helpers/courses.js
src/models/CourseHistory.js
tests/integration/courses.test.js
tests/unit/helpers/courseHistories.test.js
tests/unit/helpers/courses.test.js

- Périmetre interface : vendor / client
- Périmetre roles : rof / coach / admin
Lorsque je supprime un apprenant, je le vois dans l'historique

COM-1614 - Add course history on trainee deletion

---

src/helpers/contracts.js
src/helpers/dpae.js
src/models/BillNumber.js
src/models/BillSlip.js
src/models/BillSlipNumber.js
src/models/Contract.js
src/models/ContractNumber.js
src/models/CreditNoteNumber.js
src/models/PaymentNumber.js
src/models/QuoteNumber.js
src/models/Rum.js
tests/end2end/seed/billingSeed.js
tests/end2end/seed/planningSeed.js
tests/integration/contracts.test.js
tests/integration/seed/billsSeed.js
tests/integration/seed/contractsSeed.js
tests/integration/seed/eventsSeed.js
tests/integration/seed/exportSeed.js
tests/integration/seed/finalPaySeed.js
tests/integration/seed/paySeed.js
tests/integration/seed/statsSeed.js
tests/integration/seed/usersSeed.js
tests/unit/helpers/contracts.test.js
tests/unit/helpers/customers.test.js
tests/unit/helpers/dpae.test.js

- Cas d'usage : Ajout du matricule sur les contrats

Com 1605 contract

---

src/helpers/courseHistories.js
src/models/CourseHistory.js
tests/integration/courseSlots.test.js
tests/unit/helpers/courseHistories.test.js

- Cas d'usage : je sais si un créneau a changé d'horaire

COM-1619 new hour

---

src/helpers/constants.js
src/models/Card.js
src/routes/cards.js
tests/integration/cards.test.js

- Périmetre roles : rof / admin
Sur une carte TitleMedia, je peux sélectionner l'input que je souhaite (image, video ou audio).
Ce qu'il manque sur cette PR :
- La gestion de l'upload par GCS (google cloud)
- Tests pour savoir si l'upload des video et des audios sont bien bloqués ?

Com 1628 - Upload Image, Video and Audio

---

src/routes/users.js

- Périmetre roles : client admin
- Cas d'usage : ajouter un apprenant sans role

COM-1631 user roles are not required anymore

---

package-lock.json
package.json
src/helpers/cards.js
src/helpers/gCloudStorage.js
src/models/Google/Storage.js
tests/integration/cards.test.js
tests/unit/helpers/cards.test.js

Passage de Clourdinary à Google Cloud Storage

Com 1628 - Google Cloud Storage

---

src/helpers/constants.js
src/models/Activity.js

- Cas d'usage : ajout type QUESTIONNAIRE pour les activités

COM-1627 add QUESTIONNAIRE activity type

---

src/helpers/users.js
tests/unit/helpers/users.test.js

- Périmetre roles : client admin
- Cas d'usage : dans le repertoire apprenant je ne vois pas les aidants ni les auxiliariesWithoutOrganisation

COM-1631 add filter to learnerDirectory on client side

---

src/helpers/courses.js
tests/unit/helpers/courses.test.js

Je vois les infos complementaires d'une formation sur la page mes formations et detail d;une formation

COM-1634 add misc in return course for user

---

src/controllers/cardController.js
src/helpers/cards.js
src/helpers/gCloudStorage.js
src/routes/cards.js
src/routes/preHandlers/cards.js
tests/integration/cards.test.js
tests/integration/seed/cardsSeed.js
tests/unit/helpers/cards.test.js

- Cas d'usage : Suppression des images des cartes sur GCS

COM-1628 - add deletion route

---

src/helpers/courses.js
src/helpers/users.js
src/models/User.js
tests/unit/helpers/courses.test.js
tests/unit/helpers/users.test.js

- Périmetre interface : vendeur et client 
- Périmetre roles : client admin vendor admin
- Cas d'usage : je recuppere le format de ma formation , et le nombre de formations elearning

Com 1630 LearnersInfo

---

src/controllers/payController.js
src/helpers/contracts.js
src/helpers/dpae.js
src/routes/pay.js
tests/integration/pay.test.js
tests/unit/helpers/dpae.test.js

- Cas d'usage : En tant qu'admin je peux exporter les données de contrat pour les mettre a jour dans mon logiciel de paie

COM-1623 - epoxt contract info to 123paie

---

src/controllers/payController.js
src/helpers/constants.js
src/helpers/contracts.js
src/helpers/dpae.js
src/routes/pay.js
tests/unit/helpers/dpae.test.js

- Cas d'usage : Je peux exporter les données d'avenants de contrats des auxiliaires de ma structure

Com 1623 version

---

src/helpers/subPrograms.js
tests/unit/helpers/subPrograms.test.js

- Périmetre interface : mobile & vendeur
- Périmetre roles : apprenant testeur & vendor admin
mobile: je peux voir les formations a tester
vendeur: quand je publie un sp une formation strictlyELearning est crée

Com 1641 refacto with virtual IsStrictlyELearning

---

src/routes/preHandlers/users.js

Refacto du preHandler updateUser pour plus de lisibilité

COM-1638 - update prehanlder

---

src/controllers/courseController.js
src/helpers/courses.js
src/routes/courses.js
src/routes/preHandlers/courses.js
tests/integration/courses.test.js
tests/unit/helpers/courses.test.js

- Périmetre interface : vendeur client
- Périmetre roles : rof
- Cas d'usage : je vois la liste des formations d'un apprenant

Com 1630 list user course

---

src/helpers/draftPay.js
src/helpers/historyExport.js
src/repositories/EventRepository.js
tests/integration/exports.test.js
tests/integration/seed/exportSeed.js
tests/unit/helpers/draftPay.test.js
tests/unit/helpers/historyExport.test.js

Ajout des tests sur la PR d'ajout des heures sur l'export d'absence

Com 1625 - Ajout des tests

---

src/helpers/courses.js
src/routes/courses.js
src/routes/preHandlers/courses.js
tests/integration/courses.test.js
tests/unit/helpers/courses.test.js

- Périmetre interface : vendeur / client
- Périmetre roles : rof / coach
- Cas d'usage : le format de la formation s'affiche correctement sur ProfileCourse

Com 1630 fix

---

src/controllers/userController.js
src/helpers/users.js
src/routes/users.js
tests/integration/users.test.js
tests/unit/helpers/users.test.js

- Cas d'usage : vérifier si l'email entré existe déjà ou non

COM-1653: create route

---

src/controllers/categoryController.js
src/helpers/categories.js
src/helpers/translate.js
src/models/Category.js
src/routes/categories.js
src/routes/index.js
src/routes/preHandlers/categories.js
tests/integration/categories.test.js
tests/integration/seed/categoriesSeed.js
tests/unit/helpers/categories.test.js

- Cas d'usage : je peux voir et ajouter des catégories dans l'onglet configuration

Com 1657 view and add categories

---

src/controllers/categoryController.js
src/helpers/categories.js
src/helpers/translate.js
src/routes/categories.js
src/routes/preHandlers/categories.js
tests/integration/categories.test.js
tests/unit/helpers/categories.test.js

- Cas d'usage : je peux modifier le nom dune categorie

Com 1657 update (PUT ROUTE)

---

src/controllers/categoryController.js
src/helpers/categories.js
src/helpers/translate.js
src/routes/categories.js
src/routes/preHandlers/categories.js
tests/integration/categories.test.js
tests/unit/helpers/categories.test.js

- Cas d'usage : route supp
Il faudra vérifier dans la COM-1658 qu'aucun programme n’est rattaché a une catégorie avant la suppression d'une d'elles

Com 1657 delete

---

src/helpers/courses.js
tests/unit/helpers/courses.test.js

populate de accessRules pour les récupérer en front

Com 1655 - Tabs

---

src/controllers/courseController.js
src/helpers/courses.js
src/helpers/translate.js
src/routes/courses.js
src/routes/preHandlers/courses.js
tests/integration/courses.test.js
tests/integration/seed/coursesSeed.js
tests/unit/helpers/courses.test.js

Création de la route post pour ajouter des règles d'accès à une formation

Com 1655 - POST

---

src/controllers/surchargeController.js
src/helpers/surcharges.js
src/helpers/translate.js
src/routes/preHandlers/surcharges.js
src/routes/surcharges.js
tests/integration/surcharges.test.js
tests/unit/helpers/surcharges.test.js

Refonte des plans de majorations - ajout du code dans les services + tests unitaires

Refacto surcharge

---

src/helpers/courses.js
src/models/Program.js
src/routes/programs.js
tests/integration/courses.test.js
tests/integration/programs.test.js
tests/integration/seed/coursesSeed.js
tests/integration/seed/programsSeed.js
tests/unit/helpers/courses.test.js

Cote ROF : Edition du champs Objectifs pedagogiques
Cote ROF / Formateur / Structure : telechargement des attestations de fin de formations

COM-1660 - add learning goals

---

src/helpers/courses.js
src/helpers/subPrograms.js
tests/integration/courses.test.js
tests/integration/seed/coursesSeed.js
tests/unit/helpers/courses.test.js
tests/unit/helpers/subPrograms.test.js

- Périmetre interface : Mobile
- Périmetre roles : tous (rof pour les tests - elearning)
- Cas d'usage : on affiche la description sur le catalogue et la page mes formations.

COM-1664 return description in listUserCourses and listELearningDraft

---

src/helpers/users.js
src/routes/preHandlers/users.js
src/routes/users.js
tests/integration/seed/usersSeed.js
tests/integration/users.test.js
tests/unit/helpers/users.test.js

- Périmetre roles : aucun
- Cas d'usage : je peux créer un compte sans avoir de rôle et sans être connecté

COM-1653: allow to create user to non registered person

---

src/controllers/courseController.js
src/helpers/courses.js
src/helpers/translate.js
src/routes/courses.js
src/routes/preHandlers/courses.js
tests/integration/courses.test.js
tests/unit/helpers/courses.test.js

- Périmetre roles : rof / admin
Je peux supprimer une règle d'accès

COM-1655 - add delete route

---

src/data/courseConvocation.html
src/helpers/courses.js
src/helpers/utils.js
tests/unit/helpers/courses.test.js

- Périmetre interface : LEss 2
- Périmetre roles : ROF / Coach
- Cas d'usage : Ameliration du design des feuilles d'emargement

Com 1661 design

---

tests/integration/bills.test.js
tests/integration/events.test.js
tests/integration/seed/companiesSeed.js
tests/integration/seed/customersSeed.js
tests/unit/helpers/bills.test.js
tests/unit/helpers/contracts.test.js
tests/unit/helpers/courses.test.js
tests/unit/helpers/dpae.test.js
tests/unit/helpers/draftPay.test.js
tests/unit/helpers/eventHistories.test.js
tests/unit/helpers/events.test.js
tests/unit/helpers/historyExport.test.js
tests/unit/helpers/pay.test.js
tests/unit/helpers/stat.test.js
tests/unit/helpers/subscriptions.test.js

- Cas d'usage : le resultat de mon tour des seeds. J'ai parcouru tous les dossiers dans le dossiers tests (a part integration/assets car il ne me semblait pas pertinent).

Com 1532 seeds

---

src/controllers/cardController.js
src/helpers/cards.js
src/routes/cards.js
src/routes/preHandlers/cards.js
tests/integration/cards.test.js
tests/integration/seed/cardsSeed.js
tests/unit/helpers/cards.test.js

Route POST pour ajouter une réponse à qcm et qcu. Adaptation de la route de questionAnswer

Com 1691 - post

---

src/routes/preHandlers/cards.js
tests/integration/cards.test.js
tests/integration/seed/cardsSeed.js

- Cas d'usage : je peux ajouter et supprimer des orderedAnswers

Com 1690 post delete orderedAnswers

---

src/helpers/steps.js
tests/integration/courses.test.js
tests/unit/helpers/steps.test.js

- Périmetre roles : aucun
- Cas d'usage : Je peux faire des activites d'etapes presentielles

COM-1702 on site progress take activity progress into account

---

src/routes/preHandlers/cards.js
tests/integration/cards.test.js
tests/integration/seed/cardsSeed.js

Suppression et ajout de falsyGapAnswer via la route voulue

Com 1693 post delete

---

src/models/Activity.js
src/models/Step.js
tests/integration/seed/subProgramsSeed.js
tests/integration/subPrograms.test.js

- [ np ] Mon code est testé unitairement
- [ np ] Mon code est testé avec des tests d'intégration
- Cas d'usage : une activité n'est pas valide si elle n'a pas de carte, une étape elearning n'est pas valide si elle n'a pas d'activité

COM-1700 rules to publish sub-program

---

src/helpers/authentication.js
src/helpers/users.js
tests/integration/users.test.js
tests/unit/helpers/users.test.js

- Cas d'usage : Je ne suis plus deconnecté du mobile. 
Pour tester, vous pouvez ajouter cette ligne dans la methode validate de authentication `if (moment().add(1, 'day').subtract(1, 'minute').isAfter(moment(decoded.exp, 'X'))) throw Boom.unauthorized();` et verifier qu'apres une minute, vous avez bien : 
- une 401 sur la route appelée
- une 200 sur le refresh token
- une 200 sur la premiere route (re-appelée automatiquement)

Com 1689 expiration

---

.github/workflows/lint.yml
.github/workflows/node.js.yml

- Cas d'usage : Utilisation des dernieres versions de githubActions

use last version for actions

---

src/controllers/userController.js
tests/integration/users.test.js

- Périmetre roles : aucun
- Cas d'usage : Sur les anciennes versions de l'app (tester sur dev) je peux faire mot de passe oublié

COM-1772 send mailInfo in forgotPassword for backward compatibility

---

src/data/courseConvocation.html
src/data/interAttendanceSheet.html
src/data/intraAttendanceSheet.html
tests/unit/helpers/billSlips.test.js
tests/unit/helpers/taxCertificates.test.js

- Périmetre interface : Toutes
- Périmetre roles : Toutes
- Cas d'usage : Migration des liens cloudinary vers GCS

COM-1736 - move link from cloudinary to GCS

---

src/helpers/constants.js
src/helpers/payDocuments.js
src/routes/payDocuments.js
tests/integration/payDocuments.test.js
tests/unit/helpers/payDocuments.test.js

- Cas d'usage : Je peux charger un document de paie pour l'auxiliaire

COM-1717 - refacto upload pay document

---

tests/unit/helpers/companies.test.js

COM-1781 - companies tests

---

tests/unit/helpers/activities.test.js

- Cas d'usage : passage aux stubs

Com 1781 activities unit tests

---

src/controllers/versionController.js
src/helpers/version.js
src/routes/version.js
tests/integration/version.test.js
tests/unit/helpers/version.test.js

- Cas d'usage : check si la version mobile est bien compatible (PR 1)

COM-1771: check update version

---

src/controllers/attendanceSheetController.js
src/controllers/userController.js
src/helpers/attendanceSheets.js
src/helpers/gCloudStorage.js
src/helpers/translate.js
src/models/AttendanceSheet.js
src/models/Course.js
src/routes/attendanceSheets.js
src/routes/index.js
src/routes/preHandlers/attendanceSheets.js
tests/integration/attendanceSheets.test.js
tests/integration/seed/attendanceSheetsSeed.js
tests/unit/helpers/attendanceSheets.test.js

- Cas d'usage : je peux uploader mes feuilles d'émargement
BUCKET A AJOUTER DANS LE `.env` !! `GCS_COURSE_BUCKET=compani-course-test`

Com 1751 upload attendanceSheets

---

src/controllers/versionController.js
src/helpers/version.js
src/routes/version.js
tests/integration/version.test.js
tests/unit/helpers/version.test.js

- Périmetre roles : N/A
- Cas d'usage : A tester sur les branches dev ET master de mobile: verifier que l'application demande bien de mettre a jour quand necessaire. 
Note: il faut changer API_VERSION dans le .env et lors de la mes/mep --> la format passe de 1.0.0 à 1.

Com 1771 staging

---

src/helpers/courses.js
tests/unit/helpers/courses.test.js

- Périmetre roles : coach admin
- Cas d'usage : je peux voir les formations de ma structure

COM-1752 filter courses

---

src/models/validations/cardValidation.js
src/routes/preHandlers/cards.js
tests/integration/cards.test.js

- Périmetre interface : VENDEUR
quand je rempli une carte Mettre dans l'ordre, je n'ai pas de limite de caracteres dans les reponses

COM-1825 - remove max length on order the sequence

---

src/helpers/draftFinalPay.js
src/helpers/pay.js
tests/unit/helpers/draftFinalPay.test.js
tests/unit/helpers/pay.test.js

Com 1833 staging

---

src/helpers/courses.js
tests/integration/courses.test.js
tests/unit/helpers/courses.test.js

- Cas d'usage : envoi de description et objectifs pédagogiques dans la route courses

COM-1806: return description and learningGoals

---

src/helpers/courses.js
tests/integration/courses.test.js
tests/unit/helpers/courses.test.js

- [np] Mon code est testé avec des tests d'intégration
- Cas d'usage : je vois les activités questionnaires

COM-1817 populate activities

---

src/helpers/activityHistories.js
tests/unit/helpers/activityHistories.test.js

- Périmetre roles : coach
- Cas d'usage : je vois le top des apprenants

COM-1800 get user identity

---

src/helpers/courses.js
tests/unit/helpers/courses.test.js

- Cas d'usage : j'ai accès à des informations complémentaires dans le "à propos" des formations mixtes

COM-1808: populate contact & trainer

---

src/controllers/authenticationController.js
src/helpers/authentication.js
src/helpers/constants.js
src/models/IdentityVerification.js
src/routes/authentication.js
tests/integration/authentication.test.js
tests/integration/seed/authenticationSeed.js
tests/unit/helpers/authentication.test.js

- Cas d'usage : lorsque j'ai oublié mon mot de passe je peux directement le récupérer depuis l'application grâce à un code envoyé par email

Com 1813 2

---

tests/unit/helpers/services.test.js
tests/unit/helpers/subPrograms.test.js

Refacto de sinon mongoose sur services.test.js et subPrograms.test.js
Certains test ne vérifiaient pas le mock, d'autres ne validaient pas le lean({ virtuals: true })

Com 1785 - sinon mongoose

---

src/models/Card.js
src/routes/cards.js
src/routes/preHandlers/cards.js
tests/integration/cards.test.js

- Périmetre interface : vendeurs
- Cas d'usage : je peux indiquer à l'aide d'une checkbox si dans les textes à trou les réponses sont interchangeables ou non

COM-1846: add areAnswersCommutative to card model and add prehandler

---

src/models/Card.js
src/routes/cards.js
src/routes/preHandlers/cards.js
tests/integration/cards.test.js

- Périmetre interface : vendeur 
- Cas d'usage :  je peux indiquer à l'aide d'une checkbox si la réponse à une carte de type questionnaire est obligatoire ou non

COM-1848: add isMandatory to card model and add prehandler

---

src/helpers/courses.js
tests/unit/helpers/courses.test.js

- [np] Mon code est testé avec des tests d'intégration
- Cas d'usage : first step of the digitalisation de l'émargement

COM-1851 populate picture for attendanceTable

---

src/data/interAttendanceSheet.html
src/data/intraAttendanceSheet.html

- Périmetre interface : vendeur & client (intra)
- Cas d'usage : sur le template des feuilles d'émargement, j'ai le tampon et la signature 
⚠️ je n'ai pas mis la même taille sur les feuilles intra et inter car je n'avais pas la même place. Dites-moi si cela vous va comme ça ou si vous voulez homogénéiser les 2 (et donc prendre la plus petite taille)

COM-1850: add signature on attendance sheet

---

src/helpers/pdf.js

Fix du bug https://sentry.io/organizations/alenvi/issues/2198870967/?project=1453106&query=is%3Aunresolved

COM-1887 - Fix pupeteer exception error

---

src/controllers/attendanceController.js
src/helpers/attendances.js
src/helpers/translate.js
src/routes/attendances.js
src/routes/preHandlers/attendances.js
tests/integration/attendances.test.js
tests/unit/helpers/attendances.test.js

- Cas d'usage : je peux supprimer un émargement

Com 1851 remove attendance

---

src/helpers/activityHistories.js
src/routes/preHandlers/activityHistories.js
tests/unit/helpers/activityHistories.test.js

Si je re-utilise une activite et que je supprimer une etape ou elle est utilisée:
- je peux deverouiller l'activite
- je n'ai pas d'erreur sur le tableau de bord
- SUR MOBILE: je n'ai pas d'erreur si je finis cette activite
Interrogation: Si une activite est utilisee dans une etape liee a aucun sous-programme, faut-il verouiller l'activite ? 
Vu lors du developpement de ce ticket: Si on supprimer une etape d'un sous programme utilise dans une formation mixte, l'application mobile casse. --> creation d'un ticket de bug

COM-1908 dont take step.subprogram for granted

---

src/helpers/translate.js
src/routes/preHandlers/courseSlot.js
tests/integration/courseSlots.test.js
tests/integration/seed/courseSlotsSeed.js

- ~~[ ] Mon code est testé unitairement~~  -np
fonctionnent~~
- ~~[ ] Je n'ai pas …

COM-1895 - disable slot deletion if attendance exist

---

src/routes/preHandlers/events.js
tests/integration/events.test.js

Com 1920 staging

---

src/routes/preHandlers/courseHistories.js
src/routes/preHandlers/courses.js
tests/integration/courseHistories.test.js
tests/integration/courses.test.js
tests/integration/seed/courseHistoriesSeed.js
tests/integration/seed/coursesSeed.js

fonctionnent~~
- ~~Mes changements impactent une route utilisée par l'autre plateforme (mobile/webapp):
- ~~[ ] Je n'ai pas fait de changement sur le prehandler qui implique …

COM-1944 - Fix bug where user with trainer and client_admin role could‘nt access course histories

---

src/helpers/constants.js
src/models/Payment.js

- ~~[ ] Mon code est testé unitairement~~
- ~~[ ] J'ai bien fait les tests~~ -np
fonctionnent~~
- ~~[ ] Affichage des pages explorer/mes formations/About/CourseProfile~~
- ~~[ ] Inscription a une formation e-learning~~
- ~~[ ] Possibilité de faire une activité~~
- ~~Mes changements impactent une route …

COM-1924: add cash as a payment method

---

src/helpers/programs.js
src/models/Step.js
src/routes/preHandlers/subPrograms.js
tests/integration/seed/subProgramsSeed.js
tests/integration/subPrograms.test.js
tests/unit/helpers/programs.test.js

fonctionnent~~
- ~~[ ] Je n'ai pas fait de changement sur le prehandler qui …

COM-1910 - Prevent step deletion if step is linked to courseSlot

---

src/helpers/courses.js
tests/unit/helpers/courses.test.js

fonctionnent
- ~~J'ai ajoute un champ possible dans la route :~~
- ~~J'ai rendu obligatoire un champs de la route :~~
-~~ J'ai retiré un champ possible dans la route :~~
-~~ J'ai supprimé un retour/un …

COM-1894: populate firstmobileconnection

---

src/data/rights.js
src/routes/preHandlers/users.js
src/routes/users.js
tests/integration/users.test.js

fonctionnent~~
- ~~[ ] Je n'ai pas fait de changement sur le prehandler qui implique le mobile~~
- ~~[ ] Je n'ai pas changé le type d'un paramètre ou enlevé des valeurs possibles~~
- ~~Justification des breaking changes s'il y en a:~~
- ~~[ ] Les …

COM-1950 - trainer can add non registered trainees

---

src/controllers/attendanceController.js
src/routes/attendances.js
src/routes/preHandlers/attendances.js

fonctionnent~~
-~~ [ ] Affichage des pages explorer/mes formations/About/CourseProfile~~
- ~~[ ] Inscription a une formation e-learning~~
- ~~[ ] Possibilité de faire une activité~~
- Mes changements impactent une route utilisée par l'autre plateforme (mobile/webapp):
- Je n'ai pas fait de breaking …

Com 1851 live coding

---

src/controllers/eventController.js
src/helpers/events.js
src/routes/events.js
src/routes/preHandlers/events.js
tests/integration/events.test.js
tests/unit/helpers/events.test.js

COM-1946: send billed and credit note event

---

src/helpers/constants.js
src/models/Activity.js
tests/integration/seed/coursesSeed.js

COM-1951: remove questionnaire

---

tests/unit/helpers/fundings.test.js
tests/unit/helpers/referentHistories.test.js

**fundings**
- checkSubscriptionFunding
- createFunding
- updateFunding
**referentHistories** 
- updateCustomerReferent

COM-1986: sinonmongoose

---

src/controllers/questionnaireController.js
src/data/rights.js
src/helpers/constants.js
src/helpers/questionnaires.js
src/helpers/translate.js
src/models/Questionnaire.js
src/routes/index.js
src/routes/questionnaires.js
tests/integration/questionnaires.test.js
tests/integration/seed/questionnairesSeed.js
tests/unit/helpers/authorization.test.js
tests/unit/helpers/questionnaires.test.js

COM-1974: create new routes for questionnaires

---

.github/pull_request_template.md

- Ce n'est pas une ancienne route utilisée par les app mobiles
- C'est une ancienne route utilisée par une des app mobiles
app mobiles fonctionnent
- Mes changements impactent une route utilisée par les autres plateformes (mobile/webapp):
- J'ai ajouté un champ possible …

proposition to change pr checklist

---

src/repositories/CourseRepository.js

fonctionnent
- J'ai rendu obligatoire un champs …

COM-1981 - populate for salesRepresentative

---

src/controllers/activityController.js
src/controllers/cardController.js
src/controllers/questionnaireController.js
src/helpers/activities.js
src/helpers/cards.js
src/helpers/questionnaires.js
src/models/Questionnaire.js
src/routes/activities.js
src/routes/cards.js
src/routes/preHandlers/activities.js
src/routes/preHandlers/cards.js
src/routes/preHandlers/questionnaires.js
src/routes/questionnaires.js
tests/integration/activities.test.js
tests/integration/cards.test.js
tests/integration/questionnaires.test.js
tests/integration/seed/activitiesSeed.js
tests/integration/seed/cardsSeed.js
tests/integration/seed/questionnairesSeed.js
tests/unit/helpers/activities.test.js
tests/unit/helpers/cards.test.js
tests/unit/helpers/questionnaires.test.js

Com 1988 2

---

src/helpers/questionnaires.js
src/models/Questionnaire.js
src/routes/preHandlers/questionnaires.js
src/routes/questionnaires.js
tests/integration/questionnaires.test.js
tests/integration/seed/cardsSeed.js
tests/integration/seed/questionnairesSeed.js
tests/unit/helpers/questionnaires.test.js

- Justification des breaking changes s'il y en a: changement de title à name dans le modele
- ~~J'ai ajouté un champ possible dans la route :~~
- ~~J'ai rendu …

COM-2027: change title in name

---

src/controllers/questionnaireController.js
src/controllers/questionnaireHistoryController.js
src/helpers/constants.js
src/helpers/questionnaireHistories.js
src/helpers/questionnaires.js
src/helpers/translate.js
src/models/Questionnaire.js
src/models/QuestionnaireHistory.js
src/routes/index.js
src/routes/preHandlers/activityHistories.js
src/routes/preHandlers/questionnaireHistories.js
src/routes/preHandlers/questionnaires.js
src/routes/preHandlers/utils.js
src/routes/questionnaireHistories.js
src/routes/questionnaires.js
tests/integration/questionnaireHistories.test.js
tests/integration/questionnaires.test.js
tests/integration/seed/cardsSeed.js
tests/integration/seed/questionnaireHistoriesSeed.js
tests/integration/seed/questionnairesSeed.js
tests/unit/helpers/questionnaireHistories.test.js
tests/unit/helpers/questionnaires.test.js

MES intermédiaire

---

src/models/Partner.js
src/routes/partnerOrganizations.js
tests/integration/partnerOrganizations.test.js

- ~Ce n'est pas une ancienne route utilisée par les apps mobiles
- ~~J'ai …

COM-2004: firstname is optional

---

src/repositories/PaymentRepository.js

COM-2061 - add cesu refund in tax certificate calculation

---

package-lock.json
package.json
tests/unit/helpers/pay.test.js
tests/unit/helpers/subPrograms.test.js
tests/unit/helpers/subscriptions.test.js

Vérifs avant de clore sinon-mongoose : 
occurences de require(sinon-mongoose) retirées
occurences de mock retirées + tests adaptés à SinonMongoose (subscriptions)
désinstallation de sinon-mongoose
mise à jour de sinon

COM-2051: change last tests and remove sinon-mongoose

---

src/controllers/userController.js
src/helpers/notifications.js
src/helpers/users.js
src/routes/preHandlers/users.js
src/routes/users.js
tests/integration/users.test.js
tests/seed/userSeed.js
tests/unit/helpers/notifications.test.js
tests/unit/helpers/users.test.js

- ~~[ ] Je n'ai pas fait de changement sur le prehandler qui implique le mobile~~
- ~~[ ] Je n'ai pas changé le type d'un paramètre ou enlevé des valeurs possibles~~ …

Com 2078 - MEP Intermédiaire

---

src/controllers/customerController.js
src/helpers/customers.js
src/models/Customer.js
src/routes/customers.js
src/routes/preHandlers/customers.js
tests/integration/customers.test.js
tests/unit/helpers/customers.test.js

COM-2066 - Refacto customer deletion

---

src/controllers/courseController.js
src/helpers/courses.js
src/helpers/email.js
src/helpers/translate.js
tests/integration/courses.test.js
tests/unit/helpers/courses.test.js
tests/unit/helpers/email.test.js

COM-2072: send email in course helper when add trainee

---

src/helpers/constants.js
src/models/BillNumber.js
src/models/Company.js
src/models/Customer.js
src/models/CustomerPartner.js

COM-2067: add status in customer

---

src/helpers/courses.js
src/helpers/users.js
src/models/UserCompany.js
src/repositories/CompanyRepository.js
src/routes/preHandlers/courses.js
tests/integration/seed/authenticationSeed.js
tests/integration/seed/coursesSeed.js
tests/integration/seed/usersSeed.js
tests/integration/users.test.js
tests/unit/helpers/courses.test.js
tests/unit/helpers/users.test.js

-> dans ce cas, j'ai modifié les tests existants car c'est uniquement la logique interne de l'api qui est modifié et non la route / interface avec l'app mobile
(si la route est utilisée en mobile: ne pas la renommer et plutôt créer une nouvelle route utilisée …

COM-2099 - create UserCompany on user creation

---

src/data/interAttendanceSheet.js
src/helpers/courses.js
src/helpers/file.js
src/helpers/pdf.js

test avec téléchargement des images

pdfmake-test2: test with download image

---

src/helpers/users.js
src/models/User.js
src/routes/preHandlers/courses.js
src/routes/preHandlers/sms.js
src/routes/preHandlers/users.js
tests/integration/courses.test.js
tests/integration/users.test.js
tests/unit/helpers/users.test.js

~~### MODIFICATIONS SUR LES ROUTES IMPACTANT UNE AUTRE PLATEFORME~~
- J'ai ajouté un champ possible dans la …

COM-2098 - user utilsHelper

---

src/routes/preHandlers/events.js
tests/integration/seed/eventsSeed.js

- Périmetre roles : client_admin, coach, auxiliary
Pour tester :
- Récupération des évènements d’un auxiliaire sur le planning
- Récupération des stats d’heures travaillées pour un auxiliaire (planning et tableau de bord)
- Vérifier via PostMan (ou en ajoutant un test) pour tester la 403 quand un utilisateur est dans une autre structure

Com 2122 - userCompany

---

src/routes/preHandlers/pay.js
tests/integration/seed/paySeed.js

Périmetre interface : client
Périmetre roles : client_admin, coach, auxiliaire
Pour tester :
Stats des heures des auxiliaires sur le planning ou le tableau de bord
Testée sur postman avec {{API_LINK}}/pay/hours-balance-details (pay > détail du solde):
Avec mon compte
En supprimant company de User avec mon compte
En supprimant company de User avec un compte d'une autre entreprise -> 403

COM-2126 - UserCompany

---

src/routes/preHandlers/attendances.js
tests/integration/attendances.test.js
tests/integration/seed/attendancesSeed.js

Périmetre interface : vendeur
Périmetre roles : vendeur_admin
Pour tester :
Ajouter un émargement à une feuille d'émargement intra
Dans postman (lien de la collection en thread du ticket) :
requête sur slack
Avec mon compte
En supprimant company de User avec mon compte
En supprimant company de User avec un autre trainee dans la requête -> 404

COM-2147: refacto authorizeattendancecreation prehandler

---

src/models/ThirdPartyPayer.js
src/routes/thirdPartyPayers.js
tests/integration/seed/balanceSeed.js
tests/integration/seed/billSlipsSeed.js
tests/integration/seed/billsSeed.js
tests/integration/seed/creditNotesSeed.js
tests/integration/seed/customersSeed.js
tests/integration/seed/eventsSeed.js
tests/integration/seed/exportSeed.js
tests/integration/seed/paymentsSeed.js
tests/integration/seed/statsSeed.js
tests/integration/seed/thirdPartyPayersSeed.js
tests/integration/thirdPartyPayers.test.js
tests/seed/thirdPartyPayerSeed.js

Je peux supprimer l'ID de teletransmission d'un tier payeur

COM-2042 - Allow deletion of teletransmissionId

---

src/data/courseConvocation.html
src/data/pdf/attendanceSheet/interAttendanceSheet.js
src/data/pdf/attendanceSheet/intraAttendanceSheet.js
src/data/pdf/attendanceSheet/utils.js
src/helpers/constants.js
tests/unit/data/interAttendanceSheet.test.js
tests/unit/data/intraAttendanceSheet.test.js
tests/unit/helpers/file.test.js

MAJ de  la charte graphique de Compani : 
MAJ du logo et des couleurs dans : 
- émargement formation intra
- émargement formation inter
- convocations
- attestation de fin de formation -> id du nouveau doc word sur le drive 1PPh13mFoJtAid1TXWPfZzCsPMlFR2wjJ

COM-2192 - update colors

---

src/controllers/customerNoteController.js
src/helpers/customerNotes.js
src/helpers/translate.js
src/routes/customerNotes.js
src/routes/preHandlers/customerNotes.js
tests/integration/customerNotes.test.js
tests/unit/helpers/customerNotes.test.js

-~~ Si mes changements impactent l'application erp :~~
- J'ai …

COM-2176: create route

---

src/data/pdf/courseConvocation.js
tests/unit/data/courseConvocation.test.js

COM-2150 fix columns

---

src/helpers/dataExport.js
tests/integration/seed/authenticationSeed.js
tests/integration/seed/exportSeed.js
tests/seed/userSeed.js
tests/unit/helpers/dataExport.test.js

COM-2180 - update helpers export

---

src/helpers/dataExport.js
tests/integration/exports.test.js
tests/integration/seed/authenticationSeed.js
tests/integration/seed/exportSeed.js
tests/seed/userSeed.js
tests/unit/helpers/dataExport.test.js

COM-2180 - update auxiliaries  export

---

src/helpers/questionnaires.js
src/routes/preHandlers/questionnaires.js
src/routes/questionnaires.js
tests/integration/questionnaires.test.js
tests/unit/helpers/questionnaires.test.js

COM-2213: mutualize followup

---

src/controllers/customerNoteController.js
src/helpers/constants.js
src/helpers/customerNotes.js
src/models/CustomerNote.js
src/models/CustomerNoteHistory.js
tests/unit/helpers/customerNotes.test.js

COM-2206: add history when create

---

tests/integration/exports.test.js
tests/integration/seed/exportSeed.js

Ajout d'un test pour l'horodatage via qr code

COM-2189 - Add export test

---

src/repositories/BillRepository.js
tests/integration/scripts.test.js
tests/integration/seed/scriptsSeed.js

COM-2266: fix company populate

---

tests/integration/activities.test.js
tests/integration/activityHistories.test.js
tests/integration/administrativeDocument.test.js
tests/integration/attendanceSheets.test.js
tests/integration/attendances.test.js
tests/integration/authentication.test.js
tests/integration/balances.test.js
tests/integration/seed/activityHistoriesSeed.js

REFACTO Tests d'intégration : 
- activities
- activityHistories
- administrativeDocument
- attendances
- attendanceSheets
- authentication
- balances

COM-2268: refacto tests

---

src/repositories/BillRepository.js
tests/integration/scripts.test.js
tests/integration/seed/scriptsSeed.js

Com 2266 staging

---

src/models/Customer.js
src/models/schemaDefinitions/subscription.js
src/routes/customers.js
tests/integration/customers.test.js
tests/integration/seed/customersSeed.js
tests/unit/helpers/quotes.test.js

COM-2275: add service to quote on creation

---

src/routes/contracts.js
src/routes/preHandlers/contracts.js

COM-2246 - update contract prehandler

---

src/helpers/subscriptions.js
tests/unit/helpers/subscriptions.test.js

Ajout des tests unitaires pour la méthode populateSubscriptionsServices

COM-2280 test populateSubscriptionsServices

---

tests/integration/courses.test.js
tests/integration/seed/coursesSeed.js

Tests d'integration Course
de `POST /courses` à `GET courses/user`

COM-2270 refacto beginning of course tests

---

tests/integration/seed/usersSeed.js
tests/integration/users.test.js
tests/seed/roleSeed.js

MAJ des tests d'integration de la route DELETE /users/_id

COM-2259 - update delete user tests

---

src/controllers/payController.js
src/helpers/pay.js
src/routes/payments.js
src/routes/preHandlers/payments.js
tests/integration/pay.test.js
tests/integration/payDocuments.test.js
tests/integration/payments.test.js
tests/unit/helpers/payments.test.js

- s’assurer que pour chaque groupe de test, le rôle choisi est le plus pertinent (rôle le plus bas pour un test en 200, rôle le plus haut pour un test en 403)
- s’assurer que le test ne teste pas des choses déjà testées en test unitaire (format du retour d’une route)
- s’assurer que le test n’est pas redondant (ex : un test 404 cette entité n’existe pas + un test 404 cette entité n’appartient pas à la bonne structure, alors que le 2e test serait suffisant)
- s’assurer que le test n’est pas inutile
- pay
- payDocuments
- payments

Com 2272 tests

---

src/routes/preHandlers/courses.js
tests/integration/courses.test.js

Fin du refacto pour les tests d'integration du fichier courses

Com 2270 2

---

tests/end2end/seed/billingSeed.js

fix seed for e2e tests

---

src/helpers/users.js
tests/unit/helpers/users.test.js

- Cas d'usage :  Lors de l'ajout d'un.e stagiaire a une formation, quand je clique sur le select, je vois une liste d'apprenant.es avec photo, nom, email et structure.

COM-2301-select project the db call on 'local.email'

---

src/controllers/Google/driveController.js
src/helpers/drive.js
src/models/Google/Drive.js
src/routes/Google/drive.js
tests/integration/drive.test.js
tests/unit/helpers/drive.test.js

MES - Téléchargement des documents du drive par l'api

Com 2319 staging

---

src/controllers/billsController.js
src/helpers/bills.js
src/helpers/translate.js
src/models/Bill.js
src/routes/bills.js
tests/integration/bills.test.js
tests/integration/seed/billsSeed.js
tests/unit/helpers/bills.test.js

Com 2298 get

---

src/helpers/constants.js
src/helpers/distanceMatrix.js
src/helpers/draftPay.js
tests/unit/helpers/distanceMatrix.test.js
tests/unit/helpers/draftPay.test.js

COM-2295: chose specific transport mode

---

src/routes/preHandlers/courses.js
tests/integration/courses.test.js

Fix d'un bug pour Mélodie :
ETQCoach (important d'être coach), je peux voir la page profil d'une formation qui contient ma company comme règle d'accès.
Exemple : La vie chez Alenvi, que Mélodie ne pouvait pas voir

COM-2350 - Fix access rule bug for Melodie

---

src/data/pdf/attendanceSheet/interAttendanceSheet.js

COM-2337-null fix

---

src/helpers/constants.js
src/helpers/courses.js
tests/unit/helpers/courses.test.js

COM-2362 dont save coursesmshitory if no sms sent

---

src/routes/preHandlers/events.js
tests/integration/events.test.js
tests/integration/seed/eventsSeed.js

Refonte des tests : `events.js`
j'ai ajouté des creditNotes dans les seeds. Anciennement, on les importait depuis `creditNotesSeed.js`

Com 2314 2

---

src/models/User.js
src/routes/preHandlers/users.js
src/routes/users.js
tests/integration/seed/usersSeed.js
tests/integration/users.test.js

test d'integration : users routes POST /users et GET /users/

COM-2309-user POST /users and GET /users/

---

tests/integration/users.test.js

Test d'intégration de De GET `/users/exists` à GET `/users/:id` (inclus)

COM-2309-user-2 next part

---

src/helpers/translate.js

Mise a jour des messages concernant l'archivage d'un beneficiaire. 
J'ai aussi mis a jour deux messages d'erreur selon ce que Romain m'a dit (il avait repondu apres la fusion de la première PR, je les ai donc integrés a celle-ci)
Cas d'usage:
- creer un beneficiaire
- l'archiver --> nouveau texte dans la modale 
- aller sur le planning du beneficiaire
- essayer de creer un evenement --> message d'erreur

COM-2366 - fix messages

---

src/helpers/events.js
src/repositories/EventRepository.js

Ajout des virtuals pour la requête mobile

COM-2470 - Add virtual for mobile

---

src/routes/courses.js
src/routes/preHandlers/courses.js
tests/integration/courses.test.js
tests/integration/seed/coursesSeed.js

COM-2481: block trainee addition and deletion in an archived course

---

src/helpers/courses.js
tests/unit/helpers/courses.test.js

COM-2486: refacto progress

---

package-lock.json
tests/unit/helpers/pdf.test.js

Fix pdfmake test

---

src/helpers/customerAbsences.js
src/helpers/customers.js
tests/integration/customers.test.js
tests/integration/seed/customersSeed.js
tests/unit/helpers/customerAbsences.test.js
tests/unit/helpers/customers.test.js

COM-2493 - Delete and update customer absences after customer stop

---

src/routes/attendanceSheets.js
src/routes/preHandlers/attendanceSheets.js
tests/integration/attendanceSheets.test.js
tests/integration/seed/attendanceSheetsSeed.js

COM-2482 block attendanceSheet creation/delection if archived

---

src/routes/preHandlers/services.js
src/routes/services.js
tests/integration/services.test.js

COM-2476 - add billingItems in service creation

---

.github/pull_request_template.md

- :ballot_box_with_check: :x: J'ai codé les tests unitaires
- :ballot_box_with_check: :x: J'ai codé les tests d'intégration :
- :ballot_box_with_check: :x: C'est une ancienne route utilisée par les apps mobiles
- :ballot_box_with_check: :x: J'ai fait de nouveaux tests sans modifier les anciens
- :ballot_box_with_check: :x: J'ai fait des modifications sur une route utilisée sur plusieurs plateformes
Slite indiquant les points d'attention : https://alenvi.slite.com/app/channels/K4ziWiq5eN/notes/n3bq2hr9Ia
- :ballot_box_with_check: :x: J'ai modifié un modèle utilisé en mobile
Slite indiquant les points d'attention : https://alenvi.slite.com/app/channels/K4ziWiq5eN/notes/rqTfwpUib
- :ballot_box_with_check: :x: J'ai ajouté un modèle spécifique à une structure
- :ballot_box_with_check: :x: J'ai …

COM-2578 checklist edit

---

.github/pull_request_template.md

| <ul><li>[ ] oui </li></ul> | <ul><li>[ ] non</li></ul> | J'ai codé les tests unitaires
| <ul><li>[ ] oui </li></ul> | <ul><li>[ ] non</li></ul> |J'ai codé les tests d'intégration
| <ul><li>[ ] oui </li></ul> | <ul><li>[ ] non</li></ul> |C'est une ancienne route utilisée par les apps mobiles. | <ul><li>[ ] Si oui, J'ai fait de nouveaux tests sans modifier les anciens</li></ul>
---
| <ul><li>[ ] oui </li></ul> | <ul><li>[ ] non</li></ul> | J'ai fait des modifications sur une route utilisée sur plusieurs plateformes | [Slite de détail](https://alenvi.slite.com/app/channels/K4ziWiq5eN/notes/n3bq2hr9Ia)
| <ul><li>[ …

Com 2578 v2

---

.github/pull_request_template.md

</details>
---
</details>
---
</details>
---
- Périmètre interfaces / rôles : N/A
- Cas d'usage : Je vous propose ces sections pliables. Si il y a le mot clé `open` sur la section celle-ci est dépliée par défaut sinon plié. Du coup on pourrait laisser dépliées les sections pertinentes pour la pr. C'est moins concis qu'avec la table mais ca permet de pouvoir apppuyer sur les checkbox. Qu'en pensez-vous ? 
Note: c'est pas pratique d'appuyer sur les checkbox si la section est fermée par defaut mais comme on ne devrait pas fermer par defaut des sections avec des checkbox cochées ca ne devrait pas …

COM-2578 new proposition for checklists

---

.github/pull_request_template.md

</details>
---
</details>
---
</details>
---
- Périmètre interfaces / rôles :

COM-2578 add checkbox to check if we fold section

---

src/helpers/draftBills.js
src/routes/preHandlers/sms.js
tests/integration/seed/smsSeed.js
tests/integration/sms.test.js
tests/unit/helpers/draftbills.test.js

Mes pour fix deux bugs : 
- Probleme d'envoie de sms 
- Probleme de facturation

MES intermediaire 0501

---

src/helpers/attendances.js
tests/unit/helpers/attendances.test.js

| <ul><li>[x] oui </li></ul> | <ul><li>[ ] non</li></ul> | J'ai codé les tests unitaires
| <ul><li>[ ] oui </li></ul> | <ul><li>[x] non</li></ul> | J'ai codé les tests d'intégration
| <ul><li>[ ] oui </li></ul> | <ul><li>[ ] non</li></ul> | C'est une ancienne route utilisée par les apps mobiles. | <ul><li>[ ] Si oui, J'ai fait de nouveaux tests sans modifier les anciens</li></ul> -np
---
| …

COM-2613 remove step in response of unscubscribed route

---

src/helpers/historyExport.js
tests/integration/exports.test.js
tests/unit/helpers/historyExport.test.js

| <ul><li>[x] oui </li></ul> | <ul><li>[ ] non</li></ul> | J'ai codé les tests unitaires
| <ul><li>[x] oui </li></ul> | <ul><li>[ ] non</li></ul> | J'ai codé les tests d'intégration
| <ul><li>[ ] oui </li></ul> | <ul><li>[x] non</li></ul> | C'est une ancienne route utilisée par les apps mobiles. | <ul><li>[ ] Si oui, J'ai fait de nouveaux tests sans modifier les anciens</li></ul>
---
| …

COM-2620: add new fields about presence

---

src/helpers/constants.js
src/helpers/dataExport.js
tests/integration/exports.test.js
tests/seed/authUsersSeed.js
tests/unit/helpers/dataExport.test.js

| <ul><li>[x] oui </li></ul> | <ul><li>[ ] non</li></ul> | J'ai codé les tests unitaires
| <ul><li>[x] oui </li></ul> | <ul><li>[ ] non</li></ul> | J'ai codé les tests d'intégration
| <ul><li>[ ] oui </li></ul> | <ul><li>[x] non</li></ul> | C'est une ancienne route utilisée par les apps mobiles. | <ul><li>[ ] Si oui, J'ai fait de nouveaux tests sans modifier les anciens</li></ul>
---
| …

COM-2608 - add transportMode in auxiliary export

---

src/helpers/constants.js
src/helpers/courses.js
src/helpers/steps.js
tests/unit/helpers/courses.test.js
tests/unit/helpers/steps.test.js

</details>
---
</details>
---
</details>
---
- Périmètre interfaces / rôles : vendeur/client admin_client/admin_vendeur/coach/rof/formateur
- Cas d'usage : la progression s'affiche correctement
- Comment tester ? : voir PR mobile et webapp
⚠️ ajouter les infos nécessaires sur le slite de MES/MEP une fois la MEP du 26/01 passée ⚠️ 

COM-2614: refacto progress in step and course

---

src/helpers/courses.js
src/helpers/dates/companiDurations.js
src/helpers/steps.js
src/helpers/utils.js
tests/unit/helpers/courses.test.js
tests/unit/helpers/dates/companiDuration.test.js
tests/unit/helpers/steps.test.js
tests/unit/helpers/utils.test.js

</details>
---
</details>
---
</details>
---
- Périmètre interfaces / rôles : vendeur/client admin_vendeur/admin_client/coach/rof
- Cas d'usage : je peux visualiser les présences dans les formations suivies sur le profil d'un apprenant
- Comment tester ? : voir webapp + s'assurer qu'on a rien casser : sur les progression de l'app mobile + sur le profil d'une formation mixte/elearning

COM-2615: return presence progress

---

src/helpers/constants.js
src/helpers/dates/companiDates.js
tests/unit/helpers/dates/companiDates.test.js

</details>
---
</details>
---
</details>
---
- Périmètre interfaces / rôles : tous
- Cas d'usage : fonction isBusinessday qui renvoie true si le jour est un jour normal (semaine pas férié) et false sinon
- bien regarder les tests, éventuellement faire des console.log   

COM-2653: isBusinessDay function

---

src/controllers/courseBillingItemController.js
src/controllers/courseFundingOrganisationController.js
src/helpers/courseBillingItems.js
src/helpers/translate.js
src/models/CourseBillingItem.js
src/models/CourseFundingOrganisation.js
src/routes/courseBillingItems.js
src/routes/index.js
src/routes/preHandlers/courseBillingItems.js
tests/integration/courseBillingItems.test.js
tests/integration/helpers/authentication.js
tests/integration/seed/courseBillingItemsSeed.js
tests/unit/helpers/courseBillingItemps.test.js

</details>
---
</details>
---
</details>
---
- Périmètre interfaces / rôles : vendeur admin/rof
- Cas d'usage : je peux ajouter un article de facturation
- ajouter un article de facturation
- essayer de le réajouter => 409 

COM-2665: create and list billing item

---

src/models/schemaDefinitions/identity.js
src/routes/customers.js

</details>
---
</details>
---
</details>
---
Fix d'un bug: ETQ Coach --> lorsque je supprime la date de naissance d'un beneficiaire j'ai une 400 sur la route PUT. 
- Périmètre interfaces / rôles : ETQ Coach
- Cas d'usage : Je peux supprimer la date de naissance d'un beneficaire
- Comment tester ? : Sur une fiche beneficiaire, supprimer la date de naissance.

COM-2660 - can remove birthDate on CustomerProfile

---

src/helpers/historyExport.js
tests/integration/exports.test.js
tests/unit/helpers/historyExport.test.js

</details>
---
</details>
---
</details>
---
- Cas d'usage : export d'une nouvelle colonne "Formation" sous la forme "Structure - Nom du programme - Info complémentaire" dans l'export des créneaux
- exporter les créneaux et vérifier pour quelques formations que le nom correspond bien

COM-2663: add new field in course slot export

---

src/helpers/historyExport.js
tests/integration/exports.test.js
tests/unit/helpers/historyExport.test.js

</details>
---
</details>
---
</details>
---
- Périmètre interfaces / rôles : client coach/admin
- Cas d'usage : changement de nom de la colonne "Heures prises en compte" pour "durée rémunérée"
- Comment tester ? : télécharger l'export et regarder le nom de la colonne

COM-2679: change column name

---

src/helpers/creditNotes.js
src/models/Bill.js
src/models/CreditNote.js
src/models/schemaDefinitions/billing.js
src/routes/creditNotes.js
src/routes/preHandlers/creditNotes.js
src/routes/validations/creditNote.js
tests/integration/creditNotes.test.js
tests/integration/seed/creditNotesSeed.js
tests/unit/helpers/creditNotes.test.js

</details>
---
</details>
---
</details>
---
- Périmètre interfaces / rôles : client
- Cas d'usage : Je peux créer un avoir sur les articles manuels
Créer un avoir avoir lié à des articles de facturations.
La création d'avoir étant complexe, je vous conseille de créer un avoir sur les souscriptions et un avoir lié à des évènements.
Essayer sur un bénéficiaire avec et sans tpp, avec plusieurs souscriptions, essayer avec plusieurs articles  de facturations, changer les prix / quantité des articles.
⚠️ Je n'ai pas encore fait le filtre sur les articles de facturation, on peut …

COM-2657 - Add billingItemList to CreditNotes

---

src/controllers/courseBillController.js
src/helpers/courseBills.js
src/helpers/translate.js
src/models/CourseBill.js
src/routes/courseBills.js
src/routes/index.js
src/routes/preHandlers/courseBills.js
tests/integration/courseBills.test.js
tests/integration/helpers/authentication.js
tests/integration/seed/courseBillsSeed.js
tests/unit/helpers/courseBills.test.js

</details>
---
</details>
---
</details>
---
- Cas d'usage : sur les formations intra : j'ai un onglet facturation dans lequel je peux ajouter une facture (prix + payeur)
- Comment tester ? : créer une facture dans une formation intra (avec financeur (= payeur autre que structure) et sans (= payeur = structure)

COM-2696: create routes

---

src/helpers/courseBills.js
src/models/CourseBill.js
src/routes/courseBills.js
tests/integration/courseBills.test.js
tests/integration/seed/courseBillsSeed.js
tests/integration/seed/exportsSeed.js
tests/unit/helpers/courseBills.test.js
tests/unit/helpers/historyExport.test.js

</details>
---
</details>
---
</details>
---
- Cas d'usage : à la création d'une facture je peux préciser la quantité
- Comment tester ? : supprimer toutes les factures potentiellements déjà existantes (refacto du modèle qui peut causer des incohérences) => créer une facture avec une quantité et afficher les détails

COM-2702: add count field

---

src/controllers/courseBillController.js
src/helpers/courseBills.js
src/models/CourseBill.js
src/routes/courseBills.js
src/routes/preHandlers/courseBills.js
tests/integration/courseBills.test.js
tests/integration/seed/courseBillsSeed.js
tests/unit/helpers/courseBills.test.js

</details>
---
</details>
---
</details>
---
- Cas d'usage : renommage de billingitemList => billingPurchase et conséquences
- créer une facture avec des articles et la valider : tout marche 

COM-2738: refacto to change item in purchase

---

src/models/ThirdPartyPayer.js
src/routes/thirdPartyPayers.js
src/routes/validations/utils.js
tests/integration/thirdPartyPayers.test.js
tests/unit/helpers/utilsValidation.test.js

</details>
---
</details>
---
</details>
---
- Périmètre interfaces / rôles : client - coach / admin
Je peux ajouter un identifiant strucutre et un type d'aide à un tier payeur sur la page config bénéficiaire.
Quand je clique sur l'oeil, ça ouvre une modal pour avoir les details de ces champs
Ajouter un tpp sans tppId, puis ajouter un tppId et les 2 nouveaux champs. Vérifier la validation.

COM-2729 - Add teletransmissionType and companyCode to Tpp

---

src/data/pdf/billing/creditNote.js
src/helpers/creditNotes.js
tests/unit/data/creditNote.test.js

</details>
---
</details>
---
</details>
---
- Périmètre interfaces / rôles : client / admin / coach / aidant
Sur le pdf de l'avoir (bénef / tpp), je vois le motif de l'avoir s'il existe
Pour un benef, faire plusieurs avoir : avec / sans motif, avec / sans tpp. Vérifier que le motif apprait bien où il doit apparaitre sur le pdf + dans le tableau

COM-2734 - Add misc to credit note pdf

---

src/controllers/courseBillController.js
src/helpers/courseBills.js
src/routes/courseBills.js
src/routes/preHandlers/courseBills.js
tests/integration/courseBills.test.js
tests/integration/seed/courseBillsSeed.js
tests/unit/helpers/courseBills.test.js

</details>
---
</details>
---
</details>
---
- Périmètre interfaces / rôles : formation vendeur / rof
- je peux modifier une commande
- je peux toujours modifier la charge de base
- modifier une commande : prix, quantité, description
- modifier une commande avec : description = '' 
- verifier que le titre de la modale est bon
- faire pareil avec la charge de base pour verifier

COM-2723 add route update purchase:

---

src/helpers/utils.js
src/routes/preHandlers/courseBills.js
src/routes/preHandlers/users.js
tests/integration/courseBills.test.js
tests/integration/seed/courseBillsSeed.js
tests/unit/helpers/utils.test.js

</details>
---
</details>
---
</details>
---
- Périmètre interfaces / rôles : formation / vendeur
- j'ai deplacé dans utils, une methode utilisée dans `prehandler/users` pour recuperer toutes les clés d'un objet de profondeur 2
- j'ai crée une fct similaire pour recuperer les couples clé/valeur d'un object de profondeur 2
- j'ai crée des tests unitaire pour ces fct
- j'ai utilisé ma fct pour créer un prehandler qui ne laisse passer que les changement sur 'mainFee.description'
- bien regarder les tests (unitaire et inté)
- sur webapp se mettre sur la branche …

COM-2731 forbid most updates when invoiced

---

src/data/rights.js
src/routes/helpers.js
src/routes/preHandlers/helpers.js
tests/integration/helpers.test.js

</details>
---
</details>
---
</details>
---
- Périmètre interfaces / rôles : auxi / mobile
ETQ Auxi sur l'app mobile, je peux modifier l'aidant référent
Sur la Fiche bénéficiaire (édition d'une intervention > Fiche bénef), je vois et je peux modifier l'aidant référent (il faut en ajouter plusieurs pour un benef sur la webapp)

COM-2725 - Authorize auxiliary to update helper

---

src/helpers/courses.js
src/helpers/programs.js
src/helpers/subPrograms.js
tests/unit/helpers/courses.test.js
tests/unit/helpers/programs.test.js
tests/unit/helpers/subPrograms.test.js

</details>
---
</details>
---
</details>
---
- Périmètre interfaces / rôles : app formation - tous
- Cas d'usage : je peux visualiser la durée estimée du elearning dans une formation e-learning/contenant du elearning
- Comment tester ? : dans l'onglet catalogue et formation vérifier que la durée totale s'affiche pour les formations ayant des étapes elearning avec une durée estimée et que cette durée est la bonne (= somme des durées des étapes elearning)

COM-2722: display course theoretical duration

---

src/helpers/courses.js
tests/unit/helpers/courses.test.js

</details>
- [] Je replie cette section car mes modifications n'ont pas besoin de tests unitaires ou d'intégration
---
</details>
---
</details>
---
- Périmètre interfaces / rôles : formation client et vendeur / rof ou coach
- dans la requete GET /course/{id} : on renvoie la durée total
- voir webapp

COM-2720 retrieve total elearning duration

---

src/routes/preHandlers/courseBills.js
tests/integration/courseBills.test.js
tests/integration/seed/courseBillsSeed.js

</details>
---
</details>
---
</details>
---
- Périmètre interfaces / rôles : formation / rof
- blocage de toutes les modifs sur une facture (exepté pour les descriptions)
- bien regarder les test
- se placer sur la branche dev coté webapp
- essayer de modifier le payeur
- essayer d'ajouter une commande
- essayer de modifier le prix d'une commande
- essayer de modifier la qtt d'une commande

Com 2731 2

---

src/data/pdf/billing/creditNote.js
tests/unit/data/creditNote.test.js

</details>
---
</details>
---
</details>
---
- Périmètre interfaces / rôles : auxi
Fix des retours de Corentin
Regarder que j'ai bien fix les retours de Corentin : 
- on pourrai mettre “visible par les clients” (comme on a decidé que le masculin pluriel est “neutre” dans compani)
- Tu as rajouté un point dans le pdf, du coup ca en fait deux quand l’utilisateur.ice en a deja mis un dans la modale. Je pense qu’il ne faut pas en ajouter.

COM-2734 - Fix Corentin's reviews

---

src/controllers/vendorCompanyController.js
src/helpers/translate.js
src/helpers/vendorCompanies.js
src/routes/establishments.js
src/routes/validations/utils.js
src/routes/vendorCompanies.js
tests/integration/vendorCompanies.test.js
tests/unit/helpers/vendorCompanies.test.js

</details>
---
</details>
---
</details>
---
- Cas d'usage : je peux mettre à jour les infos de factu de Compani
- Comment tester ? : changer nom, adresse et siret de company, tester les validations

COM-2760: can update vendor company

---

src/controllers/courseBillController.js
src/helpers/constants.js
src/helpers/courseBills.js
src/routes/courseBills.js
src/routes/preHandlers/courseBills.js
tests/integration/courseBills.test.js
tests/unit/helpers/courseBills.test.js

</details>
---
</details>
---
</details>
---
- Cas d'usage : je peux visualiser et télécharger les factures depuis la fiche d'une structure
- facturer une formation à une structure : s'assurer qu'elle s'affiche bien sur le profil de la formation (qu'on a pas cassé la route préexistante
- se rendre sur le profil d'une structure et s'assurer qu'on a bien la facture (si elle est validée) et qu'on peut la télécharger 

COM-2754: return bills for companies

---

src/controllers/courseFundingOrganisationController.js
src/helpers/courseFundingOrganisations.js
src/models/CourseFundingOrganisation.js
src/routes/preHandlers/courseFundingOrganisation.js
tests/integration/courseFundingOrganisations.test.js
tests/integration/seed/courseFundingOrganisationsSeed.js
tests/unit/helpers/courseFundingOrganisations.test.js

</details>
---
</details>
---
</details>
---
- Cas d'usage : je ne peux pas supprimer un financeur s'il est utilisé pour une facture (validée ou non)
- créer un financeur
- l'assigner à une facture => je ne peux plus le supprimer
- le désassigner de la facture => je peux le supprimer
- valider la facture avec le financeur => je ne peux plus le supprimer
- faire ces tests pour le disable en front et pour le blocage back (retirer le disable pour tester cette deuxième façon) 
_Si tu as lu cette description, pense a réagir avec …

COM-2751: block funder deletion if used

---

src/models/Company.js
src/routes/companies.js
tests/integration/companies.test.js

</details>
---
</details>
---
</details>
---
- Cas d'usage : quand je crée une structure, je n'ai pas besoin de préciser si c'est une entreprise ou une association
- créer une structure => je n'ai pas à préciser son type
- se rendre sur le profil de la structure => elle n'a pas de type
- lui ajouter un type => le changement est pris en compte
- je peux rechanger son type

COM-2756: move type from post route payload to put route payload

---

src/data/pdf/courseBilling/courseBill.js
tests/unit/data/courseBill.test.js

</details>
---
</details>
---
</details>
---
- Périmètre interfaces / rôles : vendeur / rof
- Cas d'usage : Correction d'une coquille dans la facture, on veut "Facturer à"
- Comment tester ? : verifier

COM-2753-2 typo

---

src/data/pdf/attendanceSheet/utils.js
tests/unit/data/interAttendanceSheet.test.js
tests/unit/data/intraAttendanceSheet.test.js

</details>
---
</details>
---
</details>
---
- Périmètre interfaces / rôles : vendeur/client rof/admin/coach
- Cas d'usage : ajout de margin sur le cadre du header des feuilles d'émargement
- Comment tester ? : télécharger feuille d'émargement inter et intra pour des formation avec un long nom et un nom court => le cadre du header s'affiche correctement

COM-2761: add margin

---

src/helpers/constants.js
src/helpers/contracts.js
src/helpers/delivery.js
src/helpers/eventsValidation.js
src/helpers/historyExport.js
src/models/Event.js
src/models/EventHistory.js
src/routes/preHandlers/eventHistories.js
tests/unit/helpers/contracts.test.js
tests/unit/helpers/delivery.test.js
tests/unit/helpers/eventsValidation.test.js
tests/unit/helpers/historyExport.test.js

MES pour supprimer la dépendances circulaire entre `models/Event` et `models/EventHistory`

COM-2783 - remove circular dependancy

---

src/controllers/attendanceController.js
src/controllers/balanceController.js
src/controllers/billsController.js
src/controllers/companyController.js
src/controllers/courseController.js
src/controllers/customerController.js
src/controllers/eventController.js
src/controllers/exportController.js
src/controllers/payController.js
src/controllers/statController.js
src/controllers/teletransmissionController.js

</details>
---
</details>
---
</details>
---
- Périmètre interfaces / rôles :
- Cas d'usage : Ajouter des éléments dans les logs pour indiquer quand on rentre dans le controlleur et savoir quelles routes sont en cours d'exécution quand l'application plante
Verifier qu'en appelant les routes suivantes, il y a bien les elements qui apparaissent dans les logs
Sur outil : 
facturation : liste et création en masse
paie : liste
statistiques pour le tableau de bord
planning
export
1ère intervention des bénéficiaire
balance client : liste et individuelle
Sur formation : …

COM-2785 - add log before controller execution

---

src/controllers/coursePaymentController.js
src/helpers/coursePayments.js
src/helpers/translate.js
src/routes/coursePayments.js
src/routes/preHandlers/coursePayments.js
tests/integration/coursePayments.test.js
tests/integration/seed/coursePaymentsSeed.js
tests/unit/helpers/coursePayments.test.js

</details>
---
</details>
---
</details>
---
- Cas d'usage : je peux éditer un règlement sur une facture
- Comment tester ? : éditer un règlement existant sur une facture

COM-2771: edit course payment

---

src/helpers/delivery.js
tests/unit/helpers/delivery.test.js

</details>
---
</details>
---
</details>
---
- Périmètre interfaces / rôles : Admin
- Cas d'usage : -> tout est détaillé ici : https://compani.atlassian.net/browse/COM-2784
- Comment tester ? : idem :) 

COM-2784 - take timestamp into account when event is not billed

---

src/controllers/billsController.js
src/controllers/courseBillController.js
src/controllers/courseController.js
src/controllers/creditNoteController.js
src/controllers/customerController.js
src/controllers/eventController.js
src/controllers/taxCertificateController.js

</details>
---
</details>
---
</details>
---
- Périmètre interfaces / rôles : Tous
- Cas d'usage : Ajout de logs sur certaines routes
PDF de facture d'interventions
PDF de facture de formation
PDF des feuilles d'émargement vierge
PDF / Zip de Word des attestations de fin de formation
PDF de convocation
PDF d'avoir d'interventions
PDF de QRCode
Stats des heures travaillées
Stats des temps de transport payés par équipe
Stats des heures a affecter par équipe
PDF d'attestation fiscale

COM-2785 - add log on route

---

package-lock.json
package.json

<details open><summary> TESTS  :computer: </summary> -np
</details>
---
<details open><summary> POINTS D'ATTENTION POUR CETTE PR  :warning: </summary> -np
</details>
---
</details>
---
- Cas d'usage : Signatures de contrat et de mandat réparées
- creer un contrat auxiliaire
- le signer cote auxiliaire et cote coach --> verifier qu'il est bien signé en se connectant a eversign dev
- signer un mandat de prélèvement cote aidant --> verifier la signature sur eversign
⚠️ La MAJ de ce paquet engendre la generation de fichiers corrompus. Un ticket a été cree pour creuser le sujet: https://compani.productboard.com/feature-board/1769559-vue-hierarchique/features/12920874/detail
_Si tu as lu cette …

COM-2800 - downgrade docxtemplater to fix bug

---

src/helpers/draftPay.js
src/repositories/EventRepository.js
tests/unit/helpers/draftPay.test.js

</details>
---
</details>
---
</details>
---
- Périmètre interfaces / rôles : Admin client
- Cas d'usage : reduire le nombre de données stockés en memoire
pour avoir une petite idee de la reduction de la taille j'ai utilisé `JSON.stringify(....).length` sur la branche de dev et sur ma branche pour comparer la taille des objets ... ce n'est pas tout a fait exact bien sur mais je pense que ca donne une bonne idée de l'ordre de grandeur
Pour s'assurer qu'il n'y a pas de regressions entre les 2 tableaux :
_ se mettre sur la branche de dev
_ charger la page
_ ouvrir un …

Com 2810 2

---

src/controllers/courseCreditNoteController.js
src/data/pdf/courseBilling/courseBill.js
src/data/pdf/courseBilling/courseCreditNote.js
src/data/pdf/courseBilling/utils.js
src/helpers/constants.js
src/helpers/courseBills.js
src/helpers/courseCreditNotes.js
src/routes/courseCreditNotes.js
src/routes/preHandlers/courseCreditNotes.js
tests/integration/courseBills.test.js
tests/integration/courseCreditNotes.test.js
tests/integration/seed/courseCreditNotesSeed.js
tests/unit/data/courseBill.test.js
tests/unit/data/courseCreditNote.test.js
tests/unit/helpers/courseBills.test.js
tests/unit/helpers/courseCreditNotes.test.js

</details>
---
</details>
---
</details>
---
- Cas d'usage : je peux télécharger un avoir sur le profil d'une formation 
- Comment tester ? : télécharger un avoir

COM-2774: credit note pdf

---

src/helpers/customers.js
src/models/Customer.js
tests/integration/customers.test.js
tests/integration/seed/customersSeed.js
tests/unit/helpers/customers.test.js

</details>
---
</details>
---
</details>
---
- Périmètre interfaces / rôles : coach
- Cas d'usage : Modification des countDocuments de `countSubscriptionUsage` pour n'avoir que 0 ou 1 suivant si la subscription est lié à un évènement ou non. 
- Sur la page profile d'un bénéficiaire, je ne peux pas supprimer une souscription si il a au moins un évènement ou une repetition. --> Seul endroit ou les champs sont effectivement utilisés
Autres endroits à vérifier car il y a l'utilisation de `Customer.findOne`
- Je peux supprimer un bénéficiaire
- Je peux générer un qrcode pour …

COM-2823 add limit to countDocument in countSubscriptionsUsage

---

src/helpers/draftBills.js
tests/unit/helpers/draftbills.test.js

</details>
---
</details>
---
</details>
---
- Périmètre interfaces / rôles : Admin client
- Cas d'usage : Je peux facturer le client 5cdd33eb8d5cce0014a8a215 sur le mois de mai
- Comment tester ? : Aller sur la page a facturer pour le mois de mai et le tableau s'affiche

Com 2805 fix

---

src/helpers/courses.js
src/helpers/translate.js
src/routes/preHandlers/courses.js
tests/integration/courses.test.js
tests/integration/seed/coursesSeed.js

</details>
---
</details>
---
</details>
---
- Périmètre interfaces / rôles : ROF 
- Cas d'usage : Je ne peux pas supprimer une formation si elle est facturée
Créer une formation, la facturer, la supprimer -> erreur
Créer une formation, créer une facture mais ne pas la valider, la supprimer => c'est ok et la facture est supprimée

COM-2835 - block course deletion if billed

---

tests/unit/helpers/courses.test.js

</details>
---
</details>
---
</details>
---
- Périmètre interfaces / rôles :
- Comment tester ? : il faut bien vérifier que les tests passent

COM-2835 - fix tests

---

tests/unit/helpers/delivery.test.js

mini fix pour corriger une coquille

fix-typo-shell: minutes on 2 digits

---

src/helpers/bills.js
src/helpers/fundings.js
src/helpers/utils.js
tests/unit/helpers/bills.test.js

</details>
---
</details>
---
</details>
---
- Périmètre interfaces / rôles : Admin / coach / aidant
- Cas d'usage : Quand je telecharge une facture pour un tiers payeur j'ai le bon prix unitaire TTC et donc le bon total sur la ligne de la souscription
Créer un bénéficiaire avec un financement
Ajouter des interventions pour ce bénéficiaire et ce plan de financement
Facturer le bénéficiaire et le tiers payeur associé
Télécharger la facture
Modifier le prix du financement 
Télécharger la facture -> elle est identique a la première
Modifier le taux de participation du …

COM-2836 - use matching funding version in bill

---

src/helpers/courseHistories.js
src/helpers/courseSlots.js
src/models/CourseHistory.js
src/routes/courseSlots.js
src/routes/courses.js
src/routes/preHandlers/courseSlot.js
src/routes/preHandlers/courses.js
tests/integration/courseSlots.test.js
tests/integration/seed/courseSlotsSeed.js
tests/unit/helpers/courseHistories.test.js
tests/unit/helpers/courseSlots.test.js
tests/unit/helpers/courses.test.js
tests/unit/helpers/delivery.test.js

</details>
---
</details>
---
</details>
---
- Périmètre interfaces / rôles : vendeur/client rof/admin_vendeur/admin_client/trainer/coach
- Cas d'usage : seul les admin vendeur/rof peuvent créer et supprimer des créneaux + boyscout création d'historique : meetinglink pris en compte + pas d'historique à la suppression de créneaux à planifier
- côté vendeur (rof/admin) : 
- créer un créneau dans une formation => je ne peux pas le supprimer si c'est le seul de l'étape
- je supprime un créneau à planifier => je n'ai pas d'historique créé
- je créé/supprime un créneau d'une étape …

COM-2816: change rights + boyscout meetlink + block history for slots to plan

---

src/helpers/draftBills.js
tests/unit/helpers/draftbills.test.js

</details>
---
</details>
---
</details>
---
- Périmètre interfaces / rôles : Admin client
facturation d'une intervention majorée de moins d'une minute
Ajouter une majoration personnalisé sur l’heure a laquelle tu fais ton test (si tu teste ce ticket a 16h14 → tu peux mettre une majoration de 16h a 17h)
Choisis un service qui a ce plan de majoration
Créer un bénéficiaire et ajoute lui une souscription sur ce service
Créer lui 2 interventions : 
une dans la majoration : tu horodates le début et tu la fais terminer dans la minute qui suit → il faut que sa durée …

COM-2838 - case if event duration is 0

---

src/helpers/bills.js
src/helpers/utils.js
tests/unit/helpers/bills.test.js
tests/unit/helpers/utils.test.js

</details>
---
</details>
---
</details>
---
- Périmètre interfaces / rôles : Admin / Coach / aidant
- Cas d'usage : Quand je telecharge une facture dans l'onglet facturation, la quantité est formatée avec une , et non un . si en decimal
Tester sur une facture manuelle tout juste créée, une facture manuelle deja en base et une facture automatique en base

COM-2832 - format quantity in pdf

---

src/controllers/courseSlotController.js
src/helpers/courseSlots.js
src/routes/courseSlots.js
src/routes/preHandlers/courseSlot.js
tests/integration/courseSlots.test.js
tests/integration/seed/courseSlotsSeed.js
tests/unit/helpers/courseSlots.test.js

</details>
---
</details>
---
</details>
---
- Périmètre interfaces / rôles : client/vendeur coach/rof/formateur
- Cas d'usage : je ne peux créer que des créneaux à planifier en tant que rof
- rof : créer un créneau à planifier et le modifier
- coach/formateur : modifier un créneau à planifier + je ne peux pas créer de créneau 

COM-2817: refacto slot creation

---

src/data/pdf/attendanceSheet/intraAttendanceSheet.js
tests/unit/data/intraAttendanceSheet.test.js

</details>
---
</details>
---
</details>
---
- Périmètre interfaces / rôles : vendeur rof
- Cas d'usage : les feuilles d'emargement intra sont bien sur une seule page meme si le titre de la formation est sur 2 lignes
- Comment tester ? : telecharger des feuilles d'emargement intra et verifier qu'elles s'affichent bien (ajouter des infos dans misc pour pouvoir avoir des titres sur plusieurs lignes)

COM-2850 change table height

---

server.js
src/helpers/constants.js

</details>
---
</details>
---
</details>
---
- Périmètre interfaces / rôles : Tous
Ajouter des logs a l'entrée de toutes les routes pour avoir des infos sur ce qui est en cours quand il y a un évènement particulier
Ajout de log en local uniquement sur l'utilisation de la mémoire
Faire des appels a l'api et vérifier que les logs s'affichent bien

COM-2840 - add log on route

---

src/helpers/courses.js
src/routes/courseSlots.js
src/routes/preHandlers/courseSlot.js
tests/integration/courseSlots.test.js
tests/unit/helpers/courses.test.js

</details>
---
</details>
---
</details>
---
- Périmètre interfaces / rôles : client/vendeur coach/rof/trainer
- Cas d'usage : les créneaux sont rangés par étape, en tant que rof je peux les créer, en tant que coach/formateur je peux les modifier : 
- bloc blanc => étape elearning / pas d'interaction
- bloc orange => étape avec des créneaux à planifier
- bloc bleu => étape sans créneaux à planifier
- si je rajoute des créneaux à planifier dans une étape bleu => orange
- si je rempli des créneaux à planifier dans une étape orange => bleu
- Comment tester ? :  
- en tant que rof : 
- je peux créer …

COM-2837: step is required

---

src/helpers/translate.js
src/helpers/users.js
src/routes/preHandlers/users.js
tests/integration/seed/usersSeed.js
tests/integration/users.test.js
tests/unit/helpers/users.test.js

</details>
---
</details>
---
</details>
---
- Périmètre interfaces / rôles : mobile-formation - norolenocompany
- Cas d'usage : je peux supprimer mon compte si je n'ai pas de structure et que je n'ai pas fait d'activité
- se connecter avec en compte sans structure
- s'inscrire à une formation elearning => je peux supprimer mon compte
- s'inscrire à une formation elearning et faire une activité => je ne peux pas supprimer mon compte 

COM-2819: delete user if no activity histories

---

src/helpers/sectorHistories.js
tests/unit/helpers/sectorHistories.test.js

</details>
---
</details>
---
</details>
---
- Périmètre interfaces / rôles : Admin / Coach
- Cas d'usage : Changement d'équipe pour une auxiliaire
- Comment tester ? : Tous les cas de tests sont listés dans le ticket

COM-2841 - update sector history after ending contract

---

package.json

</details>
---
</details>
---
</details>
---
- Périmètre interfaces / rôles : Tous
- Cas d'usage : Lancement de l'api
Ajouter dans le fichier `.env` la variable `MAX_OLD_SPACE_SIZE=920`
Lancer le serveur du back avec `nodemon --exec "heroku local -p 3000"`
Tester quelques routes donc celle de la generation des feuilles d'émargement
En dev et en staging elle sera fixée a 460 et en prod 920

COM-2854 - update command to launch server

---

src/helpers/courseBills.js
tests/unit/helpers/courseBills.test.js

</details>
---
</details>
---
</details>
---
- Cas d'usage : sur l'onglet facturation sur le profil d'une structure les formations sont classées par payeur
- Comment tester ?
- facturer une formation d'une structure A à la structure A (1)
- facturer une formation d'une structure A à la structure B (2)
- facturer un formation d'une structure B à la structure A (3)
- sur l'onglet factu de la structure A on a 2 tableaux : 
- les factures payées par A (1 et 3)
- les facutres payées par B (2)
_Si tu as lu cette description, pense a réagir avec un …

COM-2813: populate payer

---

src/controllers/courseSlotController.js
src/helpers/courseSlots.js
src/routes/courseSlots.js
tests/integration/courseSlots.test.js
tests/unit/helpers/courseHistories.test.js
tests/unit/helpers/courseSlots.test.js

</details>
---
</details>
---
</details>
---
- Périmètre interfaces / rôles : client/vendeur coach/admin.rof
- Cas d'usage : je peux supprimer la date d'un créneau
- créer un créneau à planifier
- ouvrir la modale d'édition => pas de bouton de suppression
- lui ajouter une date et une adresse
- rouvrir la modale d'édition => bouton de suppression
- supprimer la date : 
- le créneau repasse en créneau à planifier  + l'adresse est supprimée
- en base il y a un historique de suppression avec les heures du créneau supprimées et l'adresse supprimée
_Si tu as lu cette description, …

COM-2848: remove dates on slot

---

src/data/pdf/courseBilling/utils.js
src/helpers/courseBills.js
src/helpers/courseCreditNotes.js
src/models/CourseFundingOrganisation.js
src/routes/courseFundingOrganisations.js
tests/integration/courseFundingOrganisations.test.js
tests/integration/seed/courseBillsSeed.js
tests/integration/seed/courseFundingOrganisationsSeed.js
tests/integration/seed/exportsSeed.js
tests/unit/data/courseBill.test.js
tests/unit/data/courseCreditNote.test.js
tests/unit/helpers/courseBills.test.js
tests/unit/helpers/courseCreditNotes.test.js

</details>
---
</details>
---
</details>
---
- Périmètre interfaces / rôles : vendeur/ rof/admin
- Cas d'usage : l'adresse des financeurs est désormais une chaîne de caractères
- s'assurer qu'on a déjà un financeur A sur la branche dev et qu'il est utilisé dans une facture validée + avoir
- faire tourner le script et se mettre sur cette branche
-  dans l'onglet facturation le financeur A s'affiche correctement
- créer un financeur B et l'utiliser comme payeur d'une facture qu'on valide + avoir
- je peux télécharger une facture payée par une structure/ payée par le financeur …

COM-2844: refacto address

---

src/helpers/dates/companiDates.js
src/helpers/delivery.js
src/helpers/fundings.js
tests/unit/helpers/dates/companiDates.test.js

</details>
---
</details>
---
</details>
---
- Périmètre interfaces / rôles : client coach/admin
- Cas d'usage : migration luxon des fichiers delivery et funding
- je peux créer / éditer un financeur pour un bénéficiaire
- je peux exporter le fichier de télétransmission 

COM-2798: replace moment with companidate

---

src/data/pdf/courseBilling/courseBill.js
tests/unit/data/courseBill.test.js

</details>
---
</details>
---
</details>
---
- Périmètre interfaces / rôles : vendeur/client rof/admin
- Cas d'usage : suppression d'une phrase inutile dans le footer de la facturation
- télécharger une facture => je n'ai plus la phrase "Merci de lire attentivement nos Conditions Générales de Prestations et le(s) programme(s) de formation en pièce-jointe." dessus 

COM-2846: remove useless sentence

---

src/helpers/users.js
src/models/User.js
src/routes/preHandlers/users.js
tests/integration/users.test.js
tests/unit/helpers/users.test.js

</details>
---
</details>
---
</details>
---
- Périmètre interfaces / rôles : mobile-formation / sans structure
- Cas d'usage : je peux supprimer mon compte même en ayant fait des activités elearning
- créer un compte
- le supprimer directement => il est supprimé de la BDD
- créer un compte et faire des activités
- le supprimer => il est anonymisé en BDD
- refaire les deux cas précédents mais killer l'app juste après avoir valider la suppression (ne pas cliquer sur OK sur la modale de confirmation) => quand je reviens sur l'app je suis sur la page d'authentication …

COM-2820: anonymised user

---

src/helpers/courses.js
tests/unit/helpers/courses.test.js

</details>
---
</details>
---
</details>
---
- Périmètre interfaces / rôles : client/vendeur rof/admin/coach
- Cas d'usage : refacto design du référent Compani sur une formation
- sur une formation j'ai le nouveau design du référent compani
- je peux l'éditer soit via son nom soit via son mail (dans la modale)
- je ne peux l'éditer que depuis le côté vendeur 

COM-2847: select phone, picture and email

---

src/helpers/translate.js
src/helpers/users.js
src/models/User.js
src/routes/preHandlers/users.js
tests/integration/seed/usersSeed.js
tests/integration/users.test.js
tests/unit/helpers/users.test.js

</details>
---
</details>
- [] Je replie cette section car je n'ai pas fait de modifications entrainant un point d'attention
---
</details>
---
- Périmètre interfaces / rôles : mobile formation / sans role-sans structure
- Cas d'usage : je peux supprimer mon compte même si j'ai fait des activités
- créer un compte
- faire une activité
- supprimer son compte
- en base l'utilisateur est supprimé de la formation, son compte est supprimé ainsi que ses historiques d'activités 

COM-2891: delete account if has histories

---

src/helpers/courses.js
tests/unit/helpers/courses.test.js

</details>
---
</details>
---
</details>
---
- Périmètre interfaces / rôles : vendeur/client rof/admin/coach
- Cas d'usage : refacto de la section intervenant sur le profil d'une formation
- ETQ ROF : je peux ajouter un formateur à une formation et je peux l'éditer si la formation n'est pas archivée
- ETQ  coach : je peux visualiser le formateur sur le profil de la formation

COM-2815: populate trainer infos

---

src/helpers/courses.js
src/models/CourseSlot.js
src/routes/preHandlers/courses.js
tests/integration/courses.test.js
tests/integration/seed/coursesSeed.js
tests/unit/helpers/courses.test.js

</details>
---
</details>
---
</details>
---
- Cas d'usage : je peux supprimer une formation si elle n'a que des créneaux à planifier
- essayer de supprimer une formation sans stagiaires mais avec des créneaux planifier => 403
- déprogrammer les créneaux => je peux supprimer la formation 

COM-2900: can delete course with slots to plan

---

src/helpers/courses.js
tests/integration/courses.test.js
tests/integration/helpers/initializeDB.js
tests/unit/helpers/courses.test.js

</details>
---
</details>
---
</details>
---
- Cas d'usage : à la création d'une formation mixte, des créneaux sont créés dans chaque étape présentielle/distancielle
- créer une formation présentielle => des créneaux sont créés dans chaque étape présentielle
- créer une formation distancielle => des créneaux sont créés dans chaque étape distancielle 

COM-2839: create slots to plan on course creation

---

src/routes/preHandlers/courses.js
tests/integration/courses.test.js

</details>
---
</details>
---
</details>
---
- Périmètre interfaces / rôles : vendeur/client rof/coach/admin
- Cas d'usage : je peux envoyer un sms même si pas de contact ou de formateur
- envoyer un sms pour une formation sans formateur et sans contact 

COM-2876: remove some conditions

---

src/controllers/repetitionController.js
src/helpers/eventHistories.js
src/helpers/repetitions.js
src/routes/preHandlers/repetitions.js
src/routes/repetitions.js
tests/integration/repetitions.test.js
tests/integration/seed/repetitionsSeed.js
tests/unit/helpers/repetitions.test.js

</details>
---
</details>
---
</details>
---
- Périmètre interfaces / rôles : ETQ Client admin / coach / référent planning
- Cas d'usage : Je peux supprimer une repetition et les evenements reliés a partir d'une certaine date.
- supprimer une repetitoin depuis la page `Gérer les repetitions`
- verifier en bdd que la repetition a ete supprimee
-  verifier que les evenements programmés apres la date saisie sont supprimés

COM-2899 - create route delete /repetitions

---

src/helpers/repetitions.js
tests/unit/helpers/repetitions.test.js

</details>
---
</details>
---
</details>
---
- Périmètre interfaces / rôles : ETQ Coach / Admin Client / Planning referent 
- Cas d'usage : Je peux supprimer une repetition.
- supprimer des repetitions qui sont reliées a des evenements 
- vérifier en bdd que les evenemnts postérieurs a la Date entrée ont ete supprimés
- verifier que la repetition est supprimée
- supprimer des repetitions non rattachées a des evenments
- verifier que la repetition est bien supprimee 

COM-2899 - can delete a repetition without linked events

---

src/data/pdf/courseBilling/utils.js
tests/unit/data/courseBill.test.js
tests/unit/data/courseCreditNote.test.js

</details>
---
</details>
---
</details>
---
- Périmètre interfaces / rôles : client/vendeur ROF/admin/coach
- Cas d'usage : j'ai la mention du HT et du TTC sur ma facture et mon avoir
- Comment tester ? : télécharger une facture et un avoir et s'assurer que j'ai mon HT et mon TTC (les deux sont égaux)

COM-2914: add exclTaxes on pdf for bill and credit note

---

src/data/pdf/courseBilling/utils.js
tests/unit/data/courseBill.test.js
tests/unit/data/courseCreditNote.test.js

</details>
---
</details>
---
</details>
---
- Périmètre interfaces / rôles : client/vendeur ROF/admin/coach
- Cas d'usage : j'ai la mention du HT et du TTC sur ma facture et mon avoir
- Comment tester ? : télécharger une facture et un avoir et s'assurer que j'ai mon HT et mon TTC (les deux sont égaux)

COM-2914: respect figma

---

src/helpers/courses.js
tests/unit/helpers/courses.test.js

</details>
---
</details>
---
</details>
---
- Périmètre interfaces / rôles : vendeur rof
- Cas d'usage : je peux modifier le contact + boyscout retour de Romain sur les 2 tickets précédents : retirer la mention contact pour la formation + ajouter numéro manquant pour les interlocuteurs
- définir un des interlocuteurs comme contact
- changer le contact en changeant l'interlocuteur et sans changer l'interlocuteur 

COM-2918: update contact

---

src/data/pdf/completionCertificate.js
tests/unit/data/completionCertificate.test.js

</details>
---
</details>
---
</details>
---
- Périmètre interfaces / rôles : rof/apprenant
- Cas d'usage : lorsque je telecharge l'attestation de fin de formation, le footer est plus compact
- Comment tester ? : vérifier les docs sur la webapp et l'app formation (le design sur la webapp a ete valide par Romain)

COM-2915 less space on completion certificate

---

tests/integration/seed/repetitionsSeed.js

</details>
---
</details>
---
</details>
---
- Périmètre interfaces / rôles : np
- Cas d'usage : fix test de suppression de repetitions
- Comment tester ? : verifier que tous les tests passent 

BN fix repetition tests

---

src/helpers/contracts.js
tests/integration/contracts.test.js
tests/unit/helpers/contracts.test.js

</details>
---
</details>
---
</details>
---
- Périmètre interfaces / rôles : coach/admin
- Cas d'usage : Je peux supprimer un avenant d'un auxiliaire
- Comment tester ? : Supprimer un avenant d'un auxiliaire 

COM-2966 fix contract versino deletion

---

src/helpers/contracts.js
tests/integration/contracts.test.js
tests/unit/helpers/contracts.test.js

Fix du bug de suppression des avenants

MES intermediaire 08/08

---

src/routes/Google/drive.js
src/routes/preHandlers/taxCertificates.js
tests/integration/authentication.test.js
tests/integration/companies.test.js
tests/integration/companyLinkRequests.test.js
tests/integration/contracts.test.js
tests/integration/courseCreditNotes.test.js
tests/integration/coursePayments.test.js
tests/integration/courseSlots.test.js
tests/integration/drive.test.js
tests/integration/email.test.js
tests/integration/establishments.test.js
tests/integration/events.test.js
tests/integration/helpers.test.js
tests/integration/internalHours.test.js
tests/integration/payDocuments.test.js
tests/integration/roles.test.js
tests/integration/scripts.test.js
tests/integration/sectors.test.js
tests/integration/services.test.js
tests/integration/sms.test.js
tests/integration/stats.test.js
tests/integration/surcharges.test.js
tests/integration/taxCertificates.test.js
tests/integration/thirdPartyPayers.test.js
tests/integration/users.test.js

</details>
---
</details>
---
</details>
---
- Périmètre interfaces / rôles : coach
- refacto des tests d'inté sur les routes : 
- drive
- taxCertificat
- thirdPartyPayers
- sur le prehandler de `TaxCertificat` : 
- modification du code de status HTTP lors d'un appel sur un objet d'une autre structure (anciennement 403 => 404). Ce changement n'a pas d'incidence sur le front
- dans le dernier commit, j'ai complété tous les `describe` de tous les fichiers de tests inté qui n'avaient pas un titre complet (ex : `COMPANIES ROUTES - POST /companies...`)
- …

COM-2311 refacto tests

---

src/models/Card.js
tests/integration/activities.test.js
tests/integration/thirdPartyPayers.test.js

</details>
---
</details>
---
</details>
---
- Périmètre interfaces / rôles : sur compani-formation / etq rof 
- fix : sur l'editeur d'activité, je peux créer une page programme. Je peux ensuite renseigner la question, lq checkbox et les deux labels.
- je me suis posé la question d'ajouter un test d'integration pour verifier à l'avenir que les cartes nouvellement créées ont le bon format... Mais par souci d'uniformité, il faudrait alors créer un test par carte, ce qui sort du perimetre. Qu'en penses-tu ?
- sur la webapp, profile d'un programme > onglet …

COM-2968 fix survey card initialisation

---

src/helpers/constants.js
tests/unit/data/courseConvocation.test.js
tests/unit/data/interAttendanceSheet.test.js
tests/unit/data/intraAttendanceSheet.test.js

</details>
---
</details>
---
</details>
---
- Périmètre interfaces / rôles : tous 
- Cas d'usage : refacto couleurs
vu avec Romain : 
- on implémente orange plutôt que new-orange 
- on conserve peach100 et 200 même s'ils sont pas dans figma
- orange-50 vaut new-orange-50
- Comment tester ? : vérifier que les tests unitaires passent et que le orange des attestations de fin de formation s'affiche correctement (mobile + webapp)

COM-2931: refacto colors

---

src/repositories/CourseRepository.js
tests/integration/courses.test.js

</details>
---
</details>
---
</details>
---
- Périmètre interfaces / rôles : formation / intervenant
- affichage des prochains rdv dans l'espace intervenant sur mobile 
- Comment tester ? 
- voir sur la PR mobile

COM-2975-2 use formatNextStep in TrainerCourses

---

src/controllers/courseController.js
src/helpers/courses.js
src/routes/courses.js
src/routes/preHandlers/courses.js
tests/integration/courses.test.js
tests/unit/helpers/courses.test.js

</details>
---
</details>
---
</details>
---
- Périmètre interfaces / rôles : mobile formation tous
- Cas d'usage : je peux accéder à une formation
- faire tourner les tests unitaires/intégration
- sur l'app mobile accéder à une formation depuis la notification/depuis la liste de nos formations 

COM-2998: remove course/id/user route

---

src/helpers/courses.js
tests/unit/helpers/courses.test.js

</details>
---
</details>
---
</details>
---
- Périmètre interfaces / rôles : rof / coach / formateur
- ajout de l'email du contact dans la requete `GET /course?action=operation`
- sur la webapp, verifier que rien a bougé sur le cmp `ProfileOrga`
- sur mobile, voir la PR 

COM-3000 add contact.local.email to getCourseForOperation

---

src/helpers/bills.js
tests/unit/helpers/bills.test.js

</details>
---
</details>
---
</details>
---
- Périmètre interfaces / rôles : Admin / Cocach / aidant
- Cas d'usage : Quand je telecharge la facture, j'ai le bon montant
- Comment tester ? : tester sur FACT-110082200108 chez Alenvi Fontainebleau

COM-3021 - fix sum on bill

---

src/controllers/attendanceController.js
src/controllers/courseController.js
src/helpers/attendances.js
src/helpers/bills.js
src/helpers/contracts.js
src/helpers/courses.js
src/helpers/eventsValidation.js
src/models/CourseSmsHistory.js
src/routes/attendances.js
src/routes/courses.js
src/routes/preHandlers/attendances.js
src/routes/preHandlers/courses.js
tests/integration/attendances.test.js
tests/integration/courses.test.js
tests/integration/seed/attendancesSeed.js
tests/unit/helpers/attendances.test.js
tests/unit/helpers/bills.test.js
tests/unit/helpers/contracts.test.js
tests/unit/helpers/courses.test.js
tests/unit/helpers/eventsValidation.test.js

MES (mep mobile) 30/09

---

src/helpers/courses.js
tests/unit/helpers/courses.test.js

</details>
---
</details>
---
</details>
---
- Périmètre interfaces / rôles : mobile formateur
- Cas d'usage : dans l'espace intervenant d'une formation j'ai une section émargement avec des boutons pour les feuilles d'émargements à uploader et des icônes pour les feuilles déjà uploadées
- afficher l'espace intervenant pour une formation sans feuilles d'émargement/ avec quelques feuilles d'émargements/ avec toutes les feuilles d'émargements

COM-3200: populate slots

---

src/routes/preHandlers/courses.js
tests/integration/courses.test.js
tests/integration/seed/coursesSeed.js

</details>
---
</details>
---
</details>
---
- Périmètre interfaces / rôles : client coach/admin
- Cas d'usage : le coach peut modifier le référent structure même quand celui-ci est contact de la formation
- dans une formation intra, en tant que coach sans rôle vendeur rof/admin je peux modifier le référent structure même si il est contact de la formation
- vérifier que je peux toujours modifier le référent structure en tant que rof/admin

COM-3220: coach can update company representative

---

.github/pull_request_template.md
src/helpers/attendanceSheets.js
tests/unit/helpers/attendanceSheets.test.js

</details>
---
</details>
---
</details>

COM-3225: return identity

---

src/helpers/dates/companiDates.js
tests/unit/helpers/dates/companiDates.test.js

</details>
---
</details>
---
</details>

Com 3215 fix

---

src/routes/preHandlers/attendances.js
tests/integration/attendances.test.js

</details>
---
</details>
---
</details>

COM-3256 - replace company by companies and uncomment tests

---

src/helpers/authentication.js
src/helpers/dates/companiDurations.js
src/models/User.js
tests/integration/authentication.test.js
tests/unit/helpers/authentication.test.js
tests/unit/helpers/dates/companiDuration.test.js

</details>
---
</details>
---
- Aucun changement entre l'appli actuelle et les anciennes versions sur l'authentification, j'ai donc testé uniquement la dernière version
- Aucun changement entre l'appli actuelle et les anciennes versions sur l'authentification, j'ai donc testé uniquement la dernière version
</details>

COM-3240 use CompaniDate/Duration in authentication

---

src/routes/preHandlers/courses.js
tests/integration/courses.test.js
tests/integration/seed/coursesSeed.js

</details>
---
</details>
---
</details>

COM-3262 - allow new companyRepresentative to be contact directly

---

src/data/pdf/attendanceSheet/interAttendanceSheet.js
src/data/pdf/attendanceSheet/intraAttendanceSheet.js
src/data/pdf/courseBilling/courseBill.js
src/data/pdf/courseBilling/courseCreditNote.js
src/data/pdf/courseBilling/utils.js
src/helpers/courseBills.js
src/helpers/courseCreditNotes.js
src/helpers/courses.js
tests/unit/data/courseBill.test.js
tests/unit/data/courseCreditNote.test.js
tests/unit/data/interAttendanceSheet.test.js
tests/unit/data/intraAttendanceSheet.test.js
tests/unit/helpers/courseBills.test.js
tests/unit/helpers/courseCreditNotes.test.js
tests/unit/helpers/courses.test.js

</details>
---
</details>
---
</details>

Com 3259 2

---

src/helpers/constants.js
src/helpers/courses.js
src/helpers/utils.js

</details>
---
</details>
---
</details>

COM-3265: remove formatHourWithMinute

---

tests/unit/helpers/dates/companiDuration.test.js

</details>
---
</details>
---
</details>

COM-3247 add test in isLongerThan

---

src/helpers/courseHistories.js
tests/unit/helpers/courseHistories.test.js

</details>
---
</details>
---
</details>

COM-3284: create history on endDate update

---

src/routes/preHandlers/courses.js

</details>
---
</details>
---
</details>

COM-3287 - use companies instead of trainees.company

---

src/routes/preHandlers/courseHistories.js

</details>
---
</details>
---
</details>

COM-3308: refacto prehandler

---

src/helpers/courseHistories.js
src/helpers/dates/companiDates.js
tests/unit/helpers/courseHistories.test.js
tests/unit/helpers/dates/companiDates.test.js

</details>
---
</details>
---
</details>

COM-3303 add specific history when updating date and hour

---

src/routes/preHandlers/courses.js

</details>
---
</details>
---
</details>

COM-3304 - use course.companies in getDocumentAndSms method

---

src/helpers/courseBills.js
tests/unit/helpers/courseBills.test.js

</details>
---
</details>
---
</details>

COM-3264: remove type in select

---

src/helpers/questionnaires.js
tests/unit/helpers/questionnaires.test.js

</details>
---
</details>
---
</details>

COM-3310: show company name if intra

---

src/routes/preHandlers/attendanceSheets.js

</details>
---
</details>
---
</details>

COM-3312 - remove course.type conditions

---

src/helpers/vendorHistoryExport.js
tests/unit/helpers/vendorHistoryExport.test.js

</details>
---
<details close><summary> POINTS D'ATTENTION POUR CETTE PR  :warning: </summary>
</details>
---
<details close><summary> FONCTIONNALITÉS APPS MOBILES  :iphone: </summary>
</details>

COM-3322 - displays only validated invoices in courseHistoryExport

---

src/helpers/vendorHistoryExport.js
tests/integration/exports.test.js
tests/integration/seed/exportsSeed.js
tests/unit/helpers/vendorHistoryExport.test.js

</details>
---
</details>
---
</details>

COM-3320-fix payment number

---

src/helpers/vendorHistoryExport.js
tests/integration/exports.test.js
tests/unit/helpers/vendorHistoryExport.test.js

</details>
---
</details>
---
</details>

COM-3321-fix considere slotToPlan

---

src/controllers/attendanceController.js
src/controllers/exportController.js
src/helpers/attendances.js
src/helpers/courses.js
src/helpers/vendorHistoryExport.js
src/models/Attendance.js
src/repositories/CourseRepository.js
src/routes/preHandlers/courses.js
tests/unit/helpers/attendances.test.js
tests/unit/helpers/courses.test.js
tests/unit/helpers/vendorHistoryExport.test.js

</details>
---
</details>
---
</details>

COM-3328: use company in attendance get

---

src/helpers/courses.js
tests/unit/helpers/courses.test.js

</details>
---
</details>
---
</details>

COM-3328: fix for trainers

---

src/helpers/users.js
tests/integration/users.test.js
tests/unit/helpers/users.test.js

</details>
---
</details>
---
</details>

COM-3323: remove populate

---

.github/workflows/integration.js.yml

</details>
---
</details>
---
</details>

COM-3347 - update github action mongodb version

---

src/controllers/userController.js
src/helpers/users.js
src/routes/preHandlers/users.js
tests/integration/seed/usersSeed.js
tests/integration/users.test.js
tests/unit/helpers/users.test.js

</details>
---
</details>
---
</details>

COM-3362: create drive folder for good company

---

src/models/User.js

</details>
---
</details>
---
</details>

COM-3368 fix userCompanyList virtual

---

src/repositories/CourseRepository.js
tests/integration/courses.test.js
tests/integration/seed/coursesSeed.js

</details>
---
</details>
---
</details>

COM-3372 add filter on kanban : no address

---

src/helpers/courses.js
src/helpers/userCompanies.js
src/helpers/users.js
src/models/User.js
src/routes/preHandlers/sms.js
src/routes/preHandlers/users.js
tests/unit/helpers/courses.test.js
tests/unit/helpers/userCompanies.test.js
tests/unit/helpers/users.test.js

</details>
---
</details>
---
</details>

COM-3377: refacto userCompanyList

---

src/repositories/CourseRepository.js

</details>
---
</details>
---
</details>

COM-3373-2 select maxTrainees

---

src/routes/preHandlers/companyLinkRequests.js
tests/integration/companyLinkRequests.test.js
tests/integration/courseBills.test.js
tests/integration/seed/companyLinkRequestsSeed.js
tests/integration/users.test.js
tests/seed/authUsersSeed.js

</details>
---
</details>
---
</details>

COM-3339: can request attachement for  a detached user

---

src/controllers/attendanceSheetController.js
src/helpers/attendanceSheets.js
src/helpers/vendorHistoryExport.js
src/models/AttendanceSheet.js
src/routes/attendanceSheets.js
src/routes/preHandlers/attendanceSheets.js
src/routes/preHandlers/courses.js
tests/unit/helpers/attendanceSheets.test.js
tests/unit/helpers/vendorHistoryExport.test.js

</details>
---
</details>
---
</details>

COM-3333: add company in query

---

package.json

</details>
---
</details>
---
</details>
Fix suite au probleme lors de la MEP du 8 fevrier

move form-data et get-stream from devdependencies to dependencies

---

src/helpers/userCompanies.js
tests/integration/seed/usersSeed.js
tests/integration/users.test.js
tests/unit/helpers/userCompanies.test.js

</details>
---
</details>
---
</details>

COM-3393: fix wrong start date in error message

---

tests/integration/users.test.js

</details>
---
</details>
---
</details>

decomment tests

---

src/helpers/courses.js
tests/unit/helpers/courses.test.js

</details>
---
</details>
---
</details>

COM-3402: filter trainee progress by company

---

src/helpers/attendanceSheets.js
tests/integration/seed/attendanceSheetsSeed.js
tests/unit/helpers/attendanceSheets.test.js

</details>
---
</details>
---
</details>

COM-3356: create attendance sheet with company at registration

---

src/jobs/updateRole.js
src/plugins/index.js

- J'ai l'impression qu'on a pas trop de test pour les scripts. On en a seulement quelques unes pour la facturation. Je me suis demandee s'il fallait que j'ecrive de nouveaux tests mais comme c'est que cote erp, je me suis dit que ca vallait pas le coup. Qu'en pensez-vous ? 
</details>
---
</details>
---
</details>

COM-3411 fix update role + run it every two weeks

---

src/data/pdf/attendanceSheet/interAttendanceSheet.js
src/helpers/courses.js
tests/unit/data/interAttendanceSheet.test.js
tests/unit/helpers/courses.test.js

</details>
---
</details>
---
</details>

COM-3415 rename company to regitrationCompany

---

src/helpers/translate.js
src/routes/preHandlers/trainingContracts.js
tests/integration/trainingContracts.test.js

</details>
---
</details>
---
</details>

COM-3424: add error message

---

src/config/mongoose.js

</details>
---
</details>
---
</details>

COM-3430 - allow automatic connection on server start with mongodb 5

---

.github/workflows/integration.js.yml

</details>
---
</details>
---
</details>

COM-3447 - update mongodb version in github action

---

tests/integration/seed/coursesSeed.js
tests/integration/seed/seedsVerification.test.js
tests/integration/seed/stepsSeed.js
tests/integration/seed/subProgramsSeed.js

</details>
---
</details>
---
</details>

COM-3446: tests

---

src/helpers/programs.js
tests/unit/helpers/programs.test.js

</details>
---
</details>
---
</details>

COM-3453: remove empty image in program

---

src/helpers/courses.js
src/routes/courses.js
src/routes/preHandlers/courses.js
tests/integration/courses.test.js
tests/unit/helpers/courses.test.js

</details>
---
</details>
---
</details>

COM-3452: add query to route

---

src/helpers/utils.js
src/routes/preHandlers/courses.js
tests/integration/courses.test.js
tests/unit/helpers/utils.test.js

</details>
---
</details>
---
</details>

COM-3475: can access course as holding admin

---

src/controllers/courseController.js
src/helpers/courses.js
src/routes/courses.js
src/routes/preHandlers/courses.js
tests/integration/courses.test.js
tests/unit/helpers/courses.test.js

</details>
---
</details>
---
</details>

COM-3479: get learners follow up

---

src/data/rights.js
src/helpers/utils.js
src/routes/preHandlers/courses.js
tests/integration/courseSlots.test.js
tests/integration/seed/courseSlotsSeed.js
tests/unit/helpers/utils.test.js

</details>
---
</details>
---
</details>

COM-3477: can edit slots

---

src/data/rights.js
src/routes/preHandlers/users.js
tests/integration/courses.test.js
tests/integration/seed/coursesSeed.js
tests/integration/users.test.js

</details>
---
</details>
---
</details>

COM-3480: can edit and delete trainee

---

src/routes/preHandlers/courseHistories.js
tests/integration/courseHistories.test.js
tests/integration/seed/courseHistoriesSeed.js

</details>
---
</details>
---
</details>

COM-3485: can get course histories

---

src/routes/preHandlers/userCompanies.js
tests/integration/userCompanies.test.js

</details>
---
</details>
---
</details>

COM-3488: can create user company for user from holding

---

src/controllers/trainingContractController.js
src/helpers/trainingContracts.js
src/routes/preHandlers/trainingContracts.js
src/routes/trainingContracts.js
tests/integration/seed/trainingContractsSeed.js
tests/integration/trainingContracts.test.js
tests/unit/helpers/trainingContracts.test.js

</details>
---
</details>
---
</details>

COM-3482: add queries

---

src/routes/preHandlers/email.js
src/routes/preHandlers/users.js
tests/integration/email.test.js
tests/integration/seed/emailSeed.js
tests/integration/users.test.js

</details>
---
</details>
---
</details>

COM-3489: can create user

---

src/helpers/companies.js
src/routes/companies.js
src/routes/preHandlers/companies.js
tests/integration/companies.test.js
tests/unit/helpers/companies.test.js

</details>
---
</details>
---
</details>

COM-3504 - populate BillingRepresentative + add prehandler check

---

src/routes/questionnaires.js
tests/integration/questionnaires.test.js

</details>
---
</details>
---
</details>

COM-3521 - restrictive questionnnaire card templates

---

src/helpers/courses.js
tests/unit/helpers/courses.test.js

</details>
---
</details>
---
</details>

COM-3537: can download attendance sheet without trainees

---

src/helpers/courses.js
src/routes/courses.js
src/routes/preHandlers/courses.js
tests/integration/courses.test.js
tests/unit/helpers/courses.test.js

</details>
---
</details>
---
</details>

COM-3538: can archive and unarchive course easily

---

src/helpers/courses.js
src/routes/courses.js
src/routes/preHandlers/courses.js
tests/integration/courses.test.js
tests/integration/seed/coursesSeed.js
tests/unit/helpers/courses.test.js

</details>
---
</details>
---
</details>

COM-3513: can see courses table

---

src/helpers/users.js
src/routes/preHandlers/courses.js
src/routes/users.js
tests/integration/courses.test.js
tests/integration/users.test.js
tests/unit/helpers/users.test.js

</details>
---
</details>
---
</details>

COM-3539: holding admin as company representative

---

src/helpers/authentication.js
src/routes/authentication.js
src/routes/preHandlers/authentication.js
tests/integration/authentication.test.js
tests/integration/seed/emailSeed.js
tests/unit/helpers/authentication.test.js

</details>
---
</details>
---
</details>

COM-3568 - throw 401 if missing refresh token

---

src/data/pdf/billing/bill.js

</details>
---
</details>
---
</details>

COM-3570: use get

---

tests/integration/seed/customersSeed.js

</details>
---
</details>
---
</details>

COM-3450 - update customer seed

---

src/data/pdf/attendanceSheet/intraAttendanceSheet.js
src/helpers/courses.js
src/routes/preHandlers/courses.js
tests/integration/courses.test.js
tests/integration/seed/coursesSeed.js
tests/unit/data/intraAttendanceSheet.test.js
tests/unit/helpers/courses.test.js

</details>
---
</details>
---
</details>

COM-3560: can download attendance sheet

---

src/routes/preHandlers/courseSlot.js
tests/integration/courseSlots.test.js
tests/integration/seed/courseSlotsSeed.js

</details>
---
</details>
---
</details>

COM-3562: can edit slot

---

src/routes/preHandlers/courseHistories.js
tests/integration/courseHistories.test.js
tests/integration/seed/courseHistoriesSeed.js

</details>
---
</details>
---
</details>

COM-3564: can get history

---

src/routes/preHandlers/attendances.js
tests/integration/attendances.test.js
tests/integration/seed/attendancesSeed.js

</details>
---
</details>
---
</details>

COM-3581: can get attendances

---

src/data/pdf/courseBilling/utils.js
src/helpers/courseBills.js
src/helpers/courses.js
src/helpers/utils.js
src/routes/preHandlers/courseBills.js
tests/integration/courseBills.test.js
tests/unit/data/courseBill.test.js
tests/unit/data/courseCreditNote.test.js
tests/unit/helpers/courseBills.test.js

</details>
---
</details>
---
</details>

COM-3613: can download course bill

---

src/helpers/vendorHistoryExport.js
src/repositories/CourseRepository.js
tests/integration/exports.test.js
tests/integration/seed/exportsSeed.js
tests/unit/helpers/vendorHistoryExport.test.js

</details>
---
</details>
---
</details>

COM-3617: can export bills and credit notes

---

src/helpers/courseBills.js
src/helpers/coursePayments.js
src/models/CoursePayment.js
src/routes/coursePayments.js
src/routes/preHandlers/coursePayments.js
tests/integration/coursePayments.test.js
tests/integration/seed/coursePaymentsSeed.js
tests/integration/seed/exportsSeed.js
tests/integration/seed/seedsVerification.test.js
tests/unit/helpers/courseBills.test.js
tests/unit/helpers/courseCreditNotes.test.js
tests/unit/helpers/coursePayments.test.js

</details>
---
</details>
---
</details>

COM-3616: change course payment model from company to companies

---

src/data/pdf/courseBilling/utils.js
src/helpers/constants.js
src/models/CourseBill.js
src/routes/courseBills.js
src/routes/preHandlers/courseBills.js
tests/integration/courseBills.test.js
tests/integration/seed/courseBillsSeed.js
tests/integration/seed/courseCreditNotesSeed.js
tests/integration/seed/courseFundingOrganisationsSeed.js
tests/integration/seed/coursePaymentsSeed.js
tests/integration/seed/coursesSeed.js
tests/integration/seed/exportsSeed.js
tests/integration/seed/seedsVerification.test.js
tests/unit/data/courseBill.test.js
tests/unit/data/courseCreditNote.test.js

</details>
---
</details>
---
</details>

COM-3608: add count unit in model

---

src/data/pdf/courseBilling/utils.js
src/helpers/constants.js
src/helpers/courseBills.js
src/models/CourseBill.js
tests/unit/data/courseBill.test.js
tests/unit/helpers/courseBills.test.js

</details>
---
</details>
---
</details>

COM-3609: don't show company if payer is company

---

src/routes/preHandlers/trainingContracts.js
tests/integration/seed/trainingContractsSeed.js
tests/integration/trainingContracts.test.js

</details>
---
</details>
---
</details>

COM-3587: can get holding training contracts

---

src/data/pdf/trainingContract.js
src/helpers/trainingContracts.js

</details>
---
</details>
---
</details>

COM-3588: include intra_holding case

---

src/routes/courses.js
tests/integration/courses.test.js

</details>
---
</details>
---
</details>

COM-3626 - remove useless field

---

src/routes/users.js
tests/integration/users.test.js

</details>
---
</details>
---
</details>

COM-3627: add verification

---

src/models/Course.js
src/routes/courses.js
src/routes/preHandlers/courses.js
tests/integration/courses.test.js

</details>
---
</details>
---
</details>

COM-3631: a course can have certifying tests

---

src/helpers/courses.js
src/routes/authentication.js
tests/integration/authentication.test.js
tests/unit/helpers/courses.test.js

</details>
---
</details>
---
</details>

COM-3648: can connect to API with old mobile version

---

src/controllers/trainerMissionController.js
src/data/rights.js
src/helpers/trainerMissions.js
src/helpers/translate.js
src/models/TrainerMission.js
src/routes/preHandlers/trainerMissions.js
src/routes/trainerMissions.js
tests/integration/seed/seedsVerification.test.js
tests/integration/seed/trainerMissionsSeed.js
tests/integration/trainerMissions.test.js
tests/unit/helpers/authorization.test.js
tests/unit/helpers/trainerMission.test.js

</details>
---
</details>
---
</details>

COM-3630: can cancel trainer mission

---

src/helpers/users.js
tests/unit/helpers/users.test.js

</details>
---
</details>
---
</details>

COM-3645 - populate salesRepresentative to display it on ContactProfile

---

src/controllers/courseBillController.js
src/data/pdf/courseBilling/courseBill.js
src/data/pdf/courseBilling/courseCreditNote.js
src/data/pdf/courseBilling/utils.js
src/helpers/courseBills.js
src/routes/courseBills.js
src/routes/preHandlers/courseBills.js
tests/unit/data/courseBill.test.js
tests/unit/data/courseCreditNote.test.js
tests/unit/helpers/courseBills.test.js

</details>
---
</details>
---
</details>

COM-3647 : can display paid mention on bills

---

src/controllers/trainerMissionController.js
src/helpers/trainerMissions.js
src/models/TrainerMission.js
src/routes/trainerMissions.js
tests/integration/seed/trainerMissionsSeed.js
tests/integration/trainerMissions.test.js
tests/unit/helpers/trainerMission.test.js

</details>
---
</details>
---
</details>

COM-3629: trainer can get own trainer missions

---

yarn.lock

</details>
---
</details>
---
</details>

COM-3658: fix yarn.lock

---

src/helpers/courses.js
src/routes/courses.js
tests/integration/courses.test.js
tests/integration/seed/coursesSeed.js

</details>
---
</details>
---
</details>

COM-3518 : can remove trainer from course

---

src/helpers/users.js
src/routes/preHandlers/companies.js
tests/integration/companies.test.js
tests/integration/seed/seedsVerification.test.js
tests/integration/users.test.js
tests/unit/helpers/users.test.js

</details>
---
</details>
---
</details>

COM-3666: can get holding admins when request on users

---

src/helpers/constants.js
src/models/Questionnaire.js
src/routes/preHandlers/questionnaires.js
src/routes/questionnaires.js
tests/integration/questionnaires.test.js
tests/integration/seed/questionnairesSeed.js

</details>
---
</details>
---
</details>

COM-3670 - add program in GET /questionnaires query

---

src/controllers/questionnaireController.js
src/helpers/questionnaires.js
src/routes/preHandlers/questionnaires.js
src/routes/questionnaires.js
tests/integration/questionnaires.test.js
tests/unit/helpers/questionnaires.test.js

</details>
---
</details>
---
</details>

COM-3687: refacto routes

---

package.json
yarn.lock

</details>
---
</details>
---
</details>

COM-3711: update docxtemplater

---

src/data/pdf/courseBilling/courseBill.js
src/data/pdf/courseBilling/courseCreditNote.js
src/data/pdf/courseBilling/utils.js
tests/unit/data/courseBill.test.js
tests/unit/data/courseCreditNote.test.js

</details>
---
</details>
---
</details>

COM-3723: add missing verbatim

---

src/helpers/courses.js
tests/unit/helpers/courses.test.js

</details>
---
<details clsoed><summary> POINTS D'ATTENTION POUR CETTE PR  :warning: </summary>
</details>
---
</details>

COM-3721 - populate histories to get timeline

---

src/controllers/taxCertificateController.js
src/helpers/taxCertificates.js
src/repositories/PaymentRepository.js
tests/unit/helpers/taxCertificates.test.js

</details>
---
</details>
---
</details>

COM-3726: update helper return

---

src/models/VendorCompany.js
src/models/utils.js
src/routes/validations/utils.js
src/routes/vendorCompanies.js
tests/integration/seed/courseBillsSeed.js
tests/integration/seed/courseCreditNotesSeed.js
tests/integration/seed/vendorCompaniesSeed.js
tests/integration/vendorCompanies.test.js

</details>
---
</details>
---
</details>

COM-3736: add two new fields to vendorCompany

---

src/data/pdf/courseBilling/courseBill.js
src/data/pdf/courseBilling/courseCreditNote.js
src/data/pdf/courseBilling/utils.js
tests/unit/data/courseBill.test.js
tests/unit/data/courseCreditNote.test.js

</details>
---
</details>
---
</details>

COM-3741: add verbatim on bills

---

.github/workflows/integration.js.yml

</details>
---
</details>
---
</details>

COM-3754 - update mongodb version in ci

---

src/helpers/companies.js
src/models/Company.js
src/routes/companies.js
tests/unit/helpers/companies.test.js

</details>
---
</details>
---
</details>

COM-3748: display holding name

---

src/helpers/questionnaires.js
tests/unit/helpers/questionnaires.test.js

</details>
---
</details>
---
</details>

COM-3700 - populate companies and subProgram name

---

src/helpers/questionnaires.js
tests/unit/helpers/questionnaires.test.js

</details>
---
</details>
---
</details>

COM-3704 - return history and trainee to get Count

---

src/helpers/users.js
tests/unit/helpers/users.test.js

</details>
---
</details>
---
</details>

COM-3753: populate company

---

src/helpers/courses.js
tests/unit/helpers/courses.test.js

</details>
---
</details>
---
</details>

COM-3704-fix - format activityHistories answers

---

src/repositories/CourseRepository.js
tests/integration/courses.test.js

</details>
---
</details>
---
</details>

COM-3751: populate holding

---

src/helpers/companies.js
src/routes/companies.js
src/routes/preHandlers/companies.js
tests/integration/companies.test.js
tests/unit/helpers/companies.test.js

</details>
---
</details>
---
</details>

COM-3749: can link to holding on creation

---

src/helpers/questionnaires.js
tests/unit/helpers/questionnaires.test.js

</details>
---
</details>
---
</details>

COM-3763 - add timeline in answers followUp

---

src/routes/courseBills.js
tests/integration/courseBills.test.js

</details>
---
</details>
---
</details>

COM-3783: can add description on creation

---

src/helpers/courses.js
tests/unit/helpers/courses.test.js

</details>
---
</details>
---
</details>

COM-3774: populate holding

---

src/routes/preHandlers/utils.js
tests/integration/activityHistories.test.js
tests/integration/seed/activityHistoriesSeed.js

</details>
---
</details>
---
</details>

COM-3771: can add qcu answers in bdd

---

src/routes/preHandlers/utils.js
tests/integration/activityHistories.test.js
tests/integration/seed/activityHistoriesSeed.js

</details>
---
</details>
---
</details>

COM-3773: can add order the sequence answers in bdd

---

src/controllers/attendanceSheetController.js
src/helpers/attendanceSheets.js
src/helpers/courses.js
src/helpers/translate.js
src/routes/attendanceSheets.js
src/routes/preHandlers/attendanceSheets.js
src/routes/preHandlers/courses.js
tests/integration/courses.test.js
tests/unit/helpers/attendanceSheets.test.js
tests/unit/helpers/courses.test.js

</details>
---
</details>
---
</details>

COM-3788: delete attendance sheet and questionnaire history

---

src/data/pdf/courseBilling/courseBill.js
src/data/pdf/courseBilling/utils.js
tests/unit/data/courseBill.test.js

</details>
---
</details>
---
</details>

COM-3802: fix big number bug on course bills

---

src/helpers/courses.js
tests/unit/helpers/courses.test.js

</details>
---
</details>
---
</details>

COM-3796 : populate trainers in getCourseForQuestionnaire

---

src/routes/preHandlers/courses.js
tests/integration/courses.test.js

</details>
---
</details>
---
</details>

COM-3809: sms history with trainers

---

src/routes/preHandlers/courseSlot.js
tests/integration/courseSlots.test.js
tests/integration/seed/courseSlotsSeed.js

</details>
---
</details>
---
</details>

COM-3807: change trainer with trainers in courseSlot

---

tests/integration/courses.test.js

</details>
---
</details>
---
</details>

COM-3831 - uncomment tests

---

src/routes/preHandlers/attendances.js
tests/integration/attendances.test.js
tests/integration/seed/attendancesSeed.js

</details>
---
</details>
---
</details>

COM-3827 - authorize all trainers to add and remove attendances

---

src/repositories/CourseRepository.js

</details>
---
</details>
---
</details>

COM-3852: sort slots

---

src/helpers/questionnaires.js
src/routes/preHandlers/questionnaires.js
tests/integration/questionnaires.test.js
tests/unit/helpers/questionnaires.test.js

</details>
---
</details>
---
</details>

COM-3838: change trainer in trainers on questionnaires + tests

---

src/routes/preHandlers/attendanceSheets.js
tests/integration/attendanceSheets.test.js
tests/integration/seed/attendanceSheetsSeed.js

</details>
---
</details>
---
</details>

COM-3836: modification trainer in trainers

---

src/helpers/courses.js
tests/integration/courses.test.js
tests/integration/seed/coursesSeed.js

</details>
---
</details>
---
</details>

COM-3867:change trainer with trainers in getTrainerList

---

src/routes/preHandlers/questionnaireHistories.js
tests/integration/questionnaireHistories.test.js
tests/integration/seed/questionnaireHistoriesSeed.js

</details>
---
</details>
---
</details>

COM-3843: modification trainer with trainers in questionnairesHistories

---

src/controllers/attendanceSheetController.js
src/helpers/attendanceSheets.js
src/helpers/courses.js
src/helpers/gCloudStorage.js
src/models/AttendanceSheet.js
src/routes/attendanceSheets.js
tests/integration/attendanceSheets.test.js
tests/unit/helpers/attendanceSheets.test.js
tests/unit/helpers/courses.test.js

</details>
---
</details>
---
</details>

COM-3851: add field signatures in attendance sheet

---

src/helpers/questionnaires.js
tests/unit/helpers/questionnaires.test.js

</details>
---
</details>
---
</details>

COM-3873: add trainerComment in questionnaires

---

src/helpers/questionnaires.js

</details>
---
</details>
---
</details>

COM-3894 - fix undefined course in url

---

src/helpers/utils.js
tests/unit/helpers/utils.test.js

</details>
---
</details>
---
</details>

COM-3882: make the method more robust

---

src/helpers/utils.js
tests/unit/helpers/utils.test.js

MES intermediaire 27/01/2025

---

.github/workflows/integration.js.yml

COM-3901: update CI to mongo 7

---

src/helpers/attendanceSheets.js
src/models/Course.js
tests/integration/attendanceSheets.test.js
tests/unit/helpers/attendanceSheets.test.js

</details>
---
</details>
---
</details>

COM-3918: can delete attendance sheet

---

src/helpers/constants.js
src/helpers/courses.js
src/models/Course.js
tests/integration/seed/coursesSeed.js
tests/integration/seed/seedsVerification.test.js

</details>
---
</details>
---
</details>

COM-3916: can display single courses in kanban

---

src/helpers/constants.js
src/models/Course.js
src/routes/courses.js
tests/integration/courses.test.js
tests/integration/seed/attendanceSheetsSeed.js
tests/integration/seed/attendancesSeed.js
tests/integration/seed/courseBillsSeed.js
tests/integration/seed/courseCreditNotesSeed.js
tests/integration/seed/courseFundingOrganisationsSeed.js
tests/integration/seed/courseHistoriesSeed.js
tests/integration/seed/coursePaymentsSeed.js
tests/integration/seed/courseSlotsSeed.js
tests/integration/seed/coursesSeed.js
tests/integration/seed/exportsSeed.js
tests/integration/seed/questionnaireHistoriesSeed.js
tests/integration/seed/questionnairesSeed.js
tests/integration/seed/subProgramsSeed.js
tests/integration/seed/trainerMissionsSeed.js
tests/integration/seed/trainingContractsSeed.js
tests/integration/seed/userCompaniesSeed.js
tests/integration/seed/usersSeed.js

</details>
---
</details>
---
</details>

COM-3909: add logic in creation course for certificate generation mode

---

src/helpers/courses.js
src/helpers/users.js
src/routes/courses.js
src/routes/preHandlers/courses.js
src/routes/users.js
tests/integration/courses.test.js
tests/integration/seed/coursesSeed.js
tests/integration/users.test.js
tests/unit/helpers/courses.test.js
tests/unit/helpers/users.test.js

</details>
---
</details>
---
</details>

COM-3917: wip

---

src/helpers/courses.js
tests/unit/helpers/courses.test.js

</details>
---
</details>
---
</details>

COM-3943: populate connection infos

---

src/routes/preHandlers/courses.js

</details>
---
</details>
---
</details>

COM-3923: use type rather than subprogram

---

src/helpers/completionCertificates.js
src/jobs/completionCertificateCreation.js
src/routes/completionCertificates.js
src/routes/preHandlers/completionCertificates.js
tests/integration/completionCertificates.test.js
tests/integration/seed/completionCertificatesSeed.js
tests/unit/helpers/completionCertificates.test.js
tests/unit/jobs/completionCertificateCreation.test.js

</details>
---
</details>
---
</details>

COM-3912 - can get completion certificates for a specific course

---

src/helpers/courses.js
tests/integration/courses.test.js
tests/unit/helpers/courses.test.js

</details>
---
</details>
---
</details>

COM-3947: format courses by on going, achieved and next steps

---

src/helpers/completionCertificates.js
tests/unit/helpers/completionCertificates.test.js

</details>
---
</details>
---
</details>

COM-3939: populate holding from company in completion certificates

---

src/helpers/courses.js
src/routes/preHandlers/activityHistories.js
tests/integration/activityHistories.test.js
tests/integration/seed/activityHistoriesSeed.js
tests/unit/helpers/courses.test.js

</details>
---
</details>
---
</details>

COM-3948: can save and return tutor progress

---

src/helpers/courses.js
tests/unit/helpers/courses.test.js

</details>
---
</details>
---
</details>

COM-3937: select type

---

src/routes/preHandlers/courseSlot.js
tests/integration/courseSlots.test.js
tests/integration/seed/courseSlotsSeed.js

</details>
---
</details>
---
</details>

COM-3956: block date deletion if attendance sheet

---

src/helpers/notifications.js
src/helpers/subPrograms.js
tests/integration/seed/subProgramsSeed.js
tests/integration/subPrograms.test.js
tests/unit/helpers/notifications.test.js
tests/unit/helpers/subPrograms.test.js

</details>
---
</details>
---
</details>

COM-3942: send notification for courses with access rules

---

src/routes/preHandlers/attendances.js
tests/integration/attendances.test.js
tests/integration/seed/attendancesSeed.js

</details>
---
</details>
---
</details>

COM-3954: can't add attendance for unregistered trainee

---

src/controllers/completionCertificatesController.js
src/helpers/completionCertificates.js
src/helpers/translate.js
src/routes/completionCertificates.js
src/routes/preHandlers/completionCertificates.js
tests/integration/completionCertificates.test.js
tests/integration/seed/completionCertificatesSeed.js
tests/unit/helpers/completionCertificates.test.js

</details>
---
</details>
---
</details>

COM-3946 - create DELETE /completioncertificates/{_id}

---

src/helpers/courses.js
src/helpers/translate.js
src/routes/courses.js
src/routes/preHandlers/courses.js
tests/integration/courses.test.js
tests/integration/seed/coursesSeed.js
tests/unit/helpers/courses.test.js

</details>
---
</details>
---
</details>

COM-3966 - display remote slots in AttendanceSheets

---

src/helpers/courses.js
tests/unit/helpers/courses.test.js

</details>
---
</details>
---
</details>

COM-3969: send notification if add access rule

---

src/helpers/courses.js
src/models/Course.js
src/routes/courses.js
tests/integration/courses.test.js
tests/unit/helpers/courses.test.js

</details>
---
</details>
---
</details>

COM-3971: can add price to course at creation

---

src/helpers/courseBills.js
src/models/CourseBill.js
src/routes/courseBills.js
tests/integration/courseBills.test.js
tests/unit/helpers/courseBills.test.js

</details>
---
</details>
---
</details>

COM-3975: add maturityDate in courseBill

---

src/routes/courseBills.js
tests/integration/courseBills.test.js
tests/integration/seed/courseBillsSeed.js

</details>
---
</details>
---
</details>

COM-3976: add maturityDate on course bill edition

---

src/helpers/courses.js
src/routes/courses.js
src/routes/preHandlers/courses.js
tests/integration/courses.test.js
tests/integration/seed/coursesSeed.js
tests/integration/seed/seedsVerification.test.js
tests/unit/helpers/courses.test.js

</details>
---
</details>
---
</details>

COM-3972: update course with prices in payload

---

src/helpers/companies.js
src/helpers/holdings.js
src/routes/holdings.js
src/routes/preHandlers/holdings.js
tests/integration/holdings.test.js
tests/integration/seed/holdingsSeed.js
tests/unit/helpers/companies.test.js
tests/unit/helpers/holdings.test.js

</details>
---
</details>
---
</details>

COM-3985: modification on holding route PUT

---

src/routes/preHandlers/courseBills.js

</details>
---
</details>
---
</details>

COM-3979: sum can't be bigger than 100% on bills without credit note

---

src/repositories/CourseRepository.js

</details>
---
</details>
---
</details>

COM-4004: can selected course if interruptedAt

---

src/helpers/courseBills.js
src/routes/preHandlers/courseBills.js
tests/integration/courseBills.test.js
tests/integration/seed/courseBillsSeed.js
tests/unit/helpers/courseBills.test.js

</details>
---
</details>
---
</details>

COM-4003: add logic if course is interrupted

---

src/helpers/courseBills.js
src/routes/courseBills.js
tests/integration/courseBills.test.js
tests/unit/helpers/courseBills.test.js

</details>
---
</details>
---
</details>

COM-4010: get all validated bills

---

src/helpers/courses.js
src/routes/courses.js
src/routes/preHandlers/courses.js
tests/integration/courses.test.js
tests/unit/helpers/courses.test.js

Com 4012 master

---

src/helpers/vendorHistoryExport.js
tests/integration/exports.test.js
tests/unit/helpers/vendorHistoryExport.test.js

</details>
---
</details>
---
</details>

COM-4023 - add courseBill.payerId in course_payment export

---

src/helpers/courseBills.js
tests/unit/helpers/courseBills.test.js

</details>
---
</details>
---
</details>

COM-4007 - fix bug when trainers arent defined

---

src/helpers/attendanceSheets.js
src/routes/attendanceSheets.js
src/routes/preHandlers/attendanceSheets.js
src/routes/validations/utils.js
tests/integration/attendanceSheets.test.js
tests/integration/seed/attendanceSheetsSeed.js
tests/integration/seed/seedsVerification.test.js
tests/unit/helpers/attendanceSheets.test.js

</details>
---
</details>
---
</details>

COM-4036: can sign attendance sheet for intra

---

src/helpers/attendanceSheets.js
src/helpers/courses.js
src/routes/preHandlers/attendanceSheets.js
tests/integration/attendanceSheets.test.js
tests/integration/seed/attendanceSheetsSeed.js
tests/unit/helpers/attendanceSheets.test.js
tests/unit/helpers/courses.test.js

</details>
---
</details>
---
</details>

COM-4038: can sign attendance sheet for intra as trainee

---

src/models/Card.js
src/routes/cards.js
src/routes/preHandlers/cards.js
tests/integration/cards.test.js
tests/integration/seed/seedsVerification.test.js

- [] J'ai codé les tests unitaires
</details>
---
</details>
---
</details>

COM-4048: add isChronological for cards

---

src/helpers/courseBills.js
tests/unit/helpers/courseBills.test.js

</details>
---
</details>
---
</details>

COM-4059: display only received status on bill pdf

---

src/data/pdf/attendanceSheet/intraAttendanceSheet.js

</details>
---
</details>
---
</details>

COM-4052: fix bug

---

src/helpers/attendanceSheets.js
src/routes/preHandlers/attendances.js
tests/integration/attendances.test.js
tests/integration/seed/attendanceSheetsSeed.js
tests/unit/helpers/attendanceSheets.test.js

</details>
---
</details>
---
</details>

COM-4054: create attendance on attendance sheet creation

---

src/helpers/translate.js

</details>
---
</details>
---
</details>

COM-4068: rename error

---

.github/workflows/integration.js.yml

</details>
---
</details>
---
</details>

COM-4081: update CI
