CompaniTech/compani-api

controllers/contractController.js
controllers/customerController.js
helpers/contracts.js
helpers/eSign.js
routes/contracts.js
tests/unit/helpers/contracts.test.js

Dans cette PR : 
- Edition de la date d'effet d'un contrat/avenant
-- Si contrat : on met a jour le champ `startDate` dans le premier objet de `versions` et le champ a la racine de `contract`
-- Si avenant : on met a jour le champ `startDate` dans l'objet courant de `versions` et du précédant
- Refacto des routes `contracts` pour les mettre dans l'helper

Com 583 start date

---

src/helpers/events.js
src/helpers/eventsRepetition.js
src/jobs/eventRepetitions.js
tests/unit/helpers/events.test.js
tests/unit/helpers/eventsRepetition.test.js

Objectif de la PR :
- Ne pas verifier les conflits si l'evenement n'est pas affecté
- pour les repetitions, on passe a NEVER la frequence quand un evenement sort de la repetition mais on n'enleve pas son parentId
- quand on met fin a un contrat, il faut passer tous les objets Repetition de l'auxiliaire en "A affecter"

COM-701 - Should not check conflicts on not affected events

---

src/controllers/billsController.js
src/controllers/creditNoteController.js
src/plugins/hapiAuthJwt2.js

Actuellement, on génère un blob sur la webapp afin de l'afficher dans le navigateur. Cela pose trop de problèmes en fonction des différents navigateurs (affichage, téléchargement, ...) comparé à l'utilisation d'un pdf natif. Etant donné, que l'API renvoie un PDF je mets son lien directement ds la webapp afin d'obtenir le PDF original.

COM-562 pdf no more blob

---

src/controllers/creditNoteController.js
src/helpers/creditNotes.js
tests/integration/creditNotes.test.js

Pendant back de la COM-776 sur la migration de la page des avoirs. (lié également aux scripts)
Ce petit fix empêchera la création d'avoirs s'il y a un problème au niveau même de la création ou à la mise à jour des events/fundings (ce qui m'est arrivé -> création des avoirs mais échec du reste).

COM-776 Fix credit note creation

---

src/controllers/eventController.js
src/helpers/customers.js
src/helpers/events.js
src/models/preHooks/validate.js
src/repositories/EventRepository.js
tests/integration/customers.test.js
tests/unit/helpers/customers.test.js
tests/unit/helpers/draftFinalPay.test.js
tests/unit/helpers/draftPay.test.js
tests/unit/helpers/events.test.js

ajout du prehook sur les aggregations des evenements:
- getEventGroupedBy --> planning
- getWorkingEventsForExport --> export
- getCustomerSubscriptions --> utilise lors de la fin d'un contrat pour mettre les evenements en a affecter
- getEventsGroupedByParentId --> suppression en masse des evenements
- getEventsToPay --> paie 
- getEventsToBill --> facturation
- getCustomersFromEvent --> planning beneficiaire
- getCustomersWithBilledEvents --> avoir
- getCustomersWithIntervention --> repertoire beneficiaire

Com 908 event

---

src/helpers/billSlips.js
src/models/BillSlip.js
src/models/BillSlipNumber.js
tests/unit/helpers/billSlips.test.js

NB : ce qui n'allait pas : 
- la collection `BillSlipNumber` n'etait pas mise a jour apres la creation des bordereaux
- les bordereaux etaient créés en doublon
- la page n'etait pas triee par mois

COM-933 - fix bill slip creation

---

src/helpers/stats.js
src/repositories/StatRepository.js
tests/integration/stat.test.js

En partant des evenements et on verifiant que les financements sont bien defini pour les evenements dans le helper plutot que dans l'aggregation, ca permet d'ameliorer de beaucoup les perfs. 
Petit soucis neanmoins, si un beneficiaire n'a pas d'evenement correspondant à la souscription du financement sur les trois mois (dernier, courant, suivant) alors il n'apparaitra pas dans le tableau.

Com 882 from events

---

src/controllers/userController.js
src/helpers/users.js
src/helpers/utils.js
src/models/User.js
tests/integration/users.test.js
tests/unit/helpers/users.test.js
tests/unit/helpers/utils.test.js

En lisant des articles sur l'authentification, je suis repassé sur le code qu'on avait et je me suis permise une petite refacto. N'hesitez pas si vous voyez d'autres pistes d'améliorations
Idem pour le front
pour info par rapport au `forbidden` et `unauthorized `
"In summary, a 401 Unauthorized response should be used for missing or bad authentication, and a 403 Forbidden response should be used afterwards, when the user is authenticated but isn’t authorized to perform the requested operation on the given resource."
https://stackoverflow.com/questions/3297048/403-forbidden-vs-401-unauthorized-http-responses

COM-990 refacto authentication

---

src/helpers/contracts.js
tests/unit/helpers/contracts.test.js

- Périmetre interface : coach
- Périmetre pages : page contrat auxiliaire
- Cas d'usage : Creer un contrat pour une auxiliaire qui est inactive, elle doit alors avoir un role auxiliaire

COM-459 change auxiliary role on contract creation

---

src/repositories/EventRepository.js
tests/integration/exports.test.js
tests/integration/seed/exportSeed.js

- Périmetre interface : interface admin
- Périmetre pages : page export
- Cas d'usage : exporter les evenements sur un an
**Par rapport à l'index:** 
L'aggregation utilise l'index `startDate_-1_endDate_-1_type_-1` meme si on en ajoute un specifique `startDate: -1`. 
J'ai essayé de l'ajouter et de forcer l'aggregation à l'utiliser (avec un `hint`) mais je n'ai pas réussi à faire fonctionner les tests. Comme je ne savais pas si c'etait genant d'utiliser cet index (il a une taille plus important mais qui reste negligeable a cote de la taille max pour le sort) j'ai préféré ouvrir ma pr comme ca pour l'instant. Dites moi ce que vous en pensez :)

COM-1005 sort before lookups

---

src/controllers/companyController.js
src/routes/companies.js
tests/integration/companies.test.js

- Périmetre interface : Vendeur / admin + responsable organisme formation
- Périmetre pages : repertoire structures
- Cas d'usage : Creation d'une structure
NB : on garde `tradeName` et `type` en obligatoire dans le model de l'organisation

COM-1028 - update post route

---

src/helpers/constants.js
src/helpers/dataExport.js
src/helpers/users.js
tests/integration/users.test.js
tests/unit/helpers/users.test.js

- Périmetre roles : Coach / auxiliaire
- Cas d'usage : Affichage des auxiliaire dont le role est `auxiliary_without_company` dans le planning

COM-1101 - get all auxiliary roles on planning

---

src/helpers/courses.js
tests/unit/helpers/courses.test.js

- Cas d'usage : Les cartes d'une formation possedent les infos suivantes: 
- programme
- entreprise
- formateur
- Nombre de stagiaire
- Nombre de jours de formations

COM-1132 populate courses

---

src/helpers/translate.js
src/helpers/users.js
tests/integration/users.test.js
tests/unit/helpers/users.test.js

- Cas d'usage : Dans la modale de creation de formateur, un conflit avec un formateur déjà présent renvoie un notify spécifique. Depuis le back, on renvoie une 409 (anciennement 400)
rien a changer dans le front, la 409 était en fait attendu

Com 1178 fix

---

src/helpers/users.js
tests/unit/helpers/users.test.js

- Périmetre interface : -
- Périmetre roles : -
- Cas d'usage : Fix a l'authentification
-- Ne renvoyer l'erreur a la fin, apres toutes les verifications pour ne pas donner d'information au hacker
-- Si pas de mot de passe enregistrer, envoyer une string vide a bcrypt pour ne pas avoir une erreur

Fix authenticate

---

src/helpers/events.js
src/helpers/eventsRepetition.js
tests/unit/helpers/events.test.js

- Périmetre roles : Coach, auxiliaire
Creer une repetition en "A affecter" , mettre a jour cette repetition en ajoutant une auxilaire. les evenements en conflit seront mis a jour sans secteur... => Corrige

COM-1217 - fix updateRepetitions

---

src/routes/courses.js
src/routes/preHandlers/courseSlot.js
src/routes/preHandlers/courses.js
tests/integration/courseSlots.test.js
tests/integration/courses.test.js
tests/integration/seed/courseSlotsSeed.js
tests/integration/seed/coursesSeed.js
tests/seed/roleSeed.js

- Périmetre roles : coach / client_admin
- Cas d'usage : en tant que coach/admin, je peux lire et editer les infos d'une formations de ma structure
> note : pour les test d'integration courses.test.js : 
- j'ai fait un essai (dans la boucle des 'other roles') pour preciser qu'on essaie avec une structure differentes de celle de l'utilisateur.ice. Je suis pas très satisfait de se que j'ai fait ( rajouter la 'situation') dites moi si vous en pensez 
- je teste une fois avec les deux roles, puis ensuite que avec clien_admin, ça vous parait bien ?

COM-1202 add courses:edit with restriction to coach/admin

---

src/helpers/draftPay.js
tests/unit/helpers/draftPay.test.js

- Cas d'usage : refacto du calcul des evenements, on attribut au contrat en cours a la fin du mois uniquement les évènements qui lui correspondent

COM-1274 select only events within contract in draftPay

---

src/data/attendanceSheet.html
src/helpers/courses.js
tests/unit/helpers/courses.test.js

- Cas d'usage : - pour l'attestation de fin de stage, mofication du template (gdrive) pour enlever le course.name et ne garder que course.programName.
- pour les feuilles de présence, ajout du nom du programme au titre de la formation

COM-1300 in attendance sheet add program name to course title

---

src/controllers/scriptController.js
src/helpers/eventsRepetition.js
src/jobs/eventRepetitions.js
tests/unit/helpers/eventsRepetition.test.js
tests/unit/jobs/eventRepetitions.test.js

- Cas d'usage : Ajouter un ordre dans la script des repetitions pour que les indispo et les heures internes soient creees avant les interventions

COM-1320 - organise repetitions

---

src/controllers/courseController.js
src/helpers/courses.js
src/repositories/CourseRepository.js
src/routes/courses.js
tests/integration/courses.test.js
tests/unit/helpers/courses.test.js

- Périmetre interface : page info formation
- Périmetre roles : tous/ meme sans authentification
- Cas d'usage : nouvelle route pour fournir les infos publics d'une formation sur la page info formation. 
L'ancienne route devient protégée par courses:read. Dans le futur ticket (dont on a parlé en daily) pour proteger les formations intra (et inter sans stagiaire de la structure ?) des utilisateur.ices d'autre structures on pourra rajouter un prehandler a cette route.

COM-1298-public-infos add specific route for course's public infos

---

src/data/rights.js
tests/integration/payments.test.js
tests/unit/helpers/authentication.test.js

- Cas d'usage : retirer aux coachs la possibilité de créer et modifier des paiements

COM-736 - remove payments right to coach

---

src/helpers/eventsValidation.js
src/helpers/users.js
src/routes/contracts.js
tests/integration/seed/contractsSeed.js
tests/unit/helpers/contracts.test.js
tests/unit/helpers/users.test.js

contractSeed: le customer s'appelle customerContract
Il y a un commentaire a la ligne 42 de eventsValidation a supprimer
suppression du populate contracts dans helpers/users
il y a un test unitaire ‘it should create a new customer contract’
Suppression du droit customer-{_id} dans la route get contracts.

Com 1276 fix

---

src/repositories/StatRepository.js
tests/integration/seed/statsSeed.js
tests/integration/stat.test.js

- Cas d'usage : sur la page de suivi des plans d'aide c'est le dernier secteur de l'auxiliaire referent qui s'affiche

COM-1495 get last sector of auxiliary

---

src/repositories/StatRepository.js
tests/integration/seed/statsSeed.js
tests/integration/stat.test.js

- Cas d'usage : sur la page des suivi des plans d'aide, on n'affiche pas les beneficiaires qui n'ont plus de plans d'aide.

COM-1489 fix apa hours when funding has ended

---

src/controllers/userController.js
src/helpers/users.js
src/routes/users.js
tests/integration/users.test.js
tests/unit/helpers/users.test.js

- Périmetre roles : Admin / coach
- Cas d'usage : creation du dossier drive pour les auxiliaires

Refacto create drive

---

src/helpers/courses.js
tests/unit/helpers/courses.test.js

- Cas d'usage : externaliser dans le back le calcul de la progression pour une formation

COM-1665: externalize getprogress in back

---

src/helpers/cards.js
src/models/Card.js
src/models/validations/cardValidation.js
src/routes/cards.js
src/routes/preHandlers/cards.js
tests/integration/cards.test.js
tests/integration/seed/cardsSeed.js
tests/unit/helpers/cards.test.js

qcuFalsyAnswers, qcmAnswers et questionAnswers sont fondus en un seul champ qAnswers.
L'utilisation des qcm et des qcu se fera sous la même forme que question answer :
- ajout des champs answer en plus via un bouton
- passage par les routes /{_id}/answers (POST, PUT, DELETE)
Dans cette PR :
- uniquement la refonte en un seul champ
- le fait que qcm et qcu ne soit plus comme avant est voulu (préparation à l'ajout de réponse par bouton)
- on reste sur une modification par la route updateCard, donc les tests seront amenés à être changés. Pour l'instant je les ai adapté pour ne pas avoir d'erreurs et tester que le comportement reste bien le même malgré la fusion des champs.

Com 1691 - refacto qcm/qcu/questionAnswers

---

src/controllers/cardController.js
src/helpers/cards.js
src/routes/cards.js
src/routes/preHandlers/cards.js
tests/integration/cards.test.js
tests/integration/seed/cardsSeed.js
tests/unit/helpers/cards.test.js

Suite du changement sur qcAnswers. L'édition de réponse pour QCM et QCU passe désormais par la route updateQuestionAnswer.
Changement dans l'utilisation de QCM (vu avec Sophie) :
- désormais le texte et la box sont indépendants : on peut avoir une carte qcm sans réponse valide, la carte sera bien sûr  invalide mais réponses seront gardées en back.
Reste à faire :
la route post et delete pour ajouter de nouvelles réponses et les enlever

Com 1691 put

---

src/helpers/users.js
tests/integration/users.test.js
tests/unit/helpers/users.test.js

- Périmetre roles : aucun
- Cas d'usage : Quand je cree un compte sur mobile, firstMobileConnection est directement defini

COM-1711 set firstMobileConnection when creating a user from mobile

---

src/helpers/programs.js
tests/unit/helpers/programs.test.js

- Cas d'usage : les catégories sont populés dans programmes afin de récupérer le nom d'une catégorie et de pouvoir ranger les programmes par catégories dans catalog

COM-1696: populate categories

---

src/helpers/subPrograms.js
tests/unit/helpers/subPrograms.test.js

- Périmetre roles : vendeur admin / rof
- Cas d'usage : dans formations à tester je reçois l'image associé au programme quand elle existe

COM-1742: send image for subprograms from back

---

package-lock.json
package.json

maj d'axios 0.19.2 -> 0.21.0
Résumé
- la methode PURGE est prise en compte
- le body d'une request peut ne pas être décompressé
https://github.com/axios/axios/pull/2661
- les méthodes axios.all() et axios.spread() sont dépréciées
Changelog
https://github.com/axios/axios/blob/master/CHANGELOG.md

COM-1731 - npm update axios

---

tests/unit/helpers/categories.test.js

- [np] Mon code est testé avec des tests d'intégration
- Cas d'usage : plus besoin de ce satané sinon-mongoose pour lister nos belles catégories!

COM-1769 category list without sinon-mongoose

---

src/helpers/eventHistories.js
tests/unit/helpers/eventHistories.test.js

- Périmetre roles : Coach / auxilaire
- Cas d'usage : Je peux supprimer les evenements qui ont un objet `address: {}`

COM-1780 - set adress in history if exists

---

src/helpers/version.js
tests/unit/helpers/version.test.js

sur iphone et android on envoie une build avec `apiVersion: 1`
or pour le moment, sur le server de l'api la version c'est 0
donc apple ne va pas pouvoir tester l'app
j'ai changé l'inégalité en strictement superieur : 
- si l'api recoit du mobile une version superieur a la sienne (maj future) : c'est bon car le mobile est en avance
- si elle recoit la meme : version actuellement en prod donc c'est bon car le mobile est a jour
- si elle recoit une version inferieure, il faut mettre a jour car le mobile est en retard

Allow app validation

---

src/helpers/users.js
src/models/User.js
tests/integration/users.test.js
tests/unit/helpers/users.test.js

- Périmetre interface : tous
- Périmetre roles : formateur & sans role
- Cas d'usage : ne pas renvoyer le refreshToken et le mot de passe quand on créé un utilisateur formateur depuis la web app ou apprenant depuis le mobile
overwrite : https://mongoosejs.com/docs/documents.html

COM-1713: don't send refreshToken after create account

---

src/models/Event.js
src/repositories/EventRepository.js
src/routes/events.js
src/routes/preHandlers/events.js
tests/integration/events.test.js
tests/integration/seed/eventsSeed.js

- [] Mon code est testé unitairement
- Périmetre roles : coach / admin / vendor
Je peux créer un absence sur le planning auxiliaire qui est le prolongement d'une absence existante

COM-1744 - add extension for absence

---

src/helpers/pdf.js
tests/unit/helpers/pdf.test.js

- Périmetre interface : client/vendeur
- Cas d'usage : verifier que la generation des pdf: facture, avoir, convocation, feuilles d'emargement, attestation fiscale fonctionnent toujours. 
Vous pouvez aussi simuler une erreur a la ligne avant browser.newPage() si vous voulez voir ce qu'il se passe en cas d'erreur.

COM-1804 fix memory leak when error from puppeteer

---

src/helpers/historyExport.js
src/repositories/EventRepository.js
tests/integration/exports.test.js
tests/unit/helpers/historyExport.test.js

- Périmetre roles : coach
Sur l'export d'absence (Exports > Historique > Absence), je vois 2 nouvelles colonnes 'Prolongation' et  'Absence d'origine', ayant respectivement oui/non si l'absence est une prolongation et la date de l'absence d'origine si c'est le cas.

COM-1744 - Add extension in absence export

---

src/helpers/draftFinalPay.js
src/helpers/draftPay.js
src/helpers/pay.js
tests/integration/pay.test.js
tests/integration/seed/paySeed.js
tests/unit/helpers/draftFinalPay.test.js
tests/unit/helpers/draftPay.test.js
tests/unit/helpers/pay.test.js

- Périmetre roles : Coach / Auxiliaire
- Cas d'usage : Le compteur d'heures des auxiliaires est remis à zéro en janvier 
en janvier le compteur d'heures correspond au solde du mois. pour tous les autres mois il correspond a la somme du compteur du mois précédent et du solde d'heures du mois. 
C'est visible sur le tableau de bord individuel et la page paie mensuelle.
Pour les tests, voila ce que j'ai regardé. N'hesitez pas a verifier plus si vous vus rendez compte que ce n'est pas suffisant : 
- sur la page de paie mensuelle du mois de janvier, j'ai bien 0 sur diff, compteur M-1. le compteur correspond au solde
- sur la page de paie mensuelle des autre mois, je vois une diff, un compteur M-1, et compteur = solde + compteur M - 1
- idem sur la page de fin de …

Com 1747 reset counter

---

src/helpers/emailOptions.js

- Périmetre interface : vendor / client
Lorsque j'ajoute un apprenant, dans le mail qu'il reçoit je vois les logos Apple et Google Play
Ce qu'il reste à faire : 
La seule solution que j'ai trouvée est d'upload le logo d'Apple (téléchargeable ici https://tools.applemediaservices.com/app-store/) dans GCS et de linker vers cette image.
Ici j'ai upload sur le bucket program-test, mais je pense que sa place est plus dans compani-main.
Résumé des règles de chaque logo :
https://www.mobizel.com/usage-des-badges-play-store-et-app-store/

COM-1795 - Fix Apple Logo

---

src/helpers/dpae.js
tests/unit/helpers/dpae.test.js

Lorsque j'exporte les absences (depuis Paie Mensuelle > Données absences), j'ai deux nouvelles colonnes qui correspondent à (cf schéma) : 
- 0 si l'absence est une prolongation et 1 sinon
- la date de l'absence d'origine si c'es tune prolongation et la startDate de l'absence sinon.
PAS ENCORE SÛR QUE CA FONCTIONNE :
Pour tester, j'ai utilisé le compte de test de 123Paie, ajouté le fichier d'absence exporté dans 123Paie. J'avais bien les absences des auxiliaires modifiés (en accord avec le fichier) mais lorsque je regarde dans informations complémentaires (Préparer la paie > saisie individuelle > maladie puis la petite flèche > liste des prolongations), je ne vois pas l'absence comme étant une prolongation.

COM-1745 - Add prolongation in 123Paie

---

src/helpers/events.js
src/helpers/eventsRepetition.js
tests/unit/helpers/events.test.js
tests/unit/helpers/eventsRepetition.test.js

- Périmetre roles : auxiliaire/coach
- Cas d'usage : mutualisation d'une fonction pour detacher un evenement d'une auxiliaire lors de sa creation en cas de conflit
J'ai aussi renommer `event` dans la methode de creation d'evenement pour avoir des constantes plus claires.

Com 1831 create

---

src/helpers/sectors.js
src/routes/preHandlers/sectors.js
src/routes/sectors.js
tests/integration/sectors.test.js
tests/integration/seed/sectorsSeed.js
tests/unit/helpers/sectors.test.js

- ~~Ce n'est pas une ancienne route utilisée par le mobile~~
- ~~[ ] J'ai bien fait les tests~~
fonctionnent~~
- ~~[ ] Je n'ai pas fait …

COM-1878 - Allow duplicate name for team of different structure

---

src/controllers/taxCertificateController.js
src/helpers/taxCertificates.js
src/repositories/EventRepository.js
tests/unit/helpers/taxCertificates.test.js

fonctionnent~~
-~~ [ ] Je n'ai pas changé les droits dans le fichier rights.js~~
- ~~[ ] Je n'ai pas fait de changement sur le prehandler qui …

COM-1933 - fix serial number in tax certificates

---

src/controllers/contractController.js
src/helpers/contracts.js
src/helpers/subPrograms.js
tests/integration/contracts.test.js
tests/integration/exports.test.js
tests/integration/seed/authenticationSeed.js
tests/integration/seed/contractsSeed.js
tests/unit/helpers/contracts.test.js

fonctionnent~~
- ~~[ ] Je n'ai pas fait de changement sur le prehandler qui …

COM-1949 - fix update contract startdate

---

src/controllers/contractController.js
src/helpers/contracts.js
src/helpers/gDriveStorage.js
tests/integration/contracts.test.js
tests/integration/seed/contractsSeed.js
tests/unit/helpers/contracts.test.js

fonctionnent~~
- ~~[ ] Affichage des pages explorer/mes formations/About/CourseProfile~~
- ~~[ ] Inscription a une formation e-learning~~
- ~~[ ] Possibilité de faire une activité~~
- Mes changements impactent une route utilisée par l'autre plateforme (mobile/webapp):
- Je n'ai pas fait de breaking …

COM-1949 - cannot create version before previous version startDate

---

src/controllers/programController.js
src/helpers/programs.js
src/helpers/translate.js
src/routes/preHandlers/programs.js
src/routes/programs.js
tests/integration/programs.test.js
tests/unit/helpers/programs.test.js

- C'est une ancienne route utilisée par le mobile -np
fonctionnent
- Mes changements impactent une route utilisée par l'autre plateforme (mobile/webapp): -np …

Com 1956 delete

---

src/controllers/subProgramController.js
src/helpers/subPrograms.js
src/routes/preHandlers/subPrograms.js
src/routes/subPrograms.js
tests/integration/seed/subProgramsSeed.js
tests/integration/subPrograms.test.js
tests/unit/helpers/subPrograms.test.js

- ~~Ce n'est pas une ancienne route utilisée par le mobile~~
fonctionnent
- Justification des breaking changes s'il y en a: la route qui n'était accessible que pour les ROF/admin-vendors devient accessible à tous, le tri se fait à partir de la liste des formations pour lesquelles l'utilisateur est testeur, définie dans le préhandler
créer une nouvelle route utilisée par la WEBAPP et toutes les …

COM-1957: allow user to access draft elearning programs which for he/she is tester

---

src/routes/preHandlers/subPrograms.js
src/routes/subPrograms.js
tests/integration/subPrograms.test.js

- ~~[ ] Mon code est testé unitairement~~
-~~ Ce n'est pas une ancienne route utilisée par le mobile~~
fonctionnent
- J'ai …

COM-1957: access to subprogram when user is a tester

---

src/controllers/paymentController.js
src/helpers/payments.js
src/helpers/translate.js
src/routes/payments.js
src/routes/preHandlers/payments.js
tests/integration/payments.test.js
tests/unit/helpers/payments.test.js

- Ce n'est pas une ancienne route utilisée par le mobile 
- C'est une ancienne route utilisée par le mobile -np
fonctionnent
- Mes changements impactent une route utilisée par l'autre plateforme (mobile/webapp): -np …

COM-1954 add route to remove refund

---

src/controllers/administrativeDocumentController.js
src/helpers/administrativeDocument.js
tests/unit/helpers/administrativeDocument.test.js

fonctionnent
-~~ Mes changements impactent une route utilisée par l'autre plateforme (mobile/webapp):~~ …

COM-1961: remove return from create administrative document

---

package.json

Ajout des tests avec tags.
Il vous suffit de rajouter `#tag` à n'importe quel test (dans la description du `it()` ou du` describes()`) et lorsque vous lancerez `npm run test:tag`, tous les tests taggés seront lancés.

Add test:withTag to package.json

---

src/helpers/translate.js
src/routes/preHandlers/questionnaires.js
src/routes/questionnaires.js
tests/integration/questionnaires.test.js
tests/integration/seed/questionnairesSeed.js

- ~~[] Mon code est testé unitairement~~
fonctionnent
- J'ai …

COM-1974: can't create a questionnaire if already one in draft

---

src/helpers/utils.js
src/routes/preHandlers/email.js
tests/integration/email.test.js
tests/unit/helpers/utils.test.js

- ~~[ ] Mon code est testé unitairement~~
fonctionnent
- Mes changements impactent une route utilisée par l'autre plateforme (mobile/webapp):
- J'ai supprimé …

COM-1971: trainer can send email

---

src/helpers/courses.js
tests/unit/helpers/courses.test.js

fonctionnent
-~~ Mes changements impactent une route utilisée par l'autre plateforme (mobile/webapp):~~
- J'ai rendu obligatoire un champs …

COM-1980-fix - Add salesRepresentative identity to course

---

src/helpers/constants.js
src/helpers/version.js
src/routes/version.js
tests/integration/version.test.js
tests/unit/helpers/version.test.js

- Ce n'est pas une ancienne route utilisée par le mobile -np
fonctionnent
- Mes changements impactent une route utilisée par l'autre plateforme (mobile/webapp):
- J'ai supprimé un retour/un champs du retour de la route …

Change check version

---

src/helpers/contracts.js
src/helpers/dates.js
src/helpers/eventsValidation.js
tests/integration/events.test.js
tests/unit/helpers/dates.test.js
tests/unit/helpers/eventsValidation.test.js

- ~~Si mes changements impactent l'application formation~~ :
- ~~Si mes changements impactent l'application erp~~ :
- J'ai retiré …

COM-2030 - refacto event validation

---

src/controllers/questionnaireController.js
src/helpers/questionnaires.js
src/routes/preHandlers/questionnaires.js
src/routes/questionnaires.js
tests/unit/helpers/questionnaires.test.js

- ~~Tests intégrations : ~~
- J'ai retiré …

COM-2037: return end of course questionnaire

---

src/routes/preHandlers/activities.js
src/routes/preHandlers/steps.js
tests/integration/activities.test.js
tests/integration/steps.test.js

COM-2041: allow title edition

---

src/helpers/questionnaires.js
tests/unit/helpers/questionnaires.test.js

COM-2039: minor bug

---

src/helpers/questionnaires.js
tests/unit/helpers/questionnaires.test.js

- ~~Si mes changements impactent l'application erp : ~~ …

COM-2037: display questionnaire when last slot is started

---

src/helpers/draftBills.js
tests/unit/helpers/draftbills.test.js

COM-2081 fix bills for customer with 0 participationrate

---

src/controllers/customerPartnerController.js
src/helpers/customerPartners.js
src/helpers/translate.js
src/routes/customerPartners.js
src/routes/preHandlers/customerPartners.js
tests/integration/customerPartners.test.js
tests/unit/helpers/customerPartners.test.js

COM-2070: remove customer partner

---

src/repositories/EventRepository.js

- Si mes changements impactent l'application erp : -np car pas en prod
- …

COM-2073 populate histories

---

src/helpers/eventHistories.js
src/helpers/eventTimeStamping.js
src/helpers/translate.js
src/routes/events.js
src/routes/preHandlers/events.js
tests/integration/events.test.js
tests/integration/seed/eventsSeed.js
tests/unit/helpers/eventHistories.test.js
tests/unit/helpers/eventTimeStamping.test.js

- Si mes changements impactent l'application formation : -np
- Si mes changements impactent l'application erp : pas en prod
- J'ai …

COM-2074 can timestamp end of intervention

---

package-lock.json
package.json
src/models/Google/Drive.js

- Périmetre interface : Reduire la taille des nodes_modules en important uniquement le paquet drive de googleapis (celui qu'on utilise)
Chargement manuel des documents qui vont sur le drive (fiche auxiliaire)
Affichage des thumbnails
Suppression des documents du drive
Chargement des documents automatique sur le drive suite a la signature en ligne (mandat de prélèvement ou contrat)

COM-2104 - replace googleapis by @googleapis/drive

---

src/routes/events.js
tests/integration/events.test.js

- C'est une ancienne route utilisée par une des apps mobiles -np …

add validation for type and groupby on route get

---

package-lock.json
package.json

PACKAGE MIS À JOUR
dotenv  9.0.2 => 10.0.0
* Add generic support to parse function
* Allow for import "dotenv/config.js"
* Add support to resolve home directory in path via ~
https://github.com/motdotla/dotenv/blob/master/CHANGELOG.md
expect  26.6.2 => 27.0.0
:warning: SEVERAL BREAKING CHANGES (ne semblent pas nous affecter) :warning:
https://github.com/facebook/jest/blob/master/CHANGELOG.md
mongoose-autopopulate  0.13.0 => 0.14.0
feat: add functions option to list out functions to register hooks on
https://github.com/mongodb-js/mongoose-autopopulate/blob/master/History.md
sinon  10.0.0 => 11.0.0
* Explicitly use samsam 6.0.2
* Update packages
* Warn of potential memory leaks
* Fix clock test errors
https://github.com/sinonjs/sinon/blob/master/CHANGELOG.md
DISK INVENTORY X
pas de …

COM-2107: npm update

---

src/helpers/constants.js
src/helpers/customers.js
src/models/Customer.js
src/routes/customers.js
src/routes/preHandlers/customers.js
tests/integration/customers.test.js
tests/integration/seed/customersSeed.js
tests/unit/helpers/customers.test.js

COM-2093: add status to put route

---

src/helpers/draftBills.js
tests/unit/helpers/draftbills.test.js

- Ce n'est pas une ancienne route utilisée par les apps mobiles -np …

Com 2081 fix

---

src/helpers/userCompanies.js
src/helpers/users.js
tests/unit/helpers/userCompanies.test.js
tests/unit/helpers/users.test.js

- [] J'ai bien fait les tests
- Si mes changements impactent l'application erp : -np
- Je n'ai pas fait de breaking change : -np
- J'ai supprimé une route : -np
- J'ai renommé une route : -np
- J'ai ajouté un champ possible dans la route : -np
- J'ai rendu …

add function to create userCompany with verification

---

src/helpers/historyExport.js
src/models/Event.js
src/models/EventHistory.js
src/routes/preHandlers/events.js
tests/unit/helpers/eventTimeStamping.test.js

- Si mes changements impactent l'application formation : -np …

COM-2137 replace MANUAL_TIME_STAMPING by TIME_STAMPING_ACTIONS

---

src/routes/preHandlers/customers.js

MAJ du referent d'un bénéficiaire
- Cas d'usage : lorsque je suis sur la fiche d'un bénéficiaire je peux mettre a jour l'auxiliaire référent
- Pour tester: 
Dans le service: `/src/helpers/authorization` : 
-  importer `const UserCompany = require('../models/UserCompany’);`
- dans `validate`:  
- commenter: `.populate({ path: 'company' })`
- ajouter: `const userCompany = await UserCompany.findOne({ user: user._id }).populate('company').lean();`
- transformer tous les `user.company` en `userCompany.company`
**Test pour verifier que le prehandler fonctionne toujours avec un utilisateur de la meme structure:**
-  commenter le champs `Company` de la collection `Users`
-  sur la fiche bénéficiaire, modifier l'auxiliaire référent
**Test pour vérifier que l’on a bien une 403 avec un utilisateur …

Com 2123-  MAJ du referent d'un bénéficiaire

---

src/routes/preHandlers/contracts.js
tests/integration/contracts.test.js
tests/integration/seed/contractsSeed.js

MAJ du referent d'un bénéficiaire
- Cas d'usage : ETQ Coach ou admin je peux accéder aux contrats d'une auxiliaire 
- Pour tester: 
Dans le service: `/src/helpers/authorization` : 
-  importer `const UserCompany = require('../models/UserCompany’);`
- dans `validate`:  
- commenter: `.populate({ path: 'company' })`
- ajouter: `const userCompany = await UserCompany.findOne({ user: user._id }).populate('company').lean();`
- transformer tous les `user.company` en `userCompany.company`
**Tester que l'on a bien accès aux contrats d'une auxiliaire lorsaue l'on commente le champ `company` dans le modele `Users`**
**Test pour vérifier que l’on a bien une 404 avec un utilisateur d’une autre structure:**
- creer une structure test avec l’abonnement ERP
- ajouter un utilisateur
- sur postman: 	
- …

Com 2125 - userCompany refacto

---

src/routes/preHandlers/pay.js
tests/integration/pay.test.js

Périmetre interface : client
Périmetre roles : client_admin, coach, auxiliaire
Pour tester :
Validation de la paie des auxiliaires sur la page Paie mensuelle
Testée sur postman avec la requête envoyée sur slack:
Avec mon compte
En supprimant company de User avec mon compte
En supprimant company de User avec un compte d'une autre entreprise -> 404

COM-2127: refacto UserCompany in pay preHandler

---

src/routes/preHandlers/contracts.js
tests/integration/contracts.test.js
tests/integration/seed/contractsSeed.js

REFACTO du preHandler authorizecontractcreation
Périmetre interface : client
Périmetre roles : client_admin, coach, auxiliaire
Pour tester :
Création d’un contrat pour un auxiliaire
Testée sur postman avec la requête create a contract (visiblement il faut virer le status de la requête et s'assurer que l'user passé en paramètre existe bien et n'a pas de contract en cours (j'ai créé un auxiliaire pour l'occasion)). Entre chaque test penser à mettre fin au contract pour que le suivant passe 
Avec mon compte
En supprimant company de User avec mon compte
En supprimant company de User avec un compte d'une autre entreprise -> 404

COM-2131: refacto prehandler authorizecontractcreation

---

src/controllers/eventController.js
src/helpers/eventsRepetition.js
src/routes/events.js
src/routes/preHandlers/events.js
tests/unit/helpers/eventsRepetition.test.js

COM-2140: refacto deleterepetition

---

src/routes/preHandlers/finalPay.js
tests/integration/finalPay.test.js
tests/integration/seed/finalPaySeed.js

Périmetre interface : client
Périmetre roles : client_admin
Pour tester :
Validation de la paie des auxiliaires sur la page “Fin de contrats” / STC
- Ajoutez une auxiliaire + contrat + une intervention -> fin de contrat -> STC
Dans postman (lien de la collection en thread du ticket) :
- Changer l'id dans le payload par l'id de votre auxiliaire
- Avec mon compte
- En supprimant company de User avec mon compte
- En supprimant company de User avec un compte d'une autre entreprise -> 404

COM-2128 - use UserCompany in finalPay preHandler

---

src/helpers/dates.js
src/helpers/utils.js
src/repositories/EventRepository.js
src/routes/preHandlers/events.js
tests/integration/events.test.js
tests/unit/helpers/dates.test.js
tests/unit/helpers/utils.test.js
tests/unit/repositories/EventRepositories.test.js

COM-2075 - refacto get events groupBy

---

src/helpers/customers.js
src/helpers/dates.js
src/helpers/events.js
src/helpers/eventsRepetition.js
tests/unit/helpers/customers.test.js
tests/unit/helpers/dates.test.js

Com 2094 clean

---

src/routes/preHandlers/events.js
tests/integration/events.test.js

Refacto du lien structure/utilisateur - Prehandler création / mise à jour d'un évènement affecté
A tester sur la webApp: 
- Création d’une intervention
- Affectation d’une intervention à un auxiliaire (dans la modale  - planning auxiliaire)
- Affectation d’une intervention à un auxiliaire (dans la modale  - planning bénéficiaire)
- Affectation d’une intervention à un auxiliaire (drag&drop)
- Désaffectation d’une intervention pour un auxiliaire (dans la modale  - planning auxiliaire)
- Désaffectation d’une intervention pour un auxiliaire (drag&drop)
- Changement d’auxiliaire pour une intervention (dans la modale - planning auxiliaire)
- Changement d’auxiliaire pour une intervention (dans la modale - planning bénéficiaire)
- Changement d’auxiliaire pour une intervention (drag&drop)
A tester …

Com 2129 - userCompany

---

src/helpers/dates.js
src/helpers/events.js
src/routes/preHandlers/events.js
tests/unit/helpers/events.test.js

Correction d'un bug remonté par Romain : sur la page d'horodatage, je recupere les evenements de la veille et d'aujourd'hui
C'est un soui qui vient de l'absence de gestion de timezone sur un newDate classique + le serveur de la prod est sur l'UTC
Je suis donc revenue sur l'utilisation de moment -> il faudra changer ca quand on aura choisi la librairies de remplacement

COM-2179 - remove getStartOfDay and getEndOfDay

---

src/helpers/dates.js
src/helpers/utils.js
tests/unit/helpers/dates.test.js

Fix events

---

src/helpers/translate.js

- Si mes changements impactent l'application formation : -np 
- J'ai retiré …

COM-2141 modify error message when 409

---

src/helpers/email.js
src/helpers/emailOptions.js
src/jobs/eventRepetitions.js
tests/unit/jobs/eventRepetitions.test.js

Com 2094 - script

---

src/helpers/fundings.js
src/models/Customer.js
src/routes/customers.js
src/routes/preHandlers/customers.js
tests/integration/customers.test.js
tests/integration/seed/customersSeed.js
tests/unit/helpers/fundings.test.js

COM-2143: add teletransmissionId to create and edit funding

---

src/routes/validations/customer.js

COM-2186: remove default on customerParticipationRate

---

src/routes/preHandlers/courses.js
tests/integration/seed/coursesSeed.js

- [] J'ai bien fait les tests
apps mobiles fonctionnent - j'ai modifie un test qui ne fonctionnait pas
- Si mes changements impactent l'application formation : 
- Si mes changements impactent l'application erp : -np
- J'ai supprimé une route : -np
- J'ai renommé une route : -np
- J'ai ajouté un champ …

COM-2196 fix access to interb2b course

---

src/routes/preHandlers/courses.js
tests/integration/courses.test.js
tests/integration/seed/coursesSeed.js

Commenter le champ company du modele User
Dans le service: /src/helpers/authorization : 
- importer const UserCompany = require('../models/UserCompany’);
- dans validate:  
- commenter: .populate({ path: 'company' })
- ajouter: const userCompany = await UserCompany.findOne({ user: user._id }).populate('company').lean();
- transformer tous les user.company en userCompany.company => pour userRights (l.41) et credentials.company (l.58) plutôt mettreget(userCompany, 'company') || null
- Je peux accéder au formation d'un apprenant de ma structure
- Je peux accéder au formation d'un apprenant d'une autre structure
- Je peux accéder au formation d'un apprenant sans structure
- Je peux accéder au formation d'un apprenant de ma structure
- Je ne peux pas accéder au formation d'un apprenant d'une …

Com 2183 - userCompany

---

src/helpers/activityHistories.js
tests/unit/helpers/activityHistories.test.js

- Périmetre roles : admin / coach
Refacto userCompany du service activityHistories.
Pour tester :
- afficher le dashboard formation sur dev et sur ma branche -> les deux sont identiques
- sur postman, appeler la route avec un utilisateur d'une autre company -> on ne reçoit les informations que de cette structure
- en appliquant les modifications usuelles (commenter le champ company de user + refacto validate) -> la route fonctionne bien avec mon compte et le compte de l'autre structure.
Voici la route postman : https://www.getpostman.com/collections/2cac4c813897e59ad118

COM-2135 - Refacto userCompany in activityHistories helper

---

src/helpers/eventsRepetition.js
tests/unit/helpers/eventsRepetition.test.js

COM-2187: block creation for event after stopping date

---

src/helpers/events.js
src/routes/preHandlers/events.js
tests/integration/events.test.js
tests/unit/helpers/events.test.js

- ETQ coach, sur le planning auxiliaires, afficher les heures travaillées par rapport aux heures contrats a coté de l’avatar de l’auxiliaire
- ETQ auxiliaire, sur le planning auxiliaires, afficher les heures travaillées par rapport aux heures contrats a coté de l’avatar de l’auxiliaire
Sur postman:
- faire appel a la route GET /events/working-stats avec:
- en query: startDate, endDate et une auxiliaire de la même structure --> 200
- en query: startDate, endDate et une auxiliaire d'une autre structure --> 404
- en query: …

Com 2136 rebase

---

src/routes/customers.js
tests/integration/customers.test.js

COM-2174: add scope

---

tests/unit/helpers/eventsRepetition.test.js

Fix des tests unitaires de :
-  createRepetitionsEveryDay
- createRepetitionsEveryWeekDay
- createRepetitionsByWeek
On utilise un moment range plutôt que de créer la range à la main.
Et on évite d'utiliser moment.add() (pour utiliser le moins de fonctions moment possible dans nos tests)

Com 2187 fix

---

src/helpers/users.js
tests/unit/helpers/users.test.js

COM-2171: userCompany in getlearnerlist

---

package-lock.json
package.json

PACKAGES MIS À JOUR
@hapi/boom    9.1.2  ->  9.1.3  no info yet :  https://hapi.dev/module/boom/changelog/
eslint       7.29.0  -> 7.30.0  minor fix and update : https://github.com/eslint/eslint/blob/master/CHANGELOG.md
mocha         9.0.1  -> 9.0.2 minor fix and changed dependencies : https://github.com/mochajs/mocha/blob/master/CHANGELOG.md
mongoose     5.13.0  -> 5.13.2 minor fixs : https://github.com/Automattic/mongoose/blob/master/History.md
pdfmake      0.1.71 ->  0.1.72 Introduced new build-vfs.js script to build virtual file system for fonts ( no use for compani yet) : https://github.com/bpampuch/pdfmake/releases
qrcode the fork is still uptodate : https://github.com/sophiemoustard/node-qrcode

COM-2197 npm update

---

src/helpers/partnerOrganizations.js
tests/unit/helpers/partnerOrganizations.test.js

COM-2071 display customer creation date

---

src/helpers/eventsRepetition.js
tests/unit/helpers/eventsRepetition.test.js

- Tests intégrations : JE N'AI PAS LA POSSIBILITER DE FAIRE TOURNER LES TESTS D'INTE AVEC MON PROCESSEUR 👎 
- J'ai supprimé un retour/un champs du retour de la route :
- J'ai ajouté un modèle spécifique à une structure:
- J'ai changé un modèle …

COM-2240 remove CustomerFindOne call if eventType is not intervention

---

src/helpers/constants.js
src/helpers/eventHistories.js
src/models/EventHistory.js
src/routes/events.js
tests/integration/events.test.js
tests/unit/helpers/eventHistories.test.js

Com 2189 2

---

src/routes/preHandlers/users.js
tests/integration/seed/usersSeed.js
tests/integration/users.test.js

- [] J'ai bien fait les tests
- Justification des breaking changes s'il y en a: empêcher l'accès à un utilisateur sans compagnie ce qui n'est pas un cas possible en mobile
et toutes les nouvelles …

COM-2203: block access to user without company

---

src/helpers/questionnaires.js
tests/unit/helpers/questionnaires.test.js

- ~~Tests intégrations : ~~
- J'ai …

COM-2304: populate historiesCount

---

src/helpers/eventHistories.js
src/models/EventHistory.js
src/routes/eventHistories.js
tests/integration/eventHistories.test.js
tests/unit/helpers/eventHistories.test.js

- ~~[ ] J'ai fait de nouveaux tests sans modifier les anciens pour s'assurer que les anciennes versions des
apps mobiles fonctionnent~~
~~### MODIFICATIONS SUR LES ROUTES IMPACTANT UNE AUTRE PLATEFORME~~
(si la route est utilisée en mobile: ne pas la renommer et plutôt créer …

COM-2327 - allow action in event history payload

---

src/helpers/questionnaires.js
tests/unit/helpers/questionnaires.test.js

COM-2302: populate trainer

---

src/helpers/bills.js
tests/unit/helpers/bills.test.js

COM-2341 - fix amount bill

---

src/helpers/events.js
src/routes/events.js
src/routes/preHandlers/events.js
tests/integration/events.test.js
tests/unit/helpers/events.test.js

- ~~J'ai ajouté un champ possible dans la route :~~
- ~~J'ai rendu obligatoire un champs de la route :~~
- …

COM-2294 - handle repetitions

---

src/helpers/bills.js
src/models/schemaDefinitions/billing.js
src/routes/preHandlers/bills.js
tests/unit/helpers/bills.test.js

Com 2298 billing article

---

src/models/Google/Drive.js

- ~[ ] Mon code est testé unitairement~
- ~Tests intégrations~ :
~### MODIFICATIONS SUR LES ROUTES IMPACTANT UNE AUTRE PLATEFORME~
- J'ai …

COM-2230 retrieve id instead of url

---

src/helpers/distanceMatrix.js
src/helpers/draftPay.js
tests/unit/helpers/distanceMatrix.test.js
tests/unit/helpers/draftPay.test.js

-~~ Si mes changements impactent l'application formation :~~
-~~ Si mes changements impactent l'application erp :~~
- J'ai …

COM-2295: fix if specific transport is private car

---

src/helpers/bills.js
tests/unit/helpers/bills.test.js

Comment reproduire le bug :
- Facturer un bénéficiaire pour le mois en cours (pour le 15/09 par exemple) -> tout ce passe bien
- Ajouter une facture manuelle
- Facturer un autre bénéficiaire pour le mois en cours -> vous avez l'erreur suivante en back : E11000 duplicate key error collection: local.bills index: number dup key: { number: "FACT-10109210000x"}.
Cela vient du fait que les factures manuelles avaient pour `number` (leur clé unique) le dernier billNumber + 1 alors que les factures automatiques ont pour `number` le dernier billNumber tout court.
J'ai rétabli le fait que les factures manuelles ont désormais le dernier billNumber comme number

COM-2353 - Fix billnumber for manual bills

---

src/helpers/bills.js
src/models/schemaDefinitions/billing.js
tests/unit/helpers/bills.test.js

Oubli du champ discount dans `bill.billingItemList`

COM-2329 - Fix missing discount field in bill billingItemList

---

src/helpers/bills.js
tests/unit/helpers/bills.test.js

COM-2330 - Add TPP to bill pdf

---

src/models/Card.js

COM-2324: fix bug when create media card

---

src/routes/preHandlers/services.js
tests/integration/services.test.js

COM-2354: can't have two versions with same date

---

src/routes/validations/customer.js
tests/integration/customers.test.js

COM-2399 - allow empty date

---

.github/workflows/lint.yml
.github/workflows/node.js.yml
package-lock.json
package.json
src/helpers/dates.js

Node Js 14.16.0 => 14.18.0
Pré-requis
nvm install 14.18.0 (si pas déjà fait)
nvm use 14.18.0 sur compani-api (penser à le changer dans la config iTerm si besoin)
npm i -g nodemon (si pas déjà fait)
rm -rf node_modules && rm package-lock.json && npm i

[ne pas fusionner] COM-2344: update node js

---

package-lock.json
package.json
src/helpers/docx.js
tests/unit/helpers/docx.test.js

nmp outdated :
Axios s'est rajouté ce matin : 0.21.4  -> 0.22.0 : pas de changement importants. (pas de correction du bug des appels infinis) https://github.com/axios/axios/blob/master/CHANGELOG.md
On  attend d'être sûr.e de nous pour mettre a jour le driver mongo.
La maj de mongoose depend du driver.
La maj de mongoose-autopopulate depend de mongoose.
---
Docxtemplater : 
en ajoutant des arguments au constructeur Docxtemplater, l'exectution du test bloque. Je n'ai pas reussi, a "stuber" l'instance de Docxtemplater (comme pour zippiz). J'ai l'impression que le constructeur de Docxtemplater n'est pas construit comme l'attend sinon.stub. jsp 😕 
J'ai donc séparé l'instanciation et le rendu de docxtemplater a part, pour pouvoir facilement mettre un stub. Qu'en pensez vous ?

COM-2357 docxtemplater new syntaxe

---

src/helpers/constants.js
src/models/Step.js
tests/integration/activities.test.js
tests/integration/programs.test.js
tests/integration/seed/activitiesSeed.js
tests/integration/seed/programsSeed.js

🟠  A ce propos je me rend compte qu'on ne test pas les virtuals. Est-ce qu'il faudrait le faire ? 
(j'ai testé depuis le navigateur que la pastille orange apparait ou non selon différentes conditions)
- ~Tests intégrations~ :
(si la route est utilisée en mobile: ne pas la renommer et plutôt créer …

COM-2372 add remote step type

---

src/helpers/courses.js
tests/unit/helpers/courses.test.js

- ~~Tests intégrations :~~ -np
- J'ai …

COM-2385: don't return allSettled status if no phone numbers

---

src/routes/preHandlers/bills.js
tests/integration/bills.test.js
tests/integration/seed/billsSeed.js

COM-2368 prevent billing archived customer

---

src/helpers/programs.js
tests/integration/programs.test.js
tests/unit/helpers/programs.test.js

COM-2424 populate subProgram's name and program in step

---

src/helpers/delivery.js
src/repositories/EventRepository.js
tests/unit/helpers/delivery.test.js

COM-2467 - do not call methods if no event

---

src/routes/preHandlers/events.js
tests/integration/events.test.js

COM-2472 - allows auxiliaries to suppress mass interventions

---

src/models/User.js
src/routes/users.js

COM-2504 - clean user model

---

src/helpers/customerAbsences.js
src/helpers/eventsValidation.js
src/helpers/translate.js
tests/unit/customerAbsences.test.js
tests/unit/helpers/eventsValidation.test.js

COM-2474 - Prevent event creation and update if customer is absent

---

src/routes/preHandlers/courseSlot.js
tests/integration/courseSlots.test.js
tests/integration/seed/courseSlotsSeed.js

-~~ C'est une ancienne route utilisée par une des apps mobiles~~
- J'ai …

COM-2480: block slot addition and edition

---

tests/integration/courses.test.js

-~~C'est une ancienne route utilisée par une des apps mobiles~~
-~~Si mes changements impactent l'application erp :~~
- J'ai retiré …

COM-2484: add integration test

---

src/routes/courses.js
src/routes/preHandlers/courses.js
tests/integration/courses.test.js
tests/integration/seed/coursesSeed.js

COM-2483 add integration test

---

src/helpers/events.js
tests/integration/events.test.js

COM-2473 remove events before creating absence

---

package-lock.json
package.json
src/helpers/companiDates.js
src/helpers/courseHistories.js
tests/unit/helpers/companiDates.test.js

COM-2514: replace moment with luxon in coursehistories

---

src/helpers/eventHistories.js
src/routes/eventHistories.js
src/routes/validations/utils.js
tests/integration/eventHistories.test.js
tests/integration/seed/eventHistoriesSeed.js
tests/unit/helpers/eventHistories.test.js

- Justification des breaking changes s'il y en a: -np
- ~~J'ai rendu obligatoire un champs de la route :~~
- …

COM-2471 - Add isCancelled

---

src/helpers/draftPay.js
tests/unit/helpers/draftPay.test.js

COM-2562 keep only positive break duration

---

tests/integration/seed/coursesSeed.js

COM-2284: remove password for users seeds

---

src/controllers/programController.js
src/helpers/constants.js
src/helpers/notifications.js
src/helpers/programs.js
src/helpers/subPrograms.js
src/routes/programs.js
tests/integration/programs.test.js
tests/unit/helpers/notifications.test.js
tests/unit/helpers/programs.test.js
tests/unit/helpers/subPrograms.test.js

- ~~Justification des breaking changes s'il y en a:~~
-~~ J'ai ajouté un champ possible dans la route :~~
- ~~J'ai rendu obligatoire un champs de la route …

COM-2516: send notification for new elearning course

---

src/helpers/notifications.js
tests/unit/helpers/notifications.test.js

-~~Si mes changements impactent l'application formation :~~
- J'ai …

COM-2516: not size rather than where

---

src/helpers/draftBills.js
src/repositories/EventRepository.js
tests/unit/helpers/draftbills.test.js

COM-2554 - prevent tpp billing for cancelledEvent

---

src/routes/preHandlers/customerAbsences.js

- Si mes changements impactent l'application erp : -np
- J'ai retiré …

COM-2552 - fix bug

---

package.json
src/helpers/dates/companiDates.js
src/routes/preHandlers/courseSlot.js
tests/unit/helpers/dates/companiDates.test.js

COM-2559: add issameorbefore luxon

---

tests/integration/seed/eventsSeed.js
tests/integration/seed/exportsSeed.js
tests/integration/seed/finalPaySeed.js
tests/integration/seed/helpersSeed.js

Revue des tests et des seeds suivants :
events
exports
finalPay
helpers
Ce qui a été fait :
Ajout d'un Promise.all dans le populateDB
Changement des insertMany en create
Si on a des utilisateurs dans les seeds et qu’ils ne servent pas à l'authentification, pas besoin de leur assigner de mot de passe
pas de modification sur les seeds d'authentification

COM-2285: refacto populateDB

---

tests/integration/seed/internalHoursSeed.js
tests/integration/seed/partnerOrganizationsSeed.js
tests/integration/seed/partnersSeed.js
tests/integration/seed/payDocumentsSeed.js
tests/integration/seed/paySeed.js
tests/integration/seed/paymentsSeed.js
tests/integration/seed/programsSeed.js

Revue des tests et des seeds suivants :
internalHours
partnerOrganizations
partners
pay
payDocuments
payments
programs
Ce qui a été fait :
Ajout d'un Promise.all dans le populateDB
Changement des insertMany en create
Si on a des utilisateurs dans les seeds et qu’ils ne servent pas à l'authentification, pas besoin de leur assigner de mot de passe
pas de modification sur les seeds d'authentification

COM-2286: refacto populateDB

---

src/routes/preHandlers/sms.js
tests/integration/seed/smsSeed.js
tests/integration/sms.test.js

| <ul><li>[ ] oui </li></ul> | <ul><li>[x] non</li></ul> | J'ai codé les tests unitaires
| <ul><li>[x] oui </li></ul> | <ul><li>[ ] non</li></ul> | J'ai codé les tests d'intégration
| <ul><li>[ ] oui </li></ul> | <ul><li>[x] non</li></ul> | C'est une ancienne route utilisée par les apps mobiles. | <ul><li>[ ] Si oui, J'ai fait de nouveaux tests sans modifier les anciens</li></ul>
---
| …

COM-2622 prehandler check all matching numbers

---

src/helpers/constants.js
src/helpers/courses.js
src/helpers/dates/companiDates.js
src/helpers/dates/companiDurations.js
tests/unit/helpers/dates/companiDates.test.js
tests/unit/helpers/dates/companiDuration.test.js

| <ul><li>[x] oui </li></ul> | <ul><li>[ ] non</li></ul> | J'ai codé les tests unitaires
| <ul><li>[ ] oui </li></ul> | <ul><li>[x] non</li></ul> | J'ai codé les tests d'intégration
| <ul><li>[ ] oui </li></ul> | <ul><li>[x] non</li></ul> | C'est une ancienne route utilisée par les apps mobiles. | <ul><li>[ ] Si oui, J'ai fait de nouveaux tests sans modifier les anciens</li></ul>
---
| …

COM-2586 - modify CompaniDate.diff() to return an object

---

src/helpers/dates/companiDates.js
src/helpers/dates/holidays.js
tests/unit/helpers/dates/companiDates.test.js

</details>
---
</details>
---
</details>
---
- Périmètre interfaces / rôles : ---
- Creation de la fct `isHoliday`
- pas de changement dans le code (ca viendra plus tard)
- bien regarder les tests, eventuellement faire des console.log
- Avec momen.js, on utilise qui s'appelle `moment-business-days`. Cette lib est configurée pour l'année en cours, l'année suivante et l'année precedente... Avec la fct developpée dans cette PR, on peut calculer si une date est feriee ou non, et ce pour n'importe quelle annee. C'est pourquoi je test avec des dates de 2000, 2010 …

COM-2650 isHoliday

---

src/helpers/courses.js
src/helpers/steps.js
tests/unit/helpers/courses.test.js

</details>
---
</details>
---
</details>
---
- Périmètre interfaces / rôles : client_admin/coach/vendor_admin/rof
- Cas d'usage : je peux visualiser les émargements d'un apprenant sur son profil
- sur le profil d'un appreant dans le suivi des formations je vois ses émargements pour les formations mixtes (côté client et vendeur)

COM-2642: return slots in steps

---

src/helpers/bills.js
src/helpers/dates/companiDates.js
tests/unit/helpers/bills.test.js
tests/unit/helpers/dates/companiDates.test.js

</details>
---
</details>
---
</details>
---
- Périmètre interfaces / rôles : Admin / Aidant 
- Cas d'usage : Quand il y a plusieurs financement pour une même souscription, je vois le montant du dernier évènement facturé dans le pdf de la facture
Ajouter un financement avec une date de fin
Ajouter un nouveau financement sans date de fin - mettre un prix different
Facturer les interventions : au moins une qui est facturée avec le 2eme financement
Quand je telecharge le PDF, j'ai bien le montant du 2eme financement
_Si tu as lu cette description, pense a réagir avec …

COM-2677 - fix funding display

---

src/routes/thirdPartyPayers.js
tests/integration/seed/thirdPartyPayersSeed.js
tests/integration/thirdPartyPayers.test.js

</details>
---
</details>
---
</details>
---
- Périmètre interfaces / rôles : compani outils
- dans config benef > modal edition de ttp :  je peux remettre a '' les champs "type d'aide" et "identifiant structure" (si l'id de teletransmission est null)
-  lorsque l'id teletransmission est nul, je vide le champ "type d'aide", je valide et je reouvre la modal d'edition => la valeur a disparue
- meme chose avec le champ "id structure"

Com 2729 fix 2

---

src/helpers/courses.js
tests/unit/helpers/courses.test.js

</details>
---
</details>
---
</details>
---
- Périmètre interfaces / rôles : mobile / vendeur  tous/rof/admin
- Cas d'usage : je ne vois le bouton de téléchargement que si le dernier créneau a été émargé pour un stagiaire
- côté mobile :
- sur le profil : le nombre de formation s'affiche bien
- sur la liste des formation : tout s'affiche bien  
- sur une formation elearning : je ne vois pas le bouton de téléchargement
- sur une formation mixte en cours ou sans émargement sur le dernier créneau : je ne vois pas le bouton de téléchargement
- sur une formation mixte …

COM-2758: return boolean to display download button

---

src/helpers/bills.js
src/helpers/draftBills.js
src/models/Bill.js
src/models/Event.js
src/models/FundingHistory.js
src/models/schemaDefinitions/billing.js
src/routes/bills.js
tests/integration/seed/billsSeed.js
tests/unit/helpers/bills.test.js
tests/unit/helpers/draftbills.test.js

</details>
---
- on modifie le type de champs qui ne sont pas envoyés dans les appels des routes cote mobile 
</details>
---
</details>
---
- Périmètre interfaces / rôles : admin client
- Cas d'usage : lorsque je cree une facture avec des remises, les champs sont enregistres en bdd avec le bon type.
- Comment tester ? 
- en front: se mettre sur la branche feature-big-number-bills
- lancer le script
- verifier que les pages balances clients, bordereaux tiers-payeur et onglet facture sur la page beneficiaire s'affichent correctement
- creer un beneficiaire
- ajouter 3 souscription relié a …

Com 2809-2

---

src/helpers/creditNotes.js
tests/integration/exports.test.js
tests/unit/helpers/creditNotes.test.js

- [] J'ai codé les tests d'intégration
</details>
---
</details>
---
</details>
---
- Périmètre interfaces / rôles : admin client
- Cas d'usage : lorsque l'on cree un avoir pour un tiers-payeur, l'historique de financement est mis a jour et les champs `caerHours` et `amountTTC` sont des string
- lancer le script
- creer un beneficiaire
- ajouter 3 souscriptions reliées a 3 services différents 
- lui ajouter 3 financements chacun relié a une des souscriptions:
- financement 1: horaire de fréquence mensuelle
- financement 2: horaire de fréquence en une seule fois
- …

COM-2858 - transforms careHours and amountTTC in string

---

src/helpers/delivery.js
tests/unit/helpers/delivery.test.js

</details>
---
</details>
---
</details>
---
- Périmètre interfaces / rôles : admin client
- Cas d'usage : quand je telecharge le fichier de teletransmission, les interventions qui n'ont jamais ete horodate ont le code CRE plutot que CO2
- Choisir un tiers payeur
- Verifier qu'il est en facturation direct
- Lui ajouter un id de teletransmission
- Ajouter un id de teletransmission a un beneficiaire ayant un plan d'aide avec ce tiers payeurs
- Faire en sorte que le beneficiaire ait des interventions : 
- facturees
- non facturees
- horodates
- horodates a moitie
- horodates …

COM-2870 add CRE code for event with no timestamp even cancelled ones

---

src/helpers/delivery.js
tests/unit/helpers/delivery.test.js

</details>
---
</details>
---
</details>
---
- Périmètre interfaces / rôles : admin client
- Cas d'usage : J'ai la balise `EffectiveCISpecifiedPeriod` des qu'il y a un horodatage (annulé ou non)
- Comment tester ? : Vérifier différents cas (horodatage puis annulation ou non de la date de début ou de fin, horodatage puis annulation puis re-horodatage) et vérifier que des qu'il y a eu horodatage a un momeent la balise est bien presente avec comme valeur le dernier horodatage. 

COM-2870 change when specified time is in the file

---

src/helpers/utils.js
tests/unit/helpers/utils.test.js

</details>
---
</details>
---
</details>
---
- Périmètre interfaces / rôles : vendeur et client/ admin, coach, aidant
- Cas d'usage : Intl utilise les nombres js. Du coup si on lui passe un nombre BigNumber qui n'existe pas en js, cela pose probleme car il va d'abord modifier le nombre pour avoir un nombre js puis faire l'arrondi, ce qui peut poser probleme. Par exemple le nombre 595.7549999999999838 n'existe pas en js et est donc transforme en 595.755, ce qui arrondi donne 595.76 vs 595.75 qui est la valeur attendue.
J'ai tout de meme conservé Intl qui permet de formatter les nombres comme on le …

Com 2893 intl

---

src/routes/preHandlers/courses.js
tests/integration/courses.test.js

</details>
---
</details>
---
</details>
---
- Périmètre interfaces / rôles : formation / coach ou admin client
- un.e coach peut voir les infos sur le profile d'une formation elearning meme si aucun.e apprenant.e de sa structure ne suis cette formation
- ETQAdmin sur la page d’une formation e-learning : 
- si j’ai des apprenants de ma structure inscrits a la formation, je vois les infos
- si je n’ai pas d’apprenants de ma structure inscrits, je vois les infos
- ETQAdmin sur la page d’une formation mixte interb2b: 
- si j’ai des apprenants de ma structure …

COM-2960 fix prehandler to authorize elearning for coach

---

src/helpers/historyExport.js
tests/unit/helpers/historyExport.test.js

</details>
---
</details>
---
</details>
---
- Périmètre interfaces / rôles : ETQ Admin
- Cas d'usage : dans l'export des historiques d'interventions et heures internes, les heures de debut et de fin planifiées sont différentes des heures horodatées
- télécharger l'export des historiques d'intervention et heures internes et verifier que les heures de de début et de fin planifiées sont les bonnes 
- versifier que l'export sur une période d'un an fonctionne correctement (~ 20sec pour generer le doc)

COM-2992 - fix dates displays in working events export

---

src/helpers/eventsValidation.js
tests/unit/helpers/eventsValidation.test.js

</details>
---
</details>
---
</details>
---
- Périmètre interfaces / rôles : client coach
- Cas d'usage : refacto code pour eviter de passer par du code specifique a une auxiliaire quand une repeittion est affectee a un secteur
- Comment tester ? : Vérifier que l'assignation de repetition/evenement se passent bien entre auxiliaires/secteurs

COM-3015 dont check contract if assigning repetition to sector

---

tests/integration/events.test.js
tests/integration/seed/eventsSeed.js

</details>
---
</details>
---
</details>
---
- Périmètre interfaces / rôles : client auxiliaire
- Cas d'usage : ajout de test d'intégration pour vérifier qu'on bloque la création d'absence sur des événements facturés ou horodatés
- Comment tester ? : faire tourner les tests d'intégration

COM-3022: add integration test

---

src/helpers/dates/companiDurations.js
tests/unit/helpers/dates/companiDuration.test.js

</details>
---
</details>
---
</details>
---
Note : normalement ce ticket et les suivants peuvent aller directement sur dev, il n'y a pas de modifications qui cassent des fonctionnalités
- Périmètre interfaces / rôles : np
- Cas d'usage : CompaniDuration accepte a présent les durées ISO 
- Vérifier les tests unitaires 
- Si vous voulez vérifier le fonctionnement sur un cas concret + comprendre comment fonctionne les strings iso : Vous pouvez tester avec l'appel à CompaniDuration dans step `getPresenceStepProgress`, et regarder sur le profil d'un apprenant comment …

COM-3213 CompaniDuration accepts iso string

---

src/helpers/dates/companiDurations.js
tests/unit/helpers/dates/companiDuration.test.js

</details>
---
</details>
---
</details>

COM-3248: add toISO method

---

src/helpers/constants.js
src/helpers/dates/companiDurations.js
src/helpers/utils.js
tests/unit/helpers/dates/companiDuration.test.js
tests/unit/helpers/utils.test.js

</details>
---
</details>
---
</details>

COM-3216 use new .diff

---

src/helpers/constants.js
tests/unit/helpers/dates/companiDuration.test.js

</details>
---
</details>
---
</details>

COM-3267 accept millis on objet format in companiDuration parser

---

src/helpers/dates/companiDurations.js
tests/unit/helpers/dates/companiDuration.test.js

</details>
---
</details>
---
</details>
Note : ajout d'une methode utilisée sur mobile

COM-3249 add isEquivalentTo method in companiDuration

---

src/helpers/dates/companiIntervals.js
tests/unit/helpers/dates/companiIntervals.test.js

</details>
---
</details>
---
</details>

COM-3309 refacto CompaniInterval.rangeBy

---

src/helpers/translate.js
src/routes/preHandlers/courseSlot.js
tests/integration/courseSlots.test.js

</details>
---
</details>
---
</details>

COM-3382 - can't remove courseSlot dates if attendances

---

.github/workflows/integration.js.yml
.github/workflows/lint.yml

Mise à jour des library `actions/checkout` et `actions/setup-node` car les actions utilisant node12 est bientot déprécié.

COM-3371 update github action library

---

src/routes/vendorCompanies.js
tests/integration/vendorCompanies.test.js

</details>
---
</details>
---
</details>

COM-3426: can get and update activity declaration number

---

src/routes/courses.js
src/routes/preHandlers/courses.js
tests/integration/courses.test.js

</details>
---
</details>
---
</details>

COM-3484: can't get attendance sheets in inter as coach

---

src/helpers/courses.js
tests/unit/helpers/courses.test.js

</details>
---
</details>
---
</details>

COM-3566: return type for courses list

---

package.json
src/helpers/activities.js
src/helpers/payDocuments.js
src/helpers/questionnaires.js
src/models/preHooks/validate.js
tests/unit/helpers/activities.test.js
tests/unit/helpers/payDocuments.test.js
tests/unit/helpers/questionnaires.test.js
yarn.lock

Yarn Upgrade - 05/03/24
Aperçu de `yarn outdated` avant de faire les maj​ :
[Lien vers les changelogs](https://www.notion.so/compani/a023ffcce61343bfbb78024531bacde8?v=3ed3084fa89f426b9813c1c3e6bdfc48)
- @google-cloud/storage : 6.9.5 > 7.7.0
- RAS
-  @googleapis/drive : 4.0.1 > 8.6.1
-  je n'ai pas vu de breaking changes pour drive, mise a jour de l'api 
- @hapi/eslint-plugin : 5.1.0 > 6.0.0 
- version minimale de node : 14 et compatibilité avec node 18
- mise a jour d'eslint
- cron : 2.1.0 > 3.1.6 
- Fixs + breaking changes mais jai pas l'impression que ces changements impactent l'utilisation qu'on en a : https://github.com/kelektiv/node-cron/blob/main/CHANGELOG.md#-breaking-changes
- mongoose: 7.4.1 > 8.1.1 
- A partir de la version 8  `findByIdAndRemove()` n'existe plus, il faut …

COM-3658 - yarn upgrade

---

src/helpers/holdings.js
tests/unit/helpers/holdings.test.js

</details>
---
</details>
---
</details>

COM-3694: populate companies

---

src/helpers/questionnaires.js
tests/integration/questionnaires.test.js
tests/unit/helpers/questionnaires.test.js

</details>
---
</details>
---
</details>

COM-3698 - get only Expectations and End_of_course questionnaires if query is {}

---

src/helpers/courses.js
tests/unit/helpers/courses.test.js

</details>
---
</details>
---
</details>

COM-3806 : select isValidated in getQuestionnaires

---

src/routes/preHandlers/attendanceSheets.js
tests/integration/attendanceSheets.test.js
tests/integration/courses.test.js
tests/integration/seed/coursesSeed.js

</details>
---
</details>
---
</details>

COM-3828 - authorize all trainers to get and download attendance Sheets

---

src/routes/preHandlers/courses.js
tests/integration/courses.test.js

</details>
---
</details>
---
</details>

COM-3837 - authorize all trainers to get and see questionnaire histories

---

package.json
yarn.lock

Création du nouveau fork du repo : https://github.com/soldair/node-qrcode
Modification du package.json pour pointer vers le repo forké

COM-3893 - fork node/qrcode and linked it in package.json

---

src/helpers/courses.js
tests/unit/helpers/courses.test.js

</details>
---
</details>
---
</details>

COM-3943: create login code if tutor without connection infos

---

src/routes/courseBills.js
src/routes/preHandlers/courseBills.js
tests/integration/courseBills.test.js

</details>
---
</details>
---
</details>

COM-4057: can send description only for trainer fees with percentage
